/**
 * 会员营销域文案键表（商家端大批片 5 · 批内末片）
 *
 * 覆盖：MarketingPage（/marketing 五区：会员标签/券矩阵/定向发放/生日营销/活动配置）
 * + MarketingLedgerPage（/marketing-ledger 四区：支出/换货/退货待检/报表快照）。
 * 纪律照 copy/pass.ts：经营性文案一律经本表取值，组件内零硬编码；
 * 数值/端点名不进表，渲染层读数据经 {var} 插值。
 */

import { withCopyOverrides } from '@philia/shared';

const MARKETING_COPY_TABLE = {
  /* ---- MarketingPage 页级 ---- */
  'mk.page.title': '会员营销',
  'mk.page.sub': '会员标签 · 券矩阵 · 定向发放 · 生日营销 · 活动配置',
  'mk.page.toLedger': '营销台账 →',
  'mk.guide.title': '会员营销由店长或店主管理',
  'mk.guide.hint': '标签/券/活动配置属管理层视界（server 硬闸门兜底）；请切换店长或店主账号。',
  'mk.common.loadFail': '加载失败，请检查网络后重试',
  'mk.common.retry': '重新加载',
  'mk.common.cancel': '取消',
  'mk.common.submit': '确认提交',
  'mk.common.submitting': '提交中…',

  /* ---- 区 1 会员标签 ---- */
  'mk.tag.title': '会员标签',
  'mk.tag.aside': '近 500 条 · 更新倒序',
  'mk.tag.filterAll': '全部',
  'mk.tag.kindSpecies': '猫狗',
  'mk.tag.kindSize': '体型',
  'mk.tag.kindPref': '偏好',
  'mk.tag.valueFilterPh': '按标签值滤（如 dog）',
  'mk.tag.setCta': '＋ 打标',
  'mk.tag.colMember': '会员',
  'mk.tag.colKind': '类',
  'mk.tag.colValue': '值',
  'mk.tag.colTime': '更新',
  'mk.tag.empty': '暂无标签——给会员打上猫狗/体型/偏好标，定向发放才能瞄得准',
  'mk.tag.modalTitle': '打标（同员同类覆盖写）',
  'mk.tag.userId': '会员 userId',
  'mk.tag.userIdHint': '用户主键（次卡/会员页可见）',
  'mk.tag.kind': '标签类',
  'mk.tag.value': '标签值',
  'mk.tag.speciesDog': '狗（dog）',
  'mk.tag.speciesCat': '猫（cat）',
  'mk.tag.sizeSmall': '小型（small）',
  'mk.tag.sizeMedium': '中型（medium）',
  'mk.tag.sizeLarge': '大型（large）',
  'mk.tag.prefHint': '偏好自由短文（≤16 字）',
  'mk.tag.done': '已打标',
  'mk.tag.invalid': '会员 userId 与标签值必填',

  /* ---- 区 2 券矩阵 ---- */
  'mk.coupon.title': '券矩阵',
  'mk.coupon.aside': '六类模板 · 登记制不接真抵扣',
  'mk.coupon.createCta': '＋ 新建券',
  'mk.coupon.typeRegister': '注册券',
  'mk.coupon.typeRecharge': '充值券',
  'mk.coupon.typeConsume': '消费券',
  'mk.coupon.typeBirthday': '生日券',
  'mk.coupon.typeFestival': '节日券',
  'mk.coupon.typeWakeup': '唤醒券',
  'mk.coupon.colType': '类型',
  'mk.coupon.colTitle': '标题',
  'mk.coupon.colAmount': '面额',
  'mk.coupon.colThreshold': '门槛',
  'mk.coupon.colDays': '有效天数',
  'mk.coupon.colQuota': '配额',
  'mk.coupon.colStatus': '状态',
  'mk.coupon.thresholdNone': '无门槛',
  'mk.coupon.quotaNone': '不限',
  'mk.coupon.statusOn': '在架',
  'mk.coupon.statusOff': '停用',
  'mk.coupon.empty': '暂无券模板——先建一张注册券或充值券',
  'mk.coupon.modalTitle': '新建券模板',
  'mk.coupon.fType': '券类型',
  'mk.coupon.fTitle': '标题',
  'mk.coupon.fAmount': '面额（元）',
  'mk.coupon.fThreshold': '门槛（元，0=无门槛）',
  'mk.coupon.fDays': '有效天数',
  'mk.coupon.fQuota': '总配额（留空=不限）',
  'mk.coupon.done': '券模板已创建',
  'mk.coupon.invalid': '标题必填，面额须为正数，有效天数 1-3650',

  /* ---- 区 3 定向发放 ---- */
  'mk.campaign.title': '定向发放',
  'mk.campaign.aside': '台账留痕 · 同人同券不重复发',
  'mk.campaign.grantCta': '＋ 发放',
  'mk.campaign.colTitle': '标题',
  'mk.campaign.colCoupon': '券',
  'mk.campaign.colTarget': '目标',
  'mk.campaign.colGranted': '已发',
  'mk.campaign.colNote': '备注',
  'mk.campaign.colTime': '时间',
  'mk.campaign.grantedUnit': '{n} 份',
  'mk.campaign.targetAll': '本店全量会员',
  'mk.campaign.empty': '暂无发放记录',
  'mk.campaign.modalTitle': '定向发放',
  'mk.campaign.fCoupon': '选券',
  'mk.campaign.fTitle': '发放标题',
  'mk.campaign.fTargetKind': '目标标签类（留空=全量）',
  'mk.campaign.fTargetValue': '目标标签值',
  'mk.campaign.fNote': '备注（可选）',
  'mk.campaign.done': '已发放：匹配 {m} 人，实发 {g} 份',
  'mk.campaign.invalid': '须选券并填标题；选目标类后须填目标值',
  'mk.campaign.noCoupon': '暂无在架券——请先在券矩阵新建',

  /* ---- 区 4 生日营销 ---- */
  'mk.bday.title': '生日营销',
  'mk.bday.aside': '台账+通知落行 · 不造假发',
  'mk.bday.tierTitle': '生日权益档位（端口 birthday_perk_tier）',
  'mk.bday.tierAmount': '面额',
  'mk.bday.tierThreshold': '门槛',
  'mk.bday.tierDays': '有效天数',
  'mk.bday.tierEmpty': '端口未配置，走缺省档位',
  'mk.bday.upcomingTitle': '近 30 天生日提醒',
  'mk.bday.kindMember': '会员',
  'mk.bday.kindPet': '宠物',
  'mk.bday.upcomingEmpty': '近 30 天无会员/宠物生日',
  'mk.bday.grantsTitle': '生日权益发放台账',
  'mk.bday.grantOwner': '会员生日礼',
  'mk.bday.grantPet': '宠物生日礼',
  'mk.bday.grantsEmpty': '暂无生日权益发放记录',

  /* ---- 区 5 活动配置 ---- */
  'mk.promo.title': '活动配置',
  'mk.promo.aside': '排期状态机留痕 · 不接真结算',
  'mk.promo.createCta': '＋ 新建活动',
  'mk.promo.typeFullMinus': '满减',
  'mk.promo.typeDiscount': '折扣',
  'mk.promo.typeSecondPiece': '第二件',
  'mk.promo.typeExchangeGift': '换购',
  'mk.promo.typeTimePromo': '时段促销',
  'mk.promo.stDraft': '草稿',
  'mk.promo.stScheduled': '待上线',
  'mk.promo.stActive': '进行中',
  'mk.promo.stEnded': '已结束',
  'mk.promo.colName': '名称',
  'mk.promo.colType': '类型',
  'mk.promo.colStatus': '状态',
  'mk.promo.colRange': '排期',
  'mk.promo.colRules': '规则',
  'mk.promo.colOps': '操作',
  'mk.promo.rangeNone': '未排期',
  'mk.promo.editCta': '编辑',
  'mk.promo.empty': '暂无活动配置',
  'mk.promo.modalCreate': '新建活动',
  'mk.promo.modalEdit': '编辑活动',
  'mk.promo.fType': '活动类型',
  'mk.promo.fName': '活动名称',
  'mk.promo.ruleThreshold': '门槛（元）',
  'mk.promo.ruleMinus': '减（元）',
  'mk.promo.ruleRate': '折数（0-1，如 0.85）',
  'mk.promo.ruleGift': '赠品说明',
  'mk.promo.ruleDailyStart': '每日开始（HH:mm）',
  'mk.promo.ruleDailyEnd': '每日结束（HH:mm）',
  'mk.promo.fStartsAt': '排期开始（可选）',
  'mk.promo.fEndsAt': '排期结束（可选）',
  'mk.promo.fStatus': '状态',
  'mk.promo.fStatusDraft': '草稿（不上线）',
  'mk.promo.fStatusScheduled': '排期（按起止上下线）',
  'mk.promo.done': '活动已保存',
  'mk.promo.invalid': '名称必填；规则字段不合法，请检查',

  /* ---- 区 5b 促销互斥公示 ---- */
  'mk.stack.title': '促销互斥 · 叠加规则（逐项开关公示）',
  'mk.stack.couponStack': '券叠加规则',
  'mk.stack.campaignCoupon': '活动 × 券',
  'mk.stack.campaignMember': '活动 × 会员折扣',
  'mk.stack.multiCampaign': '多活动叠加',
  'mk.stack.note': '当前值=端口公示（端口可改：config.save，门店覆盖优先于总部下发）',

  /* ---- MarketingLedgerPage 页级 ---- */
  'mk.ledger.pageTitle': '营销台账',
  'mk.ledger.pageSub': '支出 · 换货 · 退货待检 · 报表快照',
  'mk.ledger.backMarketing': '← 会员营销',

  /* ---- 台账区 1 支出 ---- */
  'mk.exp.title': '支出台账',
  'mk.exp.aside': '手工台账 · 不接发票流',
  'mk.exp.createCta': '＋ 记一笔',
  'mk.exp.typeRent': '房租',
  'mk.exp.typeSalary': '工资',
  'mk.exp.typeUtility': '水电',
  'mk.exp.typeOther': '其他',
  'mk.exp.monthLabel': '月份',
  'mk.exp.monthAll': '全部月份',
  'mk.exp.summaryTotal': '合计',
  'mk.exp.colType': '类型',
  'mk.exp.colAmount': '金额',
  'mk.exp.colMonth': '归属月份',
  'mk.exp.colNote': '备注',
  'mk.exp.colOperator': '记账人',
  'mk.exp.colOps': '操作',
  'mk.exp.deleteCta': '删除',
  'mk.exp.empty': '暂无支出记录',
  'mk.exp.modalTitle': '记一笔支出',
  'mk.exp.fType': '类型',
  'mk.exp.fAmount': '金额（元）',
  'mk.exp.fMonth': '归属月份',
  'mk.exp.fNote': '备注（可选）',
  'mk.exp.done': '支出已记账',
  'mk.exp.deleted': '台账行已删除',
  'mk.exp.invalid': '金额须为正数，月份必选',

  /* ---- 台账区 2 换货 ---- */
  'mk.exch.title': '换货差价补退',
  'mk.exch.aside': '申请→确认→了结 · 留痕不碰真钱',
  'mk.exch.createCta': '＋ 登记换货',
  'mk.exch.stApplied': '已申请',
  'mk.exch.stConfirmed': '已确认',
  'mk.exch.stSettled': '已了结',
  'mk.exch.colOrig': '原商品',
  'mk.exch.colNew': '换新',
  'mk.exch.colDiff': '差价',
  'mk.exch.colStatus': '状态',
  'mk.exch.colNote': '备注',
  'mk.exch.colOperator': '经办',
  'mk.exch.colOps': '操作',
  'mk.exch.confirmCta': '确认',
  'mk.exch.settleCta': '了结',
  'mk.exch.diffPlus': '补收 {v}',
  'mk.exch.diffMinus': '退差 {v}',
  'mk.exch.diffZero': '无差价',
  'mk.exch.empty': '暂无换货记录',
  'mk.exch.modalTitle': '登记换货',
  'mk.exch.fOrig': '原商品名',
  'mk.exch.fNew': '换新商品名',
  'mk.exch.fDiff': '差价（元，正=补收 负=退差）',
  'mk.exch.fNote': '备注（可选）',
  'mk.exch.done': '换货已登记',
  'mk.exch.advanced': '状态已推进',
  'mk.exch.invalid': '原商品名/换新名必填，差价须为数字',

  /* ---- 台账区 3 退货待检 ---- */
  'mk.insp.title': '退货待检',
  'mk.insp.aside': '待检=台账标记层 · 不合格触发报损',
  'mk.insp.createCta': '＋ 登记待检',
  'mk.insp.stPending': '待检',
  'mk.insp.stPassed': '合格',
  'mk.insp.stFailed': '不合格',
  'mk.insp.colProduct': '商品',
  'mk.insp.colQty': '数量',
  'mk.insp.colStatus': '状态',
  'mk.insp.colQcNote': '质检备注',
  'mk.insp.colOperator': '经办',
  'mk.insp.colTime': '时间',
  'mk.insp.colOps': '操作',
  'mk.insp.passCta': '合格',
  'mk.insp.failCta': '不合格',
  'mk.insp.empty': '暂无待检记录',
  'mk.insp.modalTitle': '登记退货待检',
  'mk.insp.fProduct': '商品',
  'mk.insp.fQty': '数量',
  'mk.insp.fNote': '备注（可选）',
  'mk.insp.reviewTitle': '质检结论',
  'mk.insp.fQcNote': '质检备注',
  'mk.insp.done': '待检已登记',
  'mk.insp.reviewed': '质检已落痕',
  'mk.insp.invalid': '须选商品，数量须为正整数',

  /* ---- 台账区 4 报表快照 ---- */
  'mk.snap.title': '报表快照',
  'mk.snap.aside': '月快照永久留存 · 仅店主生成',
  'mk.snap.createCta': '＋ 生成快照',
  'mk.snap.monthAll': '全部月份',
  'mk.snap.kindD1': 'D1 营收月报',
  'mk.snap.kindMember': '会员月报（D3）',
  'mk.snap.colMonth': '月份',
  'mk.snap.colKind': '类型',
  'mk.snap.colCreator': '生成人',
  'mk.snap.colTime': '时间',
  'mk.snap.empty': '暂无快照——店主可生成月快照留档',
  'mk.snap.modalTitle': '生成报表快照',
  'mk.snap.fMonth': '月份',
  'mk.snap.fKind': '快照类型',
  'mk.snap.hint': 'payload 现取对应读口同帧数据（D1=营收月报 / member=会员月报）',
  'mk.snap.done': '快照已生成',
  'mk.snap.working': '正在取数并生成…',
} as const;

export const MARKETING_COPY = withCopyOverrides(MARKETING_COPY_TABLE);

export type MarketingCopyKey = keyof typeof MARKETING_COPY;

/** 文案键取值 + 占位插值（{var}）；插值参数全部来自端口/数据，不经本表硬编码 */
export function mk(key: MarketingCopyKey, vars?: Record<string, string | number>): string {
  const tpl: string = MARKETING_COPY[key];
  if (!vars) return tpl;
  return tpl.replace(/\{(\w+)\}/g, (_, k: string) => (k in vars ? String(vars[k]) : `{${k}}`));
}
