-- 端口批片 B（CJ-1002-01 内容层全端口化）：文案端口 copy_overrides 建表 + 三端 copy 键全表种子
-- （生成件见 scripts/gen-copy-overrides-seed.mts / server/src/db/copySeedRows.ts）。
-- 读取顺序=端口值（active 行）→ 码内默认；高危键重确认+禁令词闸在 config.save（domain='copy'）。
-- 幂等：种子段 rule_key active 行 NOT EXISTS 守卫（重放零副作用）；created_by='system'
-- （迁移执行器 PRAGMA foreign_keys=OFF，惯例见 migrate.ts 头注）。
CREATE TABLE `copy_overrides` (
	`id` text PRIMARY KEY NOT NULL,
	`version` integer NOT NULL,
	`rule_key` text NOT NULL,
	`label` text NOT NULL,
	`value_json` text NOT NULL,
	`effective_from` integer NOT NULL,
	`active` integer DEFAULT true NOT NULL,
	`created_by` text NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX `ix_copy_overrides_key_active` ON `copy_overrides` (`rule_key`,`active`);--> statement-breakpoint
WITH s(rule_key, label, text) AS (VALUES
  ('appeal.addPhoto', 'account', '添加照片'),
  ('appeal.decidePrefix', 'account', '门店备注'),
  ('appeal.emptyBody', 'account', '原手机号还能正常收码时，自助换绑更快'),
  ('appeal.emptyCta', 'account', '去自助换绑 ›'),
  ('appeal.emptyTitle', 'account', '还没有申诉记录'),
  ('appeal.intro', 'account', '原手机号已不可用（停用/丢失）时，提交申诉由门店协助换绑。'),
  ('appeal.linePhones', 'account', '{old} → {new}'),
  ('appeal.listTitle', 'account', '申诉记录'),
  ('appeal.loadFail', 'account', '申诉记录加载失败，请检查网络后重试'),
  ('appeal.newPhoneLabel', 'account', '新手机号'),
  ('appeal.newPhonePlaceholder', 'account', '输入 11 位新手机号'),
  ('appeal.noteLabel', 'account', '情况说明'),
  ('appeal.notePlaceholder', 'account', '简述原号停用原因，方便门店核实（必填）'),
  ('appeal.noteRequired', 'account', '请填写情况说明'),
  ('appeal.oldPhoneLabel', 'account', '原手机号'),
  ('appeal.phoneInvalid', 'account', '请输入 11 位新手机号'),
  ('appeal.photoHint', 'account', '手持证件照或证件照片，最多 3 张'),
  ('appeal.photoLimit', 'account', '最多上传 3 张'),
  ('appeal.photoTitle', 'account', '身份证明材料'),
  ('appeal.pushLabel', 'account', 'APPEAL'),
  ('appeal.removePhoto', 'account', '移除'),
  ('appeal.statusApproved', 'account', '已通过'),
  ('appeal.statusRejected', 'account', '已驳回'),
  ('appeal.statusSubmitted', 'account', '审核中'),
  ('appeal.submit', 'account', '提交申诉'),
  ('appeal.submitFail', 'account', '提交失败，请稍后再试'),
  ('appeal.submitting', 'account', '提交中…'),
  ('appeal.successBody', 'account', '门店核实材料后处理，结果与备注可在下方申诉记录查看。'),
  ('appeal.successTitle', 'account', '申诉已提交'),
  ('appeal.title', 'account', '换绑申诉'),
  ('appeal.uploadFail', 'account', '图片上传失败，请重试'),
  ('appeal.uploading', 'account', '上传中…'),
  ('appeal.whyPhoto', 'account', '为什么要身份证明：申诉通道不需要原号验证码，门店必须凭身份证明材料确认操作人是账号本人，防止账号被冒名改绑。'),
  ('bind.backSettings', 'account', '返回设置'),
  ('bind.codeInvalid', 'account', '请输入 6 位数字验证码'),
  ('bind.codePlaceholder', 'account', '输入 6 位验证码'),
  ('bind.currentPhone', 'account', '当前绑定手机号'),
  ('bind.devEcho', 'account', '内测模拟码：{code}'),
  ('bind.devEchoNote', 'account', '内测期为模拟通道，验证码直接显示在这里；正式短信通道接入后此区域消失。'),
  ('bind.needOldCode', 'account', '请先获取并输入原手机号验证码'),
  ('bind.newPhoneLabel', 'account', '新手机号'),
  ('bind.newPhonePlaceholder', 'account', '输入 11 位新手机号'),
  ('bind.noPhoneBody', 'account', '无法自助换绑，请走换绑申诉通道由门店协助处理'),
  ('bind.noPhoneCta', 'account', '去换绑申诉 ›'),
  ('bind.noPhoneTitle', 'account', '当前账号未绑定手机号'),
  ('bind.phoneInvalid', 'account', '请输入 11 位手机号'),
  ('bind.pushLabel', 'account', 'CHANGE PHONE'),
  ('bind.resendIn', 'account', '{sec}s 后重发'),
  ('bind.sendCode', 'account', '获取验证码'),
  ('bind.sendFail', 'account', '发送失败，请稍后再试'),
  ('bind.sending', 'account', '发送中…'),
  ('bind.sentOk', 'account', '验证码已发送'),
  ('bind.step1Title', 'account', '① 验证原手机号'),
  ('bind.step2Title', 'account', '② 绑定新手机号'),
  ('bind.submit', 'account', '确认换绑'),
  ('bind.submitFail', 'account', '换绑失败，请稍后再试'),
  ('bind.submitting', 'account', '换绑中…'),
  ('bind.successBody', 'account', '订单、会员、回馈金、宠物档案等全部数据已保留，新手机号即刻生效。'),
  ('bind.successTitle', 'account', '换绑成功'),
  ('bind.title', 'account', '手机号换绑'),
  ('bind.whyCode', 'account', '为什么要验证码：手机号是登录与找回账号的唯一凭证，换绑前须确认原号和新号都在你手上，防止账号被他人改绑盗用。'),
  ('deact.approvedNote', 'account', '账号已注销，正在前往登录页…'),
  ('deact.blockBody', 'account', '以下事项尚未完结，处理完成后即可申请注销：'),
  ('deact.blockGo', 'account', '去完成 ›'),
  ('deact.blockNote', 'account', '预约、订单与退款完结前，账号不能注销。'),
  ('deact.blockTitle', 'account', '暂时无法注销'),
  ('deact.cancel', 'account', '撤回注销申请'),
  ('deact.cancelFail', 'account', '撤回失败，请稍后再试'),
  ('deact.cancelOk', 'account', '注销申请已撤回'),
  ('deact.cancelPending', 'account', '正在撤回…'),
  ('deact.confirmBody', 'account', '注销后回馈金清零、会员档终止、宠物档案删除。此操作不可撤销，复核通过即生效。'),
  ('deact.confirmCancel', 'account', '再想想'),
  ('deact.confirmOk', 'account', '我已知晓，确认注销'),
  ('deact.confirmTitle', 'account', '再次确认注销账号？'),
  ('deact.ctaSubmit', 'account', '确认注销账号'),
  ('deact.impactMember', 'account', '会员档终止'),
  ('deact.impactMemberDesc', 'account', '会员身份与全部权益即刻终止，不退折算费用'),
  ('deact.impactPets', 'account', '宠物档案删除'),
  ('deact.impactPetsDesc', 'account', '宠物档案将被删除，门店历史服务记录保留'),
  ('deact.impactRebate', 'account', '回馈金清零'),
  ('deact.impactRebateDesc', 'account', '账户内回馈金余额全部清零，不可恢复'),
  ('deact.impactTitle', 'account', '注销后，这些将立即变化'),
  ('deact.inflightBody', 'account', '门店正在复核你的注销申请，期间账号可正常使用。'),
  ('deact.inflightTitle', 'account', '注销申请审核中'),
  ('deact.keepNote', 'account', '订单与服务留痕将依法保留，注销 ≠ 删除数据。'),
  ('deact.loadFail', 'account', '注销状态加载失败，请检查网络后重试'),
  ('deact.pushLabel', 'account', 'DEACTIVATE'),
  ('deact.rejectedPrefix', 'account', '驳回原因'),
  ('deact.rejectedTitle', 'account', '注销申请被驳回'),
  ('deact.reviewNote', 'account', '提交后由门店复核，复核通过账号注销生效。'),
  ('deact.submitFail', 'account', '提交失败，请稍后再试'),
  ('deact.submittedAt', 'account', '提交于 {time}'),
  ('deact.submitting', 'account', '提交中…'),
  ('deact.successBody', 'account', '门店复核期间账号可正常使用；复核通过后账号注销，期间可随时撤回。'),
  ('deact.successTitle', 'account', '注销申请已提交'),
  ('deact.title', 'account', '注销账号'),
  ('deact.whyReview', 'account', '为什么要门店复核：注销会清零回馈金、终止会员并删除宠物档案，且不可撤销。门店复核是为确认这是本人真实意愿，避免账号被盗后被恶意注销。'),
  ('device.channelAssisted', 'account', '门店协助'),
  ('device.channelSelf', 'account', '自助换绑'),
  ('device.current', 'account', '当前设备'),
  ('device.emptyBody', 'account', '手机号每次换绑都会在这里留痕，方便核对账号变动'),
  ('device.emptyCta', 'account', '返回设置'),
  ('device.emptyTitle', 'account', '还没有换绑记录'),
  ('device.firstSeen', 'account', '首次登录 {time}'),
  ('device.lastSeen', 'account', '最近活跃 {time}'),
  ('device.listTitle', 'account', '登录设备'),
  ('device.loadFail', 'account', '设备信息加载失败，请检查网络后重试'),
  ('device.logLine', 'account', '{old} → {new}'),
  ('device.logsTitle', 'account', '换绑记录'),
  ('device.pushLabel', 'account', 'DEVICES'),
  ('device.title', 'account', '登录设备管理'),
  ('device.unnamed', 'account', '未命名设备'),
  ('privacy.footnote', 'account', '拒绝授权不影响基本功能使用（《个人信息保护法》最小必要口径）。'),
  ('privacy.locationDesc', 'account', '用于展示附近门店距离'),
  ('privacy.locationNote', 'account', '当前版本无定位功能消费点：门店距离展示走门店地址，不取您的定位。'),
  ('privacy.locationOffHint', 'account', '关闭不影响预约与下单'),
  ('privacy.locationTitle', 'account', '定位'),
  ('privacy.notifyDesc', 'account', '预约进度、退款结果等实时提醒'),
  ('privacy.notifyOffHint', 'account', '关闭后，预约进度与退款结果请在订单页查看'),
  ('privacy.notifyTitle', 'account', '消息通知'),
  ('privacy.notifyUnread', 'account', '当前有未读通知'),
  ('privacy.pushLabel', 'account', 'PRIVACY'),
  ('privacy.title', 'account', '权限与隐私'),
  ('privacy.toggleFail', 'account', '设置失败，请重试'),
  ('settings.appeal', 'account', '换绑申诉'),
  ('settings.appealSub', 'account', '原号已不可用？门店协助换绑'),
  ('settings.deactivate', 'account', '注销账号'),
  ('settings.deactivateSub', 'account', '门店复核后生效，不可撤销'),
  ('settings.devices', 'account', '登录设备管理'),
  ('settings.groupAccount', 'account', '账号安全'),
  ('settings.groupDanger', 'account', '危险操作'),
  ('settings.groupGeneral', 'account', '设备与隐私'),
  ('settings.loadFail', 'account', '账号信息加载失败，请检查网络后重试'),
  ('settings.logout', 'account', '退出登录'),
  ('settings.logoutFail', 'account', '退出失败，请稍后再试'),
  ('settings.logoutSub', 'account', '退出后需重新登录'),
  ('settings.phoneBind', 'account', '手机号换绑'),
  ('settings.privacy', 'account', '权限与隐私'),
  ('settings.pushLabel', 'account', 'SETTINGS'),
  ('settings.title', 'account', '设置'),
  ('appointments.albumSub', 'appointments', '共 {count} 张照片，服务全程透明可查'),
  ('appointments.albumTitle', 'appointments', '服务相册'),
  ('appointments.backToList', 'appointments', '返回我的预约'),
  ('appointments.cancelAskFree', 'appointments', '确认取消这次预约吗？'),
  ('appointments.cancelAskLate', 'appointments', '距开始不足 4 小时，取消需商家审核'),
  ('appointments.cancelCtaFree', 'appointments', '取消预约'),
  ('appointments.cancelCtaLate', 'appointments', '申请取消（4 小时内需商家审核）'),
  ('appointments.cancelReasonTitle', 'appointments', '取消原因（选填，告诉我们为什么）'),
  ('appointments.cancelReviewing', 'appointments', '取消申请审核中，门店处理后会通知你；审核通过前预约仍然有效。'),
  ('appointments.cancelRuleFree', 'appointments', '开始前 4 小时以上可免费取消，槽位将立即释放。'),
  ('appointments.cancelRuleLate', 'appointments', '提交后预约转为「取消审核中」，门店审核通过才会取消并释放槽位。'),
  ('appointments.cancelSubmitFree', 'appointments', '确认取消'),
  ('appointments.cancelSubmitLate', 'appointments', '提交取消申请'),
  ('appointments.codeTitle', 'appointments', '到店核销码'),
  ('appointments.detailLoadFail', 'appointments', '预约详情加载失败，请检查网络后重试'),
  ('appointments.detailTitle', 'appointments', '预约详情'),
  ('appointments.emptyBody', 'appointments', '给毛孩子安排一次舒服的洗护吧'),
  ('appointments.emptyCta', 'appointments', '立即预约'),
  ('appointments.emptyTitle', 'appointments', '还没有预约'),
  ('appointments.liveBoarding', 'appointments', '寄养进行中'),
  ('appointments.liveGrooming', 'appointments', '服务进行中'),
  ('appointments.liveSub', 'appointments', '点击查看实时进度与照片'),
  ('appointments.loadFail', 'appointments', '预约列表加载失败，请检查网络后重试'),
  ('appointments.notFound', 'appointments', '预约不存在或无权查看'),
  ('appointments.rebook', 'appointments', '再次预约'),
  ('appointments.rejectedPrefix', 'appointments', '商家已婉拒'),
  ('appointments.rescheduleCta', 'appointments', '改期'),
  ('appointments.rescheduleNote', 'appointments', '{service} · {pet}（改期后需商家重新确认）'),
  ('appointments.rescheduleSubmit', 'appointments', '确认改期'),
  ('appointments.rescheduleTitleBoarding', 'appointments', '重选入住 / 退房日期'),
  ('appointments.rescheduleTitleGrooming', 'appointments', '选择新时间'),
  ('appointments.servingCall', 'appointments', '拨打门店电话'),
  ('appointments.servingNote', 'appointments', '可到店或经商家端与门店协商处理'),
  ('appointments.servingTitle', 'appointments', '服务中，如需取消请联系门店'),
  ('appointments.slotsLoadFail', 'appointments', '可约时段加载失败，请关闭后重试'),
  ('appointments.slotsLoading', 'appointments', '正在加载可约时段…'),
  ('appointments.tabEmpty', 'appointments', '暂无{status}的预约'),
  ('appointments.thinkMore', 'appointments', '再想想'),
  ('appointments.title', 'appointments', '我的预约'),
  ('booking.addCalendar', 'booking', '添加到日历'),
  ('booking.backHome', 'booking', '返回首页'),
  ('booking.boardingTitle', 'booking', '预约寄养'),
  ('booking.cancelNote', 'booking', '{week}见 · 如需取消请提前 4 小时'),
  ('booking.chooseCheckin', 'booking', '请选择入住日期'),
  ('booking.chooseCheckout', 'booking', '请选择退房日期'),
  ('booking.choosePet', 'booking', '请选择宠物'),
  ('booking.chooseRoom', 'booking', '请选择房型'),
  ('booking.chooseService', 'booking', '请选择服务'),
  ('booking.chooseStore', 'booking', '请选择门店'),
  ('booking.chooseTime', 'booking', '请选择时间'),
  ('booking.codeTitle', 'booking', '到店核销码'),
  ('booking.groomingTitle', 'booking', '预约洗护'),
  ('booking.missingParam', 'booking', '缺少预约参数'),
  ('booking.needPet', 'booking', '请先建立宠物档案'),
  ('booking.noGroomingSingle', 'booking', '该门店暂无可约洗护服务，换家门店看看'),
  ('booking.noGroomingWizard', 'booking', '该门店暂无可约洗护服务，去下一步换家门店看看'),
  ('booking.noPetBodyBoarding', 'booking', '预约寄养前需要先为毛孩子建立档案'),
  ('booking.noPetBodyPicker', 'booking', '先为毛孩子建一份档案，再来预约吧'),
  ('booking.noPetBodyWizard', 'booking', '预约前需要先为毛孩子建立档案'),
  ('booking.noPetCta', 'booking', '先建立宠物档案'),
  ('booking.noPetCtaPicker', 'booking', '去建宠物档案'),
  ('booking.noPetSkip', 'booking', '随便看看'),
  ('booking.noPetTitle', 'booking', '还没有宠物档案'),
  ('booking.noRoom', 'booking', '该门店暂无寄养房型'),
  ('booking.passHint', 'booking', '剩余 {remain} 次 · 预约确认后扣 1 次'),
  ('booking.passNone', 'booking', '暂无可用次卡'),
  ('booking.petPickHintBoarding', 'booking', '点按选择要寄养的毛孩子'),
  ('booking.petPickHintGrooming', 'booking', '点按选择要洗护的毛孩子'),
  ('booking.rescheduleLink', 'booking', '需要改期？前往预约详情改期 ›'),
  ('booking.roomEmpty', 'booking', '该门店暂无寄养房型，换一家看看'),
  ('booking.roomLoadFail', 'booking', '房型加载失败，请检查网络'),
  ('booking.staffAny', 'booking', '随缘派单'),
  ('booking.staffAnyCard', 'booking', '随缘'),
  ('booking.staffAnySub', 'booking', '门店安排'),
  ('booking.staffEarliest', 'booking', '最早可约 {time}'),
  ('booking.staffNote', 'booking', '指定洗护师会写在预约备注里传达给门店'),
  ('booking.storeLinePost', 'booking', '（可在下一步更换）'),
  ('booking.storeLinePre', 'booking', '寄养门店：'),
  ('booking.successSub', 'booking', '已自动确认，请按时到店并出示预约码'),
  ('booking.successTitle', 'booking', '预约成功'),
  ('booking.summaryLoadFail', 'booking', '预约摘要加载失败'),
  ('booking.toBoarding', 'booking', '寄养 ›'),
  ('booking.toGrooming', 'booking', '洗护 ›'),
  ('booking.vaccineBlockedNone', 'booking', '档案中还没有疫苗有效期记录'),
  ('booking.vaccineBlockedSuffix', 'booking', '，寄养需疫苗在有效期内'),
  ('booking.vaccineBlockedUntil', 'booking', '疫苗有效期至 {date}，已不满足寄养要求'),
  ('booking.vaccineFix', 'booking', '去补录'),
  ('booking.vaccineRule', 'booking', '寄养要求疫苗有效期覆盖至退房日（{date}）'),
  ('booking.viewAppointments', 'booking', '查看我的预约'),
  ('devlogin.devOnly', 'devlogin', '仅开发环境 · 生产环境请移除'),
  ('devlogin.footerA', 'devlogin', '登录即同意《用户协议》与《隐私政策》'),
  ('devlogin.footerB', 'devlogin', '内测期间口令由门店发放'),
  ('devlogin.gateBody', 'devlogin', '请输入内测口令后加载可登录账号；无口令或口令错误将无法登录。'),
  ('devlogin.gateHint', 'devlogin', '口令通过后在上方选择账号一键登录。'),
  ('devlogin.gateLink', 'devlogin', '口令入内测 ›'),
  ('devlogin.gateTitle', 'devlogin', '内测环境需要口令'),
  ('devlogin.manualBody', 'devlogin', '重跑 server 的 db:seed 后用户 ID 会变化，可在 server 库中查 users 表后粘贴到这里。'),
  ('devlogin.manualTitle', 'devlogin', '手动输入 userId'),
  ('devlogin.phoneBody', 'devlogin', '输入手机号即登录；首次使用将自动注册（新客建档）。'),
  ('devlogin.phoneTitle', 'devlogin', '手机号登录 / 注册'),
  ('devlogin.primaryCta', 'devlogin', '手机号一键登录'),
  ('devlogin.seedEmpty', 'devlogin', '未拉到种子用户，请重跑 server 的 db:seed，或手动输入 userId'),
  ('devlogin.seedFail', 'devlogin', '种子用户拉取失败（网络连接失败：{error}）——请检查网络或确认 server 已启动；若是口令问题请用上方口令门'),
  ('devlogin.seedNote', 'devlogin', '提示：种子用户一键登录 + 口令门内手机号自助开户（D-16：新号自动注册 customer）； 会话 cookie 有效期 7 天。'),
  ('devlogin.seedTitle', 'devlogin', '选择种子用户登录'),
  ('devlogin.tagline', 'devlogin', 'PHILIA · 洗护 / 美容 / 寄养'),
  ('home.casesMore', 'home', '每日更新 ›'),
  ('home.casesTitle', 'home', '店里今天的故事'),
  ('home.caseTitle', 'home', '{pet}的{service}日记'),
  ('home.entryBoarding', 'home', '预约寄养'),
  ('home.entryBoardingNote', 'home', '按晚 · 疫苗核验'),
  ('home.entryGrooming', 'home', '预约洗澡美容'),
  ('home.idFallback', 'home', '菲丽亚宠友'),
  ('home.idJoin', 'home', '免费领个身份 ›'),
  ('home.liveEta', 'home', '预计 {time} 完成'),
  ('home.liveTag', 'home', 'LIVE · 洗护进行中'),
  ('home.liveViewAll', 'home', '查看全程 ›'),
  ('home.memberCode', 'home', '会员码 ›'),
  ('home.openMemberClaim', 'home', '开通会员，买商品返回馈金'),
  ('home.openMemberSub', 'home', '付费档返 {pcts}%，次月到账'),
  ('home.panelEntrySub', 'home', '选择门店、服务和时间'),
  ('home.panelEntryTitle', 'home', '预约洗护'),
  ('home.passStripPost', 'home', ' 次 · 到店出示会员码'),
  ('home.passStripPre', 'home', '次卡共剩 '),
  ('home.petsEmpty', 'home', '还没有毛孩子档案，去添加 TA 吧'),
  ('home.petsLoadFail', 'home', '毛孩子加载失败'),
  ('home.petsTitle', 'home', '我的毛孩子'),
  ('home.preprowDone', 'home', '已完成'),
  ('home.preprowDoneAt', 'home', '{time} 已完成'),
  ('home.preprowTitle', 'home', '消毒备台 · 一客一消'),
  ('home.rebateBalanceLine', 'home', '余额 {amt} · 每月 {day} 日到账'),
  ('home.rebateLabel', 'home', '回馈金'),
  ('home.rebateLedger', 'home', '回馈金账本'),
  ('home.ringArrive', 'home', '{month} 月 {day} 日到账'),
  ('home.ringPeriod', 'home', '本期已攒回馈金 · 周期 {start} – {end}'),
  ('home.ringRule', 'home', '买商品的 {pct}%，次月回到这里。'),
  ('home.statsDays', 'home', '陪伴天数'),
  ('home.statsServices', 'home', '服务次数'),
  ('home.statsSpend', 'home', '累计消费'),
  ('mall.backHome', 'mall', '返回首页'),
  ('mall.cancelConfirmBody', 'mall', '取消后库存将释放，订单不可恢复。'),
  ('mall.cancelConfirmTitle', 'mall', '取消该订单？'),
  ('mall.cartCheckout', 'mall', '去结算'),
  ('mall.cartEmptyBody', 'mall', 'philia 帮你看着货架，
门店同款好物都在商城里'),
  ('mall.cartEmptyCta', 'mall', '去逛逛 ›'),
  ('mall.cartEmptyTitle', 'mall', '购物袋还空着呢'),
  ('mall.cartStoreNote', 'mall', '当前为「{store}」的商品 · 一次下单仅支持同一门店'),
  ('mall.cartTitle', 'mall', '购物袋'),
  ('mall.checkoutEmptyBody', 'mall', '去商城挑点好物，或回购物袋勾选商品'),
  ('mall.checkoutEmptyTitle', 'mall', '没有待结算的商品'),
  ('mall.checkoutGoCart', 'mall', '回购物袋'),
  ('mall.checkoutGoMall', 'mall', '去逛逛'),
  ('mall.checkoutTitle', 'mall', '确认订单'),
  ('mall.confirmReceive', 'mall', '确认收货'),
  ('mall.conflictBody', 'mall', '购物车内已有「{store}」的商品，加入本商品将清空原购物车。'),
  ('mall.conflictOk', 'mall', '清空并加入'),
  ('mall.conflictTitle', 'mall', '购物车仅限同一门店商品'),
  ('mall.deliverySub', 'mall', '配送时效 · 即将点亮'),
  ('mall.deliveryTitle', 'mall', '配送至 · ——'),
  ('mall.emptyBodyCategory', 'mall', '这个分类暂时没有商品，看看别的吧'),
  ('mall.emptyBodyKeyword', 'mall', '换个关键词试试，或看看其他分类'),
  ('mall.emptyClearSearch', 'mall', '清空搜索'),
  ('mall.emptyTitle', 'mall', '没有找到相关商品'),
  ('mall.endLine', 'mall', '共 {total} 件商品 · 到底啦'),
  ('mall.goPay', 'mall', '去支付'),
  ('mall.headSub', 'mall', 'MALL · 给它买点好的'),
  ('mall.headTitle', 'mall', '商城'),
  ('mall.keepShopping', 'mall', '再逛逛商城 ›'),
  ('mall.listShip', 'mall', '{store} · 门店发货'),
  ('mall.loadFail', 'mall', '商品加载失败，请稍后重试'),
  ('mall.orderPreparing', 'mall', '门店正在备货，请耐心等待'),
  ('mall.orderReceived', 'mall', '已于 {time} 确认收货'),
  ('mall.orders.emptyBody', 'mall', '下单的商品和进度都会在这里'),
  ('mall.orders.emptyCta', 'mall', '去看看服务 ›'),
  ('mall.orders.emptyTitle', 'mall', '还没有订单'),
  ('mall.ordersLoadFail', 'mall', '订单加载失败，请稍后重试'),
  ('mall.ordersTabEmpty', 'mall', '暂无{tab}的订单'),
  ('mall.ordersTitle', 'mall', '商品订单'),
  ('mall.orderSumLine', 'mall', '共 {qty} 件，合计'),
  ('mall.paySuccessSub', 'mall', '门店会尽快为你发货，进度可在订单列表查看'),
  ('mall.paySuccessTitle', 'mall', '支付成功'),
  ('mall.pdpAddCart', 'mall', '加入购物袋'),
  ('mall.pdpBackMall', 'mall', '返回商城'),
  ('mall.pdpBuyNow', 'mall', '立即购买'),
  ('mall.pdpDetailTitle', 'mall', '商品详情'),
  ('mall.pdpStockLeft', 'mall', '仅剩 {n} 件'),
  ('mall.pdpStoreLine', 'mall', '{store} · 门店同价 · 正品保障'),
  ('mall.priceNote', 'mall', '金额以提交时门店现价为准'),
  ('mall.pullMore', 'mall', '上拉加载更多'),
  ('mall.rebateLine', 'mall', '返 {amt} 回馈金'),
  ('mall.receiveConfirmBody', 'mall', '确认后订单将转为已完成，请确保商品已完好送达。'),
  ('mall.receiveConfirmTitle', 'mall', '确认已收到商品？'),
  ('mall.reorder', 'mall', '再来一单'),
  ('mall.searchPlaceholder', 'mall', '搜索主粮、零食、玩具…'),
  ('mall.soldOut', 'mall', '已售罄'),
  ('mall.submitOrder', 'mall', '提交订单'),
  ('mall.viewOrders', 'mall', '查看订单'),
  ('a3.ctaOtherTier', 'member', '看看别的档 →'),
  ('a3.ctaRenew', 'member', '续费{tier} · 每天 ¥{daily}'),
  ('a3.ctaRenewFree', 'member', '免费在册 · 随时升级'),
  ('a3.frozenTip', 'member', '回馈金余额保留但暂不可用，续费请到店收银台办理。'),
  ('a3.headNo', 'member', 'PHILIA CLUB'),
  ('a3.headTitle', 'member', '会员'),
  ('a3.ledgerBalance', 'member', '回馈金余额'),
  ('a3.ledgerPending', 'member', '本期预计'),
  ('a3.ledgerSettleDay', 'member', '到账日'),
  ('a3.ledgerSettleDayValue', 'member', '每月 {day} 日'),
  ('a3.perksAllOn', 'member', '8 项全部生效'),
  ('a3.perksTitle', 'member', '{tier}权益'),
  ('a3.pushLabel', 'member', 'MEMBER'),
  ('a3.quitLink', 'member', '退会说明 ›'),
  ('a3.quitSheetBody', 'member', '退会请联系门店办理。年费按剩余整月 × 月均价折算退回（内测期线下原路退回），回馈金余额清零、档位终止，全程留痕。'),
  ('a3.quitSheetTitle', 'member', '退会说明'),
  ('a3.remindExpire', 'member', '{days} 天后到期 · 续费即解冻'),
  ('a3.renewSheetBody', 'member', '内测期续费请到店收银台办理（现金/微信/支付宝）。到期不自动续费；续费后有效期顺延 {days} 天，冻结的回馈金同步解冻。'),
  ('a3.renewSheetTitle', 'member', '续费 · 到店办理'),
  ('a3.sheetGotIt', 'member', '知道了'),
  ('a3.stampFrozen', 'member', '已冻结 · 续费即解冻'),
  ('bk.multiPetSlot', 'member', '多宠同订 · 即将点亮'),
  ('bk.slotFull', 'member', '已满'),
  ('bk.slotOpen', 'member', '可约'),
  ('card.claimNuanyang', 'member', '含 3 只毛孩子 · 都被叫得出名字'),
  ('card.claimWeiguang', 'member', '先领个身份，慢慢认识我们'),
  ('card.claimYinghuo', 'member', '一年，省下一顿火锅'),
  ('card.claimZhuguang', 'member', '每月一次眼耳甲，不用记'),
  ('card.freePrice', 'member', '免费注册'),
  ('card.logo', 'member', 'PHILIA · LOVE BOND LIFE'),
  ('card.priceYear', 'member', '¥{price} / 年'),
  ('chg.actionFail', 'member', '预约操作失败，请稍后再试'),
  ('chg.cancelCta', 'member', '取消预约'),
  ('chg.cancelling', 'member', '取消中…'),
  ('chg.entryCta', 'member', '预约下期档位 ›'),
  ('chg.execNote', 'member', '到期日到店续费时按预约档全价收款；取消或改约不影响当前权益。'),
  ('chg.expireLabel', 'member', '到期日'),
  ('chg.freeCta', 'member', '去升级页 ›'),
  ('chg.freeNote', 'member', '免费档永久有效，无到期换档；升档即时生效请走升级页。'),
  ('chg.headNo', 'member', 'PLAN CHANGE'),
  ('chg.headTitle', 'member', '到期换档'),
  ('chg.nonMemberCta', 'member', '去开通会员 ›'),
  ('chg.nonMemberTitle', 'member', '开通会员后可预约下期档位'),
  ('chg.priceFree', 'member', '免费'),
  ('chg.priceYear', 'member', '¥{price} / 年'),
  ('chg.pushLabel', 'member', '预约下期档位 · SCHEDULE'),
  ('chg.scheduledAtLabel', 'member', '预约时刻'),
  ('chg.scheduledEntry', 'member', '已预约下期：{plan} ›'),
  ('chg.scheduledLine', 'member', '已预约 {plan} · 到期按新档续费（到店办理）'),
  ('chg.scheduledTitle', 'member', '预约单'),
  ('chg.submitCta', 'member', '预约{tier}'),
  ('chg.submitting', 'member', '提交中…'),
  ('chg.targetTitle', 'member', '选择下期档位'),
  ('chg.toastCancel', 'member', '已取消预约'),
  ('chg.toastOk', 'member', '已预约下期档位'),
  ('chg.windowClosed', 'member', '到期前 {days} 天开放预约，请到期日临近时再来。'),
  ('chg.windowOpen', 'member', '到期前 {days} 天开放预约，窗口内可改约下期档位（含低档，期内不降级不变）。'),
  ('common.memberLoadFail', 'member', '会员信息加载失败'),
  ('common.plansLoadFail', 'member', '档位信息加载失败'),
  ('common.rebateLoadFail', 'member', '回馈金账本加载失败'),
  ('f1.birthdayDesc', 'member', '它的生日周，自动为你生成一本年度特辑'),
  ('f1.birthdayTitle', 'member', '生日特辑'),
  ('f1.eyebrow', 'member', 'PHILIA · 小棉花在替你陪着它')
)
INSERT INTO `copy_overrides` (`id`,`version`,`rule_key`,`label`,`value_json`,`effective_from`,`active`,`created_by`,`created_at`,`updated_at`)
SELECT 'seedcopy_' || lower(hex(randomblob(8))), 1, s.rule_key, s.label, json_object('text', s.text), unixepoch(), 1, 'system', unixepoch(), unixepoch()
FROM s
WHERE NOT EXISTS (SELECT 1 FROM `copy_overrides` WHERE `rule_key` = s.rule_key AND `active` = 1);
--> statement-breakpoint
WITH s(rule_key, label, text) AS (VALUES
  ('f1.growthSlotDesc', 'member', '陪伴段位（初识 → 家人）与它的徽章墙，随养成体系一同点亮'),
  ('f1.growthTitle', 'member', '陪伴段位与徽章'),
  ('f1.manifesto', 'member', '它不在你身边的时候，
我们看着它。'),
  ('f1.statDays', 'member', '陪伴天数'),
  ('f1.statPhotos', 'member', '照片数'),
  ('f1.statServices', 'member', '服务次数'),
  ('j1.alreadyMember', 'member', '你已是会员（有效期至 {date}）。续费或升级请到店收银台办理。'),
  ('j1.alreadyMemberFree', 'member', '你已是会员（免费档永久有效）。升级付费档享回馈金与服务折扣，到店收银台即可办理。'),
  ('j1.backMember', 'member', '回会员中心 ›'),
  ('j1.compareFooter', 'member', '四档共通：七节点全程可视 · 美容报告 30 分钟 · 安心包全员免费
年费 ≠ 储值 · 到期不自动续费 · 权益只加不减'),
  ('j1.compareLink', 'member', '对比四档权益 ›'),
  ('j1.compareNote', 'member', '档色即身份'),
  ('j1.compareTitle', 'member', '四档权益对比'),
  ('j1.ctaAlreadyMember', 'member', '已是会员 · 去会员中心 ›'),
  ('j1.ctaOpen', 'member', '开通{tier} · 每天 ¥{daily}'),
  ('j1.ctaOpenFree', 'member', '免费注册 · 领个身份'),
  ('j1.ctaSub', 'member', '到期不自动续费 · 随时退卡'),
  ('j1.doneGotoPets', 'member', '看看它的档案 ›'),
  ('j1.estimateNote', 'member', '按门店年均消费测算，轻松省回年费'),
  ('j1.freeOpenedBody', 'member', '免费档即时生效{date}。升级萤火/烛光/暖阳可享商品回馈金与服务折扣，到店收银台即可办理。'),
  ('j1.freeOpenedTitle', 'member', '微光会员已开通'),
  ('j1.guideNote', 'member', '点卡或滑卡选档——卡本身就是选择器：'),
  ('j1.ledgerDaily', 'member', '每天'),
  ('j1.ledgerPets', 'member', '多宠覆盖'),
  ('j1.ledgerYearly', 'member', '一年'),
  ('j1.perksFollow', 'member', '8 项 · 跟随选中档'),
  ('j1.petsIncluded', 'member', '含 {n} 只'),
  ('j1.pushLabel', 'member', '开通会员 · JOIN'),
  ('j1.storeBypass', 'member', '想到店办理？收银台指引 ›'),
  ('j1.storePayBack', 'member', '重新选档'),
  ('j1.storePayBody', 'member', '你已选定「{tier}会员（{price}）」。内测期请到店收银台付款开通（现金/微信/支付宝），成交即开通、有效期 {days} 天。'),
  ('j1.storePayNote', 'member', '内测期仅支持到店收银台开通；线上支付通道开通后将在本页直接开放。'),
  ('j1.storePayOk', 'member', '我知道了'),
  ('j1.storePayStep1', 'member', '到店后告知收银员开通「{tier}会员」，报手机号即可。'),
  ('j1.storePayStep2', 'member', '收银台付款（支持现金/微信/支付宝），多宠家庭第 {n} 只起按 +¥{fen}/年/只 计入。'),
  ('j1.storePayStep3', 'member', '付款成交即开通，有效期 {days} 天；会员中心即时显示你的档位。'),
  ('j1.storePayTitle', 'member', '请到店完成开通'),
  ('j1.tierRowPaid', 'member', '回馈金 {pct}% · 服务 {zhe} 折 · {pets}'),
  ('j1.upgradeEntry', 'member', '升级更高档 ›'),
  ('l1.manifestoA', 'member', '守护每一次'),
  ('l1.manifestoB', 'member', '被'),
  ('l1.manifestoC', 'member', '的时刻。'),
  ('l1.manifestoEm', 'member', '照顾'),
  ('l1.wechatSlot', 'member', '微信一键登录'),
  ('live.stepActive', 'member', '进行中'),
  ('live.stepPending', 'member', '未开始'),
  ('mall.rebateEarnCard', 'member', '购买返 {amt} 回馈金 · 次月 {day} 日到账'),
  ('mall.rebateEarnCardNoDay', 'member', '购买返 {amt} 回馈金'),
  ('mall.rebateEarnCta', 'member', '本单返 {amt} 回馈金'),
  ('mall.rebateHook', 'member', '付费档返 {pcts}% · 仅抵商品 ›'),
  ('o1.refundTab', 'member', '退款售后'),
  ('p1.certSlotTitle', 'member', '安心证书'),
  ('perk.archive', 'member', '年度档案'),
  ('perk.archiveSub', 'member', '全年在册'),
  ('perk.birthday', 'member', '生日礼遇'),
  ('perk.birthdaySub', 'member', '年度特辑'),
  ('perk.boarding', 'member', '寄养折扣'),
  ('perk.boardingSub', 'member', '{zhe} 折'),
  ('perk.discount', 'member', '服务折扣'),
  ('perk.discountNone', 'member', '门市价'),
  ('perk.discountSub', 'member', '{zhe} 折'),
  ('perk.groomer', 'member', '专属洗护师'),
  ('perk.groomerSub', 'member', '点名安排'),
  ('perk.pets', 'member', '多宠覆盖'),
  ('perk.petsSub', 'member', '含 {n} 只'),
  ('perk.rebate', 'member', '回馈金'),
  ('perk.rebateNone', 'member', '—'),
  ('perk.rebateSub', 'member', '{pct}%'),
  ('perk.skin', 'member', '皮毛检测'),
  ('perk.skinSub', 'member', '每季一次'),
  ('q1.codeFooter', 'member', '码面白底墨码，识别率优先 · 码每 5 分钟自动刷新'),
  ('q1.hint', 'member', '到店出示 · 店员扫码'),
  ('q1.nonMemberClaim', 'member', '先领个身份，慢慢认识我们'),
  ('q1.nonMemberCta', 'member', '开通会员 ›'),
  ('q1.nonMemberGuide', 'member', '还不是会员：微光档免费，一键开通即会员；付费档到店收银台办理。'),
  ('q1.nonMemberPrice', 'member', '未开通'),
  ('q1.passEmpty', 'member', '暂无次卡。次卡余额为实时数据。'),
  ('q1.passRemain', 'member', '剩余 {remain} 次 / 共 {total} 次'),
  ('q1.passStoreFallback', 'member', '菲丽亚门店'),
  ('q1.passTitle', 'member', '次卡余额'),
  ('q1.passUnit', 'member', '次'),
  ('q1.pendingBody', 'member', '到店报手机号即可享受会员权益；扫码核销通道开通后本页自动升级。'),
  ('q1.pendingTitle', 'member', '会员码扫码核销升级中'),
  ('q1.pushLabel', 'member', '会员码 · MEMBER CODE'),
  ('q1.refreshNote', 'member', '{mm}:{ss} 后自动刷新'),
  ('rules.r1', 'member', '回馈金比例 {pct}%（{tier}档）· 仅抵商品 · 单笔不设上限'),
  ('rules.r1Free', 'member', '微光免费档无回馈金 · 付费档 {pcts}% · 仅抵商品'),
  ('rules.r2', 'member', '上月 26 日 – 本月 25 日结算 · 次月 {day} 日前到账（故障顺延 ≤3 天并明示）'),
  ('rules.r3', 'member', '{days} 天有效 · 到期未续冻结 · 续费即解冻 · 退卡清零'),
  ('rules.r3Free', 'member', '免费档永久有效 · 无到期无冻结 · 随时可升级付费档'),
  ('rules.r4', 'member', '回馈金不提现 · 不转让 · 不产息'),
  ('rules.r5', 'member', '用回馈金支付的部分不再返还'),
  ('rules.r6', 'member', '退货按退款比例扣回已返回馈金，余额不足扣至 0 不负账'),
  ('rules.r7', 'member', '回馈金 / 储值 / XP 三本账物理分离，均不计营业额'),
  ('rules.r8', 'member', '商品全员同价无会员价；服务折扣仅付费档生效'),
  ('rules.title', 'member', '年费 ≠ 储值 · 到期不自动续费'),
  ('saved.discountLine', 'member', '服务折扣节省'),
  ('saved.meSlotNote', 'member', '构成明面'),
  ('saved.noHypeNote', 'member', '只算已发生的回馈金与折扣，不含预计。'),
  ('saved.rebateLine', 'member', '回馈金累计到账'),
  ('saved.rowLine', 'member', '今年已省 ¥{total} ›'),
  ('saved.sheetTitle', 'member', '今年已省 · 构成明面'),
  ('saved.slotTitle', 'member', '今年已省'),
  ('saved.totalLine', 'member', '合计'),
  ('saved.yearNote', 'member', '{year} 年已发生口径'),
  ('slot.certSoon', 'member', '随体验批开通'),
  ('slot.soon', 'member', '即将点亮'),
  ('up.currentTitle', 'member', '当前档位'),
  ('up.emptyTitle', 'member', '当前没有可升档位'),
  ('up.emptyTopTier', 'member', '已是最高档，权益已全部点亮。'),
  ('up.entryCta', 'member', '升级会员 ›'),
  ('up.expireLine', 'member', '有效期至 {date}'),
  ('up.formulaLine', 'member', '剩余 {m} 整月 ×（新档月均价 ¥{newMonthly} − 旧档月均价 ¥{oldMonthly}）= ¥{diff}'),
  ('up.formulaPet', 'member', '多宠附加差价 ¥{pet}'),
  ('up.formulaTotal', 'member', '合计补差 ¥{total}'),
  ('up.freeTierGuide', 'member', '当前为免费档，升档按新购口径办理：全档价、到店收银台开通即时生效。'),
  ('up.headNo', 'member', 'UPGRADE QUOTE'),
  ('up.headTitle', 'member', '升级会员'),
  ('up.loadFail', 'member', '升级试算加载失败'),
  ('up.newPurchaseLine', 'member', '新购口径 = 全档价（多宠附加按现有宠物数计），开通时点重起算有效期'),
  ('up.newPurchaseTag', 'member', '新购口径'),
  ('up.nonMemberBody', 'member', '先开通会员（微光档免费一键开通），再按需要升档。'),
  ('up.nonMemberCta', 'member', '去开通会员 ›'),
  ('up.nonMemberTitle', 'member', '开通会员后可升档'),
  ('up.noteBalance', 'member', '旧档回馈金余额原样保留，零动作。'),
  ('up.noteEffective', 'member', '升档即时生效：新档权益只管新单，到期日不变。'),
  ('up.noteInflight', 'member', '在途回馈金不重算，按下单时档位口径到账。'),
  ('up.noteNoDowngrade', 'member', '期内不降级，可在到期前 {days} 天预约下期档位。'),
  ('up.notesTitle', 'member', '办理说明'),
  ('up.paidLine', 'member', '已付 ¥{price}'),
  ('up.pushLabel', 'member', '升级会员 · UPGRADE'),
  ('up.storeGuideBody', 'member', '内测期升级请到店收银台办理：出示会员码，店员代办补差，成交即时生效。'),
  ('up.storeGuideTitle', 'member', '到店办理'),
  ('up.targetTitle', 'member', '可升档位 · 试算明面'),
  ('w1.balanceFrozen', 'member', '已冻结 · 续费即解冻'),
  ('w1.balanceLabel', 'member', '可用余额'),
  ('w1.emptyCta', 'member', '去商城逛逛'),
  ('w1.emptyDesc', 'member', '每笔商品消费按档位比例返还，次月统一到账；仅抵商品、365 天有效。'),
  ('w1.emptyTitle', 'member', '回馈金是什么'),
  ('w1.fallbackTitle', 'member', '{type} · 单号 {no}'),
  ('w1.logsTitle', 'member', '明细'),
  ('w1.periodLine', 'member', '周期 {start} – {end} · {month}.{day} 前到账'),
  ('w1.pushLabel', 'member', '回馈金 · REBATE LEDGER'),
  ('w1.ringCenter', 'member', '本周期'),
  ('w1.typeClawback', 'member', '退货扣回'),
  ('w1.typeClear', 'member', '清零'),
  ('w1.typeDeduct', 'member', '回馈金抵扣'),
  ('w1.typeFreeze', 'member', '冻结'),
  ('w1.typeGrant', 'member', '消费回馈'),
  ('w1.yearTotal', 'member', '本年累计 ¥{amount}'),
  ('appt.boardingStayEmpty', 'merchant:appointments', '客户到店核销后，这里会登记房间、入住称重与随身物品。'),
  ('appt.createCta', 'merchant:appointments', '＋ 新增预约'),
  ('appt.createGuide', 'merchant:appointments', '新客户预约请引导至客户端预约页；到店客可由前台手动核销登记'),
  ('appt.detailNotFoundBody', 'merchant:appointments', '预约不存在或已被移除，回预约管理看看今天的单子。'),
  ('appt.detailNotFoundTitle', 'merchant:appointments', '找不到这个预约'),
  ('appt.listEmpty', 'merchant:appointments', '这一天没有预约'),
  ('appt.listSub', 'merchant:appointments', '{date} · 共 {count} 单 · 自动接单已启用'),
  ('appt.listSubAllDates', 'merchant:appointments', '全部日期'),
  ('appt.listTitle', 'merchant:appointments', '预约'),
  ('appt.payDialogBody', 'merchant:appointments', '{mode} · 应收 {amount}。登记后该预约转为「已收款」，不可撤销。'),
  ('appt.payDialogConfirm', 'merchant:appointments', '确认收款 {amount}'),
  ('appt.payDialogTitle', 'merchant:appointments', '登记收款？'),
  ('appt.progressActive', 'merchant:appointments', '第 {n}/6 步 · 实时同步'),
  ('appt.progressCount', 'merchant:appointments', '{done}/6 步'),
  ('appt.progressDone', 'merchant:appointments', '六步完成'),
  ('appt.progressWait', 'merchant:appointments', '等待到店核销'),
  ('appt.rescheduleEmpty', 'merchant:appointments', '未来 7 天暂无可约时段，请稍后再试或调整服务时长'),
  ('appt.reviewCancelBody', 'merchant:appointments', '客户在开始前 {hours} 小时内申请取消该预约。批准后槽位立即释放并通知客户；拒绝后预约恢复为「已确认」。'),
  ('appt.trailAside', 'merchant:appointments', '事件即轨迹 · 按时间排序'),
  ('appt.trailEmpty', 'merchant:appointments', '暂无可展示的事件'),
  ('appt.verifyCodeHint', 'merchant:appointments', '客户到店后由员工扫码或输入此码核销'),
  ('auth.agreement', 'merchant:auth', '登录即同意《商家内测协议》· 遇到问题联系 philia 小助手'),
  ('auth.devNote', 'merchant:auth', '仅开发环境：dev-login 仅允许种子用户（kimi_id 以 seed_ 前缀），会话 cookie 有效期 7 天。 非商家账号登录后会被引导回本页切换。'),
  ('auth.enterCta', 'merchant:auth', '进入门店'),
  ('auth.gateNotice', 'merchant:auth', '内测环境需先在下方输入口令'),
  ('auth.manifestoA', 'merchant:auth', '店里的每一件小事，'),
  ('auth.manifestoB', 'merchant:auth', '都值得被认真对待'),
  ('auth.seedEmpty', 'merchant:auth', '未拉到店主种子用户，请重跑 server 的 db:seed，或手动输入 userId'),
  ('auth.subtitle', 'merchant:auth', '菲丽亚宠物 · 门店经营后台（内测）'),
  ('auth.wordmark', 'merchant:auth', 'PHILIA · 商家端'),
  ('board.checkinCta', 'merchant:boarding', '＋ 入住登记'),
  ('board.checkinGuide', 'merchant:boarding', '入住登记由前台在员工端办理（到店扫码）'),
  ('board.checkoutConfirmNote', 'merchant:boarding', '确认后预约转为「已完成」，房间立即释放；操作幂等，重复点击不会重复结算。'),
  ('board.checkoutOverdue', 'merchant:boarding', '本单已超期，请与客户确认续住或按约结算。'),
  ('board.checkoutPayNote', 'merchant:boarding', '本单为到店付：退房后请在财务页「待收款」确认收款，款项才会计入营业额。'),
  ('board.detailPlaceholder', 'merchant:boarding', '点选左侧在店行查看入住详情'),
  ('board.emptyBody', 'merchant:boarding', '客户寄养单核销入店后会出现在这里'),
  ('board.emptyTitle', 'merchant:boarding', '现在没有寄养的毛孩子'),
  ('board.panelAside', 'merchant:boarding', '按退房日排序'),
  ('board.roomVacant', 'merchant:boarding', '空 · 可订'),
  ('board.stayCheckoutLead', 'merchant:boarding', '退房核销由员工在员工端办理（v1.1 起）；员工退房后本单转入「已完成」，'),
  ('board.stayCheckoutOther', 'merchant:boarding', '款项以店内结算为准。'),
  ('board.stayCheckoutPayStore', 'merchant:boarding', '到店付请到财务页「待收款」确认收款。'),
  ('board.stayLogsGap', 'merchant:boarding', '打卡明细（喂食 / 遛弯 / 照片墙）的商家查看接口待服务端补齐（v2）； 目前明细可在员工端寄养打卡页查看。'),
  ('board.sub', 'merchant:boarding', '在店 {a} 只 · 今日退房 {b} 只 · {c} 只今日未打卡'),
  ('board.title', 'merchant:boarding', '寄养'),
  ('cashier.adjustNote', 'merchant:cashier', '备注追加进调整记录留痕，原冻结数字不涂改。'),
  ('cashier.billRefundDetailLink', 'merchant:cashier', '（详情见「退款」列表页）'),
  ('cashier.billReversalNote', 'merchant:cashier', ' · 金额镜像负值，不计入已收'),
  ('cashier.billReversedNote', 'merchant:cashier', ' · 不再计入已收（原单永存不涂改）'),
  ('cashier.cartEmpty', 'merchant:cashier', '点左侧商品或服务开单'),
  ('cashier.closeShiftConfirmBody', 'merchant:cashier', '交接班=关闭当前班次（不冻结账目）；下一笔收银将自动开新班。 如需冻结当班账目，请用「日结」。'),
  ('cashier.closeShiftConfirmTitle', 'merchant:cashier', '交接班确认'),
  ('cashier.closeSub', 'merchant:cashier', '交接班=闭班不冻结 · 日结=冻结当班账目 · 反结账（拆箱）仅店主'),
  ('cashier.closeTitle', 'merchant:cashier', '日结 / 交接班'),
  ('cashier.dayCloseEmpty', 'merchant:cashier', '暂无日结单 —— 上方表单完成首次日结'),
  ('cashier.dayCloseFullNote', 'merchant:cashier', '全日口径：当前无开班班次也可日结（账面按当日全部支付段计）'),
  ('cashier.dayCloseListAside', 'merchant:cashier', '冲正单与原单双向可查 · 原单永存不涂改'),
  ('cashier.discountOverNote', 'merchant:cashier', '优惠不能超过服务/商品行合计（预约行金额不参与优惠）'),
  ('cashier.flowEmpty', 'merchant:cashier', '今日暂无流水'),
  ('cashier.headTenderRef', 'merchant:cashier', '参考（不计入已收）'),
  ('cashier.holdEmpty', 'merchant:cashier', '无挂单'),
  ('cashier.holdFooter', 'merchant:cashier', '点卡取单续结 · ⋯ 撤单（留痕）'),
  ('cashier.importAside', 'merchant:cashier', '只交付不执行——真台账导入等老板令；演示台账试导可标记清除'),
  ('cashier.importClearNote', 'merchant:cashier', '将删除该批次写入的流水并按日志反向冲减账户；批次行永存（置「已清除」留痕）。'),
  ('cashier.importClearReject', 'merchant:cashier', '已产生消费的批次拒绝清除（保护真账）——差错请走对账调整留痕。'),
  ('cashier.importConfirmNote', 'merchant:cashier', '真台账（907 人 / ¥671,264.42）执行等老板令；本次为演示台账试导，试导后可用「标记清除」回滚。 重复 execute 会重复入账（无文件级幂等），请勿重复提交。'),
  ('cashier.importConfirmPost', 'merchant:cashier', '行可导记录开户/加账并写流水（批次留痕可查）。'),
  ('cashier.importConfirmPre', 'merchant:cashier', '将对'),
  ('cashier.importMappingTitle', 'merchant:cashier', '门店映射（台账店名 → 系统门店；未映射行将失败留痕）'),
  ('cashier.memberAlreadyMember', 'merchant:cashier', '该客户已是会员 —— 点这里切换到「续费」'),
  ('cashier.memberDiscountUnknown', 'merchant:cashier', '会员折扣由服务端结账时按档自动计算，折后价以成交为准（内测期档位读路径缺口）'),
  ('cashier.memberNextPlanBadge', 'merchant:cashier', '已预约下期：{plan}'),
  ('cashier.memberPaySectionNote', 'merchant:cashier', '到店付收款段（内测期现金/微信/支付宝登记，Σ须等于应收）'),
  ('cashier.memberPlansMissing', 'merchant:cashier', '档位配置缺失——请在规则配置端口检查会员档（member_plans 域）'),
  ('cashier.memberRenewCalcNote', 'merchant:cashier', '续费金额=当前档价+既有宠物只数附加费，由 server 实算——先点「计算续费金额」取得应收再收款。'),
  ('cashier.memberRenewNote', 'merchant:cashier', '续费=当前档位顺延 {days} 天（到期冻结自今日顺延）+ 回馈金解冻；档位不变（变更请退会后重售）。'),
  ('cashier.memberRulesNote', 'merchant:cashier', '会员费=权益服务费（年费 ≠ 储值，不计储值账户/不进储值看板）；有效期 {days} 天自开通日； 到期不自动续费（到期=冻结，续费解冻，退会清零回馈金）。'),
  ('cashier.memberSearchEmpty', 'merchant:cashier', '未找到会员，按散客结账'),
  ('cashier.memberStatusNote', 'merchant:cashier', '会员状态以提交时 server 实算为准（内测期读路径缺口，错误原文透出）'),
  ('cashier.offlineBar', 'merchant:cashier', '离线中 —— 结账将先本地暂存，恢复网络后自动补传'),
  ('cashier.offlineFlushing', 'merchant:cashier', '网络已恢复，正在补传暂存单…'),
  ('cashier.offlinePending', 'merchant:cashier', '暂存单待补传'),
  ('cashier.payComboRule', 'merchant:cashier', '可组合支付：Σ支付 = 应收 才放行确认'),
  ('cashier.payGapOver', 'merchant:cashier', '超出 ¥{amt}——调低任一段金额后才可确认'),
  ('cashier.payGapUnder', 'merchant:cashier', '还差 ¥{amt}——补足后才可确认结账'),
  ('cashier.payNextCta', 'merchant:cashier', '再开一单'),
  ('cashier.payOfflineBar', 'merchant:cashier', '离线中 —— 确认后本地暂存，恢复网络自动补传'),
  ('cashier.payPassNoCard', 'merchant:cashier', '该会员无可用次卡'),
  ('cashier.payPassNoGroom', 'merchant:cashier', '车内无洗护服务行（次卡仅洗护可用）'),
  ('cashier.payPassNoMember', 'merchant:cashier', '次卡扣次：散客不可用——先检索会员'),
  ('cashier.payPassOnly', 'merchant:cashier', '全额次卡扣次——无需现金/扫码段（次卡单列，不计入已收）'),
  ('cashier.payPassShort', 'merchant:cashier', '次卡余额不足：剩 {remain} 次 · 需 {need} 次'),
  ('cashier.payRebateCap', 'merchant:cashier', '回馈金金额须 ≤ min(商品行合计 ¥{prod}, 应收 ¥{due}{bal})，可混搭现金/扫码补足'),
  ('cashier.payRebateNoProduct', 'merchant:cashier', '回馈金仅可抵商品——当单无商品行（服务/寄养行禁用回馈金段）'),
  ('cashier.payRebateNote', 'merchant:cashier', '已到账余额 1:1 抵扣（本期预计在途回馈金次月到账后可用）；用回馈金付的部分不再返'),
  ('cashier.payRebateZeroBalance', 'merchant:cashier', '回馈金已到账余额为 0（本期预计次月到账后可用）'),
  ('cashier.payRebateZeroDue', 'merchant:cashier', '应收已为 0（次卡已全额抵扣）——无需回馈金段'),
  ('cashier.paySuccessBack', 'merchant:cashier', '3 秒后自动返回'),
  ('cashier.paySvZeroDue', 'merchant:cashier', '应收已为 0（次卡已全额抵扣）——无需储值段'),
  ('cashier.payTenderNote', 'merchant:cashier', '已收口径=现金/微信/支付宝；次卡扣次 / 储值消费 / 回馈金抵扣单列，不计入今日已收'),
  ('cashier.priceNewNote', 'merchant:cashier', '新价 ¥{amt}（改价留痕，随单可查）'),
  ('cashier.recordsEmpty', 'merchant:cashier', '当前筛选无流水——收银台结账后单据会出现在这里'),
  ('cashier.recordsSub', 'merchant:cashier', '挂单 / 结账 / 撤单 / 冲正全留痕 · 共 {n} 单'),
  ('cashier.recordsTitle', 'merchant:cashier', '收银流水'),
  ('cashier.refundAllocNote', 'merchant:cashier', '按支付段占比同比例分摊回补（V3）；按金额退不回库存只退钱（口径写死）'),
  ('cashier.refundAmountNoRestock', 'merchant:cashier', '按金额退不回库存只退钱（口径写死）'),
  ('cashier.refundAnchorNote', 'merchant:cashier', '次卡退卡为锚点单口径：金额与原单支付段无关，按下方折算明细落地'),
  ('cashier.refundBoardingNote', 'merchant:cashier', '已发生晚一分不退；已住/剩余晚数与晚单价以六联动预览为准（分段明示）'),
  ('cashier.refundCrossDayNote', 'merchant:cashier', '跨日退款计入退款发生日日结（V7）；已封箱历史日结单不回填，只读留痕。'),
  ('cashier.refundDangerBody', 'merchant:cashier', '危险操作：确认即同事务六联动落账（退款单/支付段回补/库存回补/储值次卡回补/财务口径/回馈金列位）， executed 后不可撤销，纠错=再开正单。'),
  ('cashier.refundDayAside', 'merchant:cashier', '当日净额=已收−退款 · 历史日结封箱不回填（只读）'),
  ('cashier.refundDraftEmpty', 'merchant:cashier', '草稿单未执行，无六联动快照'),
  ('cashier.refundExecuteNote', 'merchant:cashier', '执行=同事务六联动落账，不可撤销（纠错=再开正单）'),
  ('cashier.refundNoProductRestock', 'merchant:cashier', '无商品行回补'),
  ('cashier.refundOfflineMethod', 'merchant:cashier', '线下原路（内测期口径，实退标记待登记）'),
  ('cashier.refundPassCancelNote', 'merchant:cashier', '折算=剩余付费次数×（实付÷付费总次数），赠次不计价（随退作废）；退卡后卡作废留痕'),
  ('cashier.refundRejectNote', 'merchant:cashier', '驳回仅对草稿（draft）生效；驳回留痕 rejected+原因。已执行单不可撤销，纠错=再开正单。'),
  ('cashier.refundRequestApproveConfirmBody', 'merchant:cashier', '批准后按 R12 既有链路原路退回并生成退款单（商城单走线下原路售后）；执行后不可撤销，纠错=再开正单。'),
  ('cashier.refundRequestApproveConfirmTitle', 'merchant:cashier', '批准退款申请'),
  ('cashier.refundRequestApproveCta', 'merchant:cashier', '批准'),
  ('cashier.refundRequestRejectCta', 'merchant:cashier', '驳回'),
  ('cashier.refundRequestRejectNote', 'merchant:cashier', '驳回留痕 rejected+原因，客户侧申请单可见驳回原因。'),
  ('cashier.refundRequestRejectTitle', 'merchant:cashier', '驳回退款申请'),
  ('cashier.refundRequestSlaOverdue', 'merchant:cashier', '超期'),
  ('cashier.refundRequestTitle', 'merchant:cashier', '客户退款申请'),
  ('cashier.refundRequestTypeRefundOnly', 'merchant:cashier', '仅退款'),
  ('cashier.refundRequestTypeReturnRefund', 'merchant:cashier', '退货退款'),
  ('cashier.refundsEmpty', 'merchant:cashier', '当前筛选无退款单——收银流水已收单的退款会出现在这里'),
  ('cashier.refundSettleNote', 'merchant:cashier', '内测期实退=线下原路退回+系统内登记；登记后退款单置「实退完成」，账不再变（executed 不可撤销口径）。'),
  ('cashier.refundsGuideHint', 'merchant:cashier', '退款发起与实退登记属管理层动作；店员账号的工作面是收银台。'),
  ('cashier.refundsGuideTitle', 'merchant:cashier', '退款单由店长或店主处理'),
  ('cashier.refundsPendingBold', 'merchant:cashier', '笔退款超 24 小时未登记实退'),
  ('cashier.refundsPendingTail', 'merchant:cashier', '——线下原路退回后请点行内「实退登记」'),
  ('cashier.refundsSub', 'merchant:cashier', '退款 ≠ 反结账 · 经营行为计退款单列 · 当日净额=已收−退款 · 原单永存不涂改'),
  ('cashier.refundsTitle', 'merchant:cashier', '退款单'),
  ('cashier.refundSvNotice', 'merchant:cashier', '本单涉储值/次卡：退款须店主办理（负债科目不设阈值，server 同口径拦截）'),
  ('cashier.reverseCloseNote', 'merchant:cashier', '拆箱将生成冲正关联单（含前后值快照/操作人/时间/原因），原日结单永存不涂改（置「已冲正」）；之后可对同日重新日结（全日口径）。'),
  ('cashier.reverseNote', 'merchant:cashier', '冲正将自动生成关联冲正单（金额镜像负值，不计当日已收）：库存回补、预约回到待收款、 次卡/储值按原路回补；原单永存不涂改，仅挂「已冲正」灰签（双向可查）。'),
  ('cashier.savingsCta', 'merchant:cashier', '开通萤火 ›'),
  ('cashier.shiftEmpty', 'merchant:cashier', '当前无开班班次 —— 首笔收银将自动开班（懒建）'),
  ('cashier.stockShort', 'merchant:cashier', '库存不足：余 {n} 件，结账将按实际库存扣减'),
  ('cashier.title', 'merchant:cashier', '收银台'),
  ('cashier.upgradeBillIdempotent', 'merchant:cashier', '（同档幂等，无新单）'),
  ('cashier.upgradeBillLabel', 'merchant:cashier', '补差单号'),
  ('cashier.upgradeDiffBase', 'merchant:cashier', '档价补差 ¥{amount}'),
  ('cashier.upgradeDiffMonthsTag', 'merchant:cashier', '剩余 {m} 整月补差'),
  ('cashier.upgradeDiffPet', 'merchant:cashier', '多宠附加补差 ¥{amount}'),
  ('cashier.upgradeDone', 'merchant:cashier', '完成'),
  ('cashier.upgradeDoneTitle', 'merchant:cashier', '升档完成 · 当前档「{plan}」（即时生效，到期日不变）'),
  ('cashier.upgradeFormula', 'merchant:cashier', '剩余 {m} 整月 ×（新档月均价 ¥{newMonthly} − 旧档月均价 ¥{oldMonthly}）= 补差 ¥{total}'),
  ('cashier.upgradeModeTab', 'merchant:cashier', '升级补差'),
  ('cashier.upgradeNewPurchaseNote', 'merchant:cashier', '新购口径：按新档全价实收（多宠附加按当前只数重算），有效期自成交日重起算'),
  ('cashier.upgradeNewPurchaseTag', 'merchant:cashier', '新购口径'),
  ('cashier.upgradeNoDowngradeNote', 'merchant:cashier', '期内只升不降——如需换到更低档，可在到期前 {days} 天预约下期档位'),
  ('cashier.upgradeQuoteLoading', 'merchant:cashier', '试算加载中…'),
  ('cashier.upgradeQuoteTotal', 'merchant:cashier', '补差应收（server 实算）'),
  ('cashier.upgradeSubmit', 'merchant:cashier', '收 ¥{amount} 升档'),
  ('cashier.upgradeSubmitting', 'merchant:cashier', '升档中…'),
  ('cashier.upgradeSuccess', 'merchant:cashier', '已升档「{plan}」· 补差单 {billNo}（¥{amount}）'),
  ('cashier.upgradeSuccessIdempotent', 'merchant:cashier', '已是「{plan}」档——无需补差，未生成新单'),
  ('cashier.voidNote', 'merchant:cashier', '撤单后单据留痕为「已撤单」，不会物理删除；仅未支付单可撤（已结账请店主用反结账）'),
  ('copyport.changedBadge', 'merchant:copyPort', '已改'),
  ('copyport.confirmBody', 'merchant:copyPort', '保存即生效（客户端新渲染）。以下 {n} 项变更将写入口径留痕：'),
  ('copyport.confirmCancel', 'merchant:copyPort', '再想想'),
  ('copyport.confirmHighRiskBody', 'merchant:copyPort', '以下 {n} 键属高危键，保存前请逐条核对前后值。键入「确认保存」四个字解锁：'),
  ('copyport.confirmHighRiskTitle', 'merchant:copyPort', '含高危键（涉钱/涉协议/涉会员口径）'),
  ('copyport.confirmMismatch', 'merchant:copyPort', '口令不符，请键入「确认保存」'),
  ('copyport.confirmOk', 'merchant:copyPort', '确认保存'),
  ('copyport.confirmPlaceholder', 'merchant:copyPort', '键入：确认保存'),
  ('copyport.confirmTitle', 'merchant:copyPort', '确认保存文案变更？'),
  ('copyport.defaultNote', 'merchant:copyPort', '码内默认'),
  ('copyport.editCancel', 'merchant:copyPort', '收起'),
  ('copyport.editCta', 'merchant:copyPort', '改文案'),
  ('copyport.emptyDomain', 'merchant:copyPort', '该域无匹配键'),
  ('copyport.filterChanged', 'merchant:copyPort', '只看已改'),
  ('copyport.filterHighRisk', 'merchant:copyPort', '只看高危键'),
  ('copyport.highRiskBadge', 'merchant:copyPort', '高危'),
  ('copyport.historyBy', 'merchant:copyPort', '操作人：{name}'),
  ('copyport.historyEmpty', 'merchant:copyPort', '还没有变更记录'),
  ('copyport.historyTitle', 'merchant:copyPort', '变更留痕'),
  ('copyport.historyVersion', 'merchant:copyPort', 'v{version}'),
  ('copyport.keysCount', 'merchant:copyPort', '{n} 键'),
  ('copyport.loadFail', 'merchant:copyPort', '文案配置加载失败，请检查网络后重试'),
  ('copyport.ownerOnly', 'merchant:copyPort', '文案端口仅店主可改'),
  ('copyport.ownerOnlyBody', 'merchant:copyPort', '界面文案涉钱涉口径，仅店主账号可进入编辑。如需调整请联系店主。'),
  ('copyport.pageSub', 'merchant:copyPort', '界面文案后台可改 · 保存即生效（新渲染）· 全程留痕'),
  ('copyport.pageTitle', 'merchant:copyPort', '文案端口'),
  ('copyport.pendingBar', 'merchant:copyPort', '{n} 项待保存变更'),
  ('copyport.saveCta', 'merchant:copyPort', '保存变更'),
  ('copyport.savedToast', 'merchant:copyPort', '文案已保存，客户端新渲染即生效'),
  ('copyport.saveFail', 'merchant:copyPort', '保存失败，请稍后再试'),
  ('copyport.searchPlaceholder', 'merchant:copyPort', '搜索键名或文案…'),
  ('slotport.empty', 'merchant:copyPort', '槽位注册表为空（种子未落库）'),
  ('slotport.liveBadge', 'merchant:copyPort', '上线中'),
  ('slotport.loadFail', 'merchant:copyPort', '槽位数据加载失败，请检查网络后重试'),
  ('slotport.noLive', 'merchant:copyPort', '暂无上线版本'),
  ('slotport.ownerOnly', 'merchant:copyPort', '槽位端口仅店主可改'),
  ('slotport.ownerOnlyBody', 'merchant:copyPort', '展示素材涉门店门面口径，仅店主账号可上传与上线。如需调整请联系店主。'),
  ('slotport.pageSub', 'merchant:copyPort', '展示素材后台可换 · 新素材默认待审 · 点上线即生效（新渲染）'),
  ('slotport.pageTitle', 'merchant:copyPort', '槽位端口'),
  ('slotport.pendingBadge', 'merchant:copyPort', '待审'),
  ('slotport.pendingCount', 'merchant:copyPort', '{n} 个待审'),
  ('slotport.pendingTitle', 'merchant:copyPort', '待审版本'),
  ('slotport.placeholderBadge', 'merchant:copyPort', '占位中'),
  ('slotport.placeholderNote', 'merchant:copyPort', '码内默认渐变/图标占位，上传真件并点上线后替换'),
  ('slotport.publishCta', 'merchant:copyPort', '点上线'),
  ('slotport.publishedToast', 'merchant:copyPort', '已上线，客户端新渲染即生效'),
  ('slotport.publishFail', 'merchant:copyPort', '上线失败，请稍后再试'),
  ('slotport.revertCta', 'merchant:copyPort', '回退上一版'),
  ('slotport.revertedToast', 'merchant:copyPort', '已回退上一版，客户端新渲染即生效'),
  ('slotport.revertFail', 'merchant:copyPort', '回退失败，请稍后再试'),
  ('slotport.uploadCta', 'merchant:copyPort', '上传替换'),
  ('slotport.uploadedToast', 'merchant:copyPort', '已上传，待审中（点上线后生效）'),
  ('slotport.uploadFail', 'merchant:copyPort', '上传失败，请稍后再试'),
  ('slotport.uploading', 'merchant:copyPort', '上传中…'),
  ('slotport.versionInfo', 'merchant:copyPort', 'v{version} · 共 {total} 版'),
  ('dash.appealAssistConfirmTitle', 'merchant:dashboard', '协助换绑确认'),
  ('dash.appealAssistCta', 'merchant:dashboard', '协助换绑'),
  ('dash.appealAssistNoteLabel', 'merchant:dashboard', '核验说明（必填，客户端可见）'),
  ('dash.appealAssistNotePlaceholder', 'merchant:dashboard', '核验方式与结论留痕，如：已线下核对本人证件'),
  ('dash.appealAssistNoteRequired', 'merchant:dashboard', '请先填写核验说明'),
  ('dash.appealAssistNotice', 'merchant:dashboard', '确认已线下核验身份，换绑后数据全保留'),
  ('dash.appealAssistSubmit', 'merchant:dashboard', '确认协助换绑'),
  ('dash.appealAssistSuccess', 'merchant:dashboard', '已协助换绑，新手机号已生效'),
  ('dash.appealBlockTitle', 'merchant:dashboard', '换绑申诉'),
  ('dash.appealCancelCta', 'merchant:dashboard', '取消'),
  ('dash.appealCountUnit', 'merchant:dashboard', '笔'),
  ('dash.appealRejectCta', 'merchant:dashboard', '驳回'),
  ('dash.appealRejectNoteLabel', 'merchant:dashboard', '驳回原因（必填，客户端可见）'),
  ('dash.appealRejectNotePlaceholder', 'merchant:dashboard', '驳回原因将展示给客户'),
  ('dash.appealRejectNoteRequired', 'merchant:dashboard', '请先填写驳回原因'),
  ('dash.appealRejectSubmit', 'merchant:dashboard', '确认驳回'),
  ('dash.appealRejectSuccess', 'merchant:dashboard', '已驳回该换绑申诉'),
  ('dash.appealRejectTitle', 'merchant:dashboard', '驳回换绑申诉'),
  ('dash.appealSlaOverdue', 'merchant:dashboard', '超期'),
  ('dash.cancel', 'merchant:dashboard', '取消'),
  ('dash.invoiceAmountNote', 'merchant:dashboard', '开票金额=订单实付 ¥{amount}'),
  ('dash.invoiceBillLead', 'merchant:dashboard', '原单'),
  ('dash.invoiceBlockTitle', 'merchant:dashboard', '发票申请'),
  ('dash.invoiceDeliveryEmail', 'merchant:dashboard', '邮箱发送'),
  ('dash.invoiceDeliveryPickup', 'merchant:dashboard', '到店自取'),
  ('dash.invoiceLoadFailed', 'merchant:dashboard', '发票申请列表加载失败'),
  ('dash.invoiceNoLabel', 'merchant:dashboard', '实际发票号（必填）'),
  ('dash.invoiceNoPlaceholder', 'merchant:dashboard', '输入已开具的发票号'),
  ('dash.invoiceNoRequired', 'merchant:dashboard', '请填写实际发票号'),
  ('dash.invoiceRegisterCta', 'merchant:dashboard', '登记开票'),
  ('dash.invoiceRegistering', 'merchant:dashboard', '登记中…'),
  ('dash.invoiceRegisterSubmit', 'merchant:dashboard', '确认登记'),
  ('dash.invoiceRegisterSuccess', 'merchant:dashboard', '已登记开票 {no}')
)
INSERT INTO `copy_overrides` (`id`,`version`,`rule_key`,`label`,`value_json`,`effective_from`,`active`,`created_by`,`created_at`,`updated_at`)
SELECT 'seedcopy_' || lower(hex(randomblob(8))), 1, s.rule_key, s.label, json_object('text', s.text), unixepoch(), 1, 'system', unixepoch(), unixepoch()
FROM s
WHERE NOT EXISTS (SELECT 1 FROM `copy_overrides` WHERE `rule_key` = s.rule_key AND `active` = 1);
--> statement-breakpoint
WITH s(rule_key, label, text) AS (VALUES
  ('dash.invoiceRegisterTitle', 'merchant:dashboard', '登记开票 {no}'),
  ('dash.invoiceTaxNoLead', 'merchant:dashboard', '税号'),
  ('dash.invoiceTitleBusiness', 'merchant:dashboard', '企业'),
  ('dash.invoiceTitleLead', 'merchant:dashboard', '抬头'),
  ('dash.invoiceTitlePersonal', 'merchant:dashboard', '个人'),
  ('dash.retry', 'merchant:dashboard', '重试'),
  ('dash.statBoardingEmpty', 'merchant:dashboard', '当前无在店寄养'),
  ('dash.statCapAppt', 'merchant:dashboard', '今日预约'),
  ('dash.statCapBoarding', 'merchant:dashboard', '在店寄养'),
  ('dash.statCapMode', 'merchant:dashboard', '接单模式'),
  ('dash.statCapRevenue', 'merchant:dashboard', '今日营业额'),
  ('dash.statModePill', 'merchant:dashboard', '已启用 · 新预约免确认'),
  ('dash.statModeValue', 'merchant:dashboard', '自动接单'),
  ('dash.ticketBlockTitle', 'merchant:dashboard', '客服工单'),
  ('dash.ticketContactNone', 'merchant:dashboard', '未留联系方式'),
  ('dash.ticketLoadFailed', 'merchant:dashboard', '工单列表加载失败'),
  ('dash.ticketPhotoCount', 'merchant:dashboard', '附图 {n} 张'),
  ('dash.ticketReplyCta', 'merchant:dashboard', '回复'),
  ('dash.ticketReplyLabel', 'merchant:dashboard', '回复内容（必填）'),
  ('dash.ticketReplyPlaceholder', 'merchant:dashboard', '写下给客户的回复…'),
  ('dash.ticketReplyRequired', 'merchant:dashboard', '请填写回复内容'),
  ('dash.ticketReplySubmit', 'merchant:dashboard', '提交回复'),
  ('dash.ticketReplySubmitting', 'merchant:dashboard', '提交中…'),
  ('dash.ticketReplySuccess', 'merchant:dashboard', '已回复工单 {no}'),
  ('dash.ticketReplyTitle', 'merchant:dashboard', '回复工单 {no}'),
  ('dash.ticketTypeComplaint', 'merchant:dashboard', '投诉'),
  ('dash.ticketTypeOther', 'merchant:dashboard', '其他'),
  ('dash.ticketTypePraise', 'merchant:dashboard', '表扬'),
  ('dash.ticketTypeSuggest', 'merchant:dashboard', '建议'),
  ('dash.timelineEmpty', 'merchant:dashboard', '今天还没有预约——把预约页分享给老客，或等自动接单'),
  ('dash.timelineTitle', 'merchant:dashboard', '今日预约'),
  ('dash.title', 'merchant:dashboard', '经营总览'),
  ('dash.todoAppealHint', 'merchant:dashboard', '手机号换绑申诉，待协助核验'),
  ('dash.todoAppealLabel', 'merchant:dashboard', '换绑申诉'),
  ('dash.todoCancelHint', 'merchant:dashboard', '客户申请取消，待审批'),
  ('dash.todoCancelLabel', 'merchant:dashboard', '取消申请待审'),
  ('dash.todoInvoiceHint', 'merchant:dashboard', '客户开票申请待登记'),
  ('dash.todoInvoiceLabel', 'merchant:dashboard', '发票申请'),
  ('dash.todoOverdueHint', 'merchant:dashboard', '超过预计退房时间仍在店'),
  ('dash.todoOverdueLabel', 'merchant:dashboard', '超期寄养'),
  ('dash.todoOverdueLead', 'merchant:dashboard', '应退未退'),
  ('dash.todoOverdueToday', 'merchant:dashboard', '今日到期未退'),
  ('dash.todoOverdueUnit', 'merchant:dashboard', '天'),
  ('dash.todoPendingHint', 'merchant:dashboard', '自动接单已启用 · 仅旧单与改期回退单在此'),
  ('dash.todoPendingLabel', 'merchant:dashboard', '历史待确认单'),
  ('dash.todoRefundRequestHint', 'merchant:dashboard', '客户申请退款，待审批'),
  ('dash.todoRefundRequestLabel', 'merchant:dashboard', '客户退款申请'),
  ('dash.todoTicketHint', 'merchant:dashboard', '客户反馈待回复'),
  ('dash.todoTicketLabel', 'merchant:dashboard', '客服工单'),
  ('dash.todoTitle', 'merchant:dashboard', '待办'),
  ('dash.todoUnpaidHint', 'merchant:dashboard', '服务已完成，未登记收款'),
  ('dash.todoUnpaidLabel', 'merchant:dashboard', '待收款'),
  ('fin.capDeduct', 'merchant:finance', '次卡扣次（非现金）'),
  ('fin.capPending', 'merchant:finance', '待收款'),
  ('fin.capReceived7d', 'merchant:finance', '近 7 天已收'),
  ('fin.capReceivedDay', 'merchant:finance', '今日已收'),
  ('fin.capReceivedMonth', 'merchant:finance', '本月已收'),
  ('fin.deductNote', 'merchant:finance', '不计入营业额'),
  ('fin.ledgerAside', 'merchant:finance', '按时间倒序'),
  ('fin.ledgerEmpty', 'merchant:finance', '{period}还没有收款'),
  ('fin.ledgerTitle', 'merchant:finance', '收款流水'),
  ('fin.pendingEmpty', 'merchant:finance', '无待收单'),
  ('fin.refundNetLead', 'merchant:finance', '当日净额=已收−退款：'),
  ('fin.refundStripNote', 'merchant:finance', '（现金段净额=现金已收−现金退款，现金退款 ¥{amt} 详见日结页； 跨日退款计入发生日，历史封箱不回填）'),
  ('fin.refundStripTitle', 'merchant:finance', '今日退款'),
  ('fin.sub', 'merchant:finance', '今日已收 ¥{received} · 待收 ¥{pending} · 口径=收款登记（到店付）'),
  ('fin.title', 'merchant:finance', '财务'),
  ('mon.boardingLogsEmpty', 'merchant:monitor', '员工打卡后会实时出现在这里；历史打卡明细请在「寄养管理」页查看。'),
  ('mon.cancelledBody', 'merchant:monitor', '该预约已取消，无服务过程可监视。'),
  ('mon.cancelledTitle', 'merchant:monitor', '预约已取消'),
  ('mon.flagBodyActive', 'merchant:monitor', '该步骤当前进行中，打标后员工会收到重拍提醒。'),
  ('mon.flagBodyDone', 'merchant:monitor', '该步骤将回退为「进行中」，已有照片全部作废，员工需重新拍摄上传。'),
  ('mon.flagBodyReopen', 'merchant:monitor', '该预约已完成：打标将重新开启本预约（打回「服务中」），该步骤回退为「进行中」，员工重拍后需重新确认完成。'),
  ('mon.flagTitle', 'merchant:monitor', '打标重拍「{step}」？'),
  ('mon.hubBoardingOverdue', 'merchant:monitor', '应退未退 {n} 天 · 联系主人或续住'),
  ('mon.hubEmpty', 'merchant:monitor', '现在店里很安静——有单开工时这里会实时动起来'),
  ('mon.hubSub', 'merchant:monitor', '服务中 {a} 单 · 寄养 {b} 只 · 实时同步'),
  ('mon.hubTitle', 'merchant:monitor', '在店监控'),
  ('mon.notStartedBody', 'merchant:monitor', '客户到店核销后，这里会实时展示服务进度与照片。'),
  ('mon.notStartedTitle', 'merchant:monitor', '服务尚未开始'),
  ('mon.parentViewAside', 'merchant:monitor', '与客户端「服务中全程页」同源'),
  ('mon.parentViewBody', 'merchant:monitor', '家长看到的内容与这屏一致（六步进度+过程照）。照片一经上传即双频道推送，不可删除，仅可被商家「打标重拍」作废旧照（B3-1 在案）。'),
  ('mon.parentViewTitle', 'merchant:monitor', '家长端视角'),
  ('mon.staffContactNote', 'merchant:monitor', '店内对讲或到工位找TA；联系方式请走门店内部渠道。'),
  ('mon.staffUnassigned', 'merchant:monitor', '该单尚未指派员工，可在预约详情页改派。'),
  ('mon.stepsEmpty', 'merchant:monitor', '六步流尚未初始化（等待员工核销）。'),
  ('mon.wallEmpty', 'merchant:monitor', '员工上传过程照后会实时出现在这里。'),
  ('order.emptyAll', 'merchant:orders', '还没有订单'),
  ('order.emptyPaid', 'merchant:orders', '没有待发货订单'),
  ('order.emptyRefunding', 'merchant:orders', '没有售后订单'),
  ('order.emptySearch', 'merchant:orders', '没有找到匹配的订单'),
  ('order.emptyShipped', 'merchant:orders', '没有已发货订单'),
  ('order.sub', 'merchant:orders', '待发货 {a} · 已发货 {b} · 售后 {c}'),
  ('order.title', 'merchant:orders', '商城订单'),
  ('pass.empty', 'merchant:pass', '还没有客户买次卡——洗护 10 次卡是老客最爱'),
  ('pass.listAside', 'merchant:pass', '按剩余次数'),
  ('pass.logsAside', 'merchant:pass', '近 100 条 · 倒序'),
  ('pass.logsEmpty', 'merchant:pass', '暂无扣次流水——预约扣次、取消/拒单回补、售卡充次都会记在这里'),
  ('pass.sellCta', 'merchant:pass', '＋ 售卡'),
  ('pass.sub', 'merchant:pass', '在效次卡 {n} 张 · 年费会员细则待定（冻结决策 15）'),
  ('pass.title', 'merchant:pass', '会员 · 次卡'),
  ('pass.topUpCustomerHint', 'merchant:pass', '仅列出本店客户（有本店预约记录或已持本店次卡）；无卡客户将自动建卡（售卡）'),
  ('pass.topUpTimesHint', 'merchant:pass', '1-999；次卡仅适用于洗护服务'),
  ('prod.createCta', 'merchant:products', '＋ 新增商品'),
  ('prod.emptyTitle', 'merchant:products', '货架空空，去上架第一件商品'),
  ('prod.sub', 'merchant:products', '在售 {on} · 已下架 {off} · 低库存 {low}'),
  ('prod.subFallback', 'merchant:products', '门店商品库存、价格与上下架'),
  ('prod.title', 'merchant:products', '商品'),
  ('rules.caliberNote', 'merchant:rules', '小字口径：规则保存即生效；新规只约束生效后的单，不回溯历史月份与已快照数据。本页仅店主可见可改，每次修改全留痕。'),
  ('rules.confirmDanger', 'merchant:rules', '危险操作：保存后立即生效，{warn}。新规只约束生效后的单，不回溯历史月份与已快照数据。'),
  ('rules.confirmHint', 'merchant:rules', '防误触：口令与按钮双重确认'),
  ('rules.confirmPhrase', 'merchant:rules', '确认保存'),
  ('rules.confirmTitle', 'merchant:rules', '确认保存规则修改'),
  ('rules.discountHint', 'merchant:rules', '按百分比填写：88 折 = 88%'),
  ('rules.errorHint', 'merchant:rules', '仅店主可读取规则配置；请确认登录态后重试'),
  ('rules.guideHint', 'merchant:rules', '提成与 XP 参数的调整入口只对店主开放。'),
  ('rules.guideTitle', 'merchant:rules', '规则配置仅店主可用'),
  ('rules.noticeDuration', 'merchant:rules', '占位待供给——当前为引擎占位值照转，老板完整供给表到后在此直接改值，保存即生效、不回溯既有单据。'),
  ('rules.noticeMemberPlans', 'merchant:rules', '档位/价格/回馈金比例/服务折扣/多宠规则老板可调，保存即生效、新规只管新单（不回溯既有会员与单据）。'),
  ('rules.noticeRefund', 'merchant:rules', '店长可办退款的累计阈值（超过须店主审批）与超阈值留口开关（默认关=维持硬拒）。保存即生效、只管新单不回溯；开关属流程留口，改动前先与产品侧对齐口径。'),
  ('rules.pageSub', 'merchant:rules', '提成与 XP 全参数 · 页面可改 · 保存即生效 · 每次修改留痕版本化'),
  ('rules.pageTitle', 'merchant:rules', '规则配置管理'),
  ('rules.splitNote', 'merchant:rules', '合计须为 100%'),
  ('rules.versionsAside', 'merchant:rules', '谁 / 何时 / 前后值（最近 20 条）'),
  ('rules.versionsEmpty', 'merchant:rules', '暂无修改记录（当前为初始种子版本）'),
  ('rules.warnCommission', 'merchant:rules', '影响全员提成与绩效核算'),
  ('rules.warnDuration', 'merchant:rules', '影响预约引擎时长与可约槽位'),
  ('rules.warnMemberPlans', 'merchant:rules', '影响会员档权益与新售卡结算'),
  ('rules.warnRefund', 'merchant:rules', '影响退款审批闸门与超阈值口径'),
  ('rules.warnXp', 'merchant:rules', '影响全员 XP 核算'),
  ('set.addrHint', 'merchant:settings', 'listNearby 距离粗排之用'),
  ('set.autoAcceptHint', 'merchant:settings', 'S4 口径 · 默认开（无开关项，仅口径展示）'),
  ('set.hoursHint', 'merchant:settings', '可约栅格之源'),
  ('set.noStoreHint', 'merchant:settings', '请确认当前账号已完成开店绑定'),
  ('set.noStoreTitle', 'merchant:settings', '未找到门店信息'),
  ('set.notifyAside', 'merchant:settings', '通知偏好仅本机生效（v2 接服务端）'),
  ('set.notifyBoardingHint', 'merchant:settings', '每日 16:00 未打卡提醒员工'),
  ('set.notifyBoardingLabel', 'merchant:settings', '寄养打卡提醒'),
  ('set.notifyCancelHint', 'merchant:settings', '≤4h 申请需审批'),
  ('set.notifyCancelLabel', 'merchant:settings', '取消申请提醒'),
  ('set.notifyNewHint', 'merchant:settings', 'SSE store 频道 · 声音提醒'),
  ('set.notifyNewLabel', 'merchant:settings', '新预约通知'),
  ('set.panelRules', 'merchant:settings', '经营口径'),
  ('set.panelStore', 'merchant:settings', '门店'),
  ('set.servicesEmpty', 'merchant:settings', '还没有服务项，点下方「＋ 新增服务」创建洗护或寄养服务'),
  ('set.servicesHint', 'merchant:settings', '洗护/造型美容/寄养房型（时长引擎之母）'),
  ('set.servicesOffNote', 'merchant:settings', '下架项本次会话内仍列出（可重新上架）；刷新后不再显示（「含下架」列表接口 v2 补齐）'),
  ('set.sub', 'merchant:settings', '门店与经营口径 · 改动即生效（可约/派单联动）'),
  ('set.title', 'merchant:settings', '设置'),
  ('staff.editRoleHint', 'merchant:staff', '前台负责扫码核销与接待；美容师负责服务执行（无核销入口）'),
  ('staff.editSkillNote', 'merchant:staff', '技能标签暂为只读（S4 派单批开放编辑）；排班请点员工行右侧的排班摘要编辑。'),
  ('staff.editSuspendNote', 'merchant:staff', '停用后该员工立即无法操作员工端（历史业绩保留）'),
  ('staff.empty', 'merchant:staff', '还没有员工'),
  ('staff.emptyCta', 'merchant:staff', '去邀请第一位员工'),
  ('staff.inviteCodeOnce', 'merchant:staff', '明文仅此一次展示，关闭本弹层后无法再次查看，请立即复制并转交员工。'),
  ('staff.inviteCta', 'merchant:staff', '＋ 邀请员工'),
  ('staff.inviteGuide', 'merchant:staff', '员工在员工端登录后输入邀请码即可绑定本店。邀请码 24 小时内有效、仅可使用一次。'),
  ('staff.inviteNameHint', 'merchant:staff', '邀请成功后将以该花名登记员工档案'),
  ('staff.panelAside', 'merchant:staff', '排班=自动派单与可约判定之源'),
  ('staff.scheduleNote', 'merchant:staff', '每天最多 {n} 个时段；设为「休息」的当天不排班。'),
  ('staff.sub', 'merchant:staff', '在职 {a} · 美容师 {b} · 前台 {c} · 自动派单按排班+负荷（S4）'),
  ('staff.suspendedNote', 'merchant:staff', '停职中不可派单/核销'),
  ('staff.title', 'merchant:staff', '员工'),
  ('ntf.allTab', 'notify', '全部'),
  ('ntf.catAccount', 'notify', '账户'),
  ('ntf.catMarketing', 'notify', '活动'),
  ('ntf.catService', 'notify', '服务'),
  ('ntf.catTrade', 'notify', '交易'),
  ('ntf.delete', 'notify', '删除'),
  ('ntf.deleteConfirm', 'notify', '再点一次确认删除'),
  ('ntf.deleted', 'notify', '已删除'),
  ('ntf.emptyBody', 'notify', '预约进度、退款结果、证书报告都会在这里告诉你'),
  ('ntf.emptyCta', 'notify', '去首页逛逛 ›'),
  ('ntf.emptyTitle', 'notify', '还没有消息'),
  ('ntf.loadFail', 'notify', '消息加载失败'),
  ('ntf.loadMore', 'notify', '加载更多'),
  ('ntf.mandatoryDesc', 'notify', '预约进度、退款结果、证书报告、账号安全——不可关闭'),
  ('ntf.mandatoryLabel', 'notify', '交易 / 服务 / 账户通知'),
  ('ntf.mandatoryNote', 'notify', '不可关闭'),
  ('ntf.markAllRead', 'notify', '全部已读'),
  ('ntf.marketingDesc', 'notify', '会员日、回馈金到账提醒、门店活动'),
  ('ntf.marketingLabel', 'notify', '活动与优惠'),
  ('ntf.offToast', 'notify', '已关闭活动通知'),
  ('ntf.onToast', 'notify', '已开启活动通知'),
  ('ntf.prefsHint', 'notify', '营销与活动通知可关闭；交易、服务、账户通知为保障服务履约不可关闭'),
  ('ntf.prefsTitle', 'notify', '订阅管理'),
  ('ntf.retry', 'notify', '重试'),
  ('ntf.title', 'notify', '消息'),
  ('ntf.unreadTab', 'notify', '未读'),
  ('agreement.member_service', 'pay', '《会员服务协议》'),
  ('agreement.no_auto_renew', 'pay', '《到期不自动续费告知》'),
  ('agreement.not_prepaid', 'pay', '《年费≠储值明示》'),
  ('checkout.agreeLabel', 'pay', '我已阅读并同意'),
  ('checkout.agreementGotIt', 'pay', '知道了'),
  ('checkout.agreementSheetNote', 'pay', '版本 {version}'),
  ('checkout.agreeMissing', 'pay', '三份协议全部勾选后才能去支付'),
  ('checkout.agreeTitle', 'pay', '开通前请阅读并勾选'),
  ('checkout.alreadyBody', 'pay', '有效期至 {date}。续费或升级请到店收银台办理，线上换档将于后续批次开放。'),
  ('checkout.alreadyBodyFree', 'pay', '免费档永久有效。升级付费档享回馈金与服务折扣，请到店收银台办理。'),
  ('checkout.alreadyCta', 'pay', '去会员中心 ›'),
  ('checkout.alreadyTitle', 'pay', '你已是会员'),
  ('checkout.amountExtra', 'pay', '多宠附加'),
  ('checkout.amountPlan', 'pay', '档价（一年）'),
  ('checkout.amountTitle', 'pay', '金额明细'),
  ('checkout.amountTotal', 'pay', '应付'),
  ('checkout.channelOffBody', 'pay', '请到店收银台办理开通（现金/微信/支付宝）；线上通道恢复后本页自动开放。'),
  ('checkout.channelOffCta', 'pay', '回开通页 ›'),
  ('checkout.channelOffTitle', 'pay', '线上支付通道维护中'),
  ('checkout.createFail', 'pay', '支付单创建失败，请稍后再试'),
  ('checkout.freePlanBody', 'pay', '微光档一键开通即可，无需进入支付流程。'),
  ('checkout.freePlanCta', 'pay', '去一键开通 ›'),
  ('checkout.freePlanTitle', 'pay', '免费档无需支付'),
  ('checkout.headNo', 'pay', 'PHILIA PAY'),
  ('checkout.missingPlanBody', 'pay', '请先到开通页选择档位，再进入确认订单。'),
  ('checkout.missingPlanCta', 'pay', '去选档 ›'),
  ('checkout.missingPlanTitle', 'pay', '缺少档位信息'),
  ('checkout.payCta', 'pay', '去支付 ¥{amount}'),
  ('checkout.petCountLabel', 'pay', '覆盖毛孩子'),
  ('checkout.petCountValue', 'pay', '{n} 只'),
  ('checkout.petExtra', 'pay', '多宠附加 ¥{price}/只/年 ×{n}'),
  ('checkout.petIncludedNote', 'pay', '本档含 {n} 只 · 第 {from} 只起按 +¥{price}/只/年 计'),
  ('checkout.petMinus', 'pay', '减少一只'),
  ('checkout.petPlus', 'pay', '增加一只'),
  ('checkout.planLabel', 'pay', '开通档位'),
  ('checkout.planPriceYear', 'pay', '¥{price}/年'),
  ('checkout.pushLabel', 'pay', '确认订单 · CHECKOUT'),
  ('checkout.quoteFail', 'pay', '价格试算失败，请重试'),
  ('checkout.submitting', 'pay', '正在创建支付单…'),
  ('checkout.timeoutNotice', 'pay', '请在 {minutes} 分钟内完成支付，超时订单自动关闭'),
  ('checkout.title', 'pay', '确认订单'),
  ('checkout.validity', 'pay', '有效期 {days} 天 · 到期不自动续费'),
  ('mock.watermark', 'pay', '内测通道 · 演示支付，不会真实扣款'),
  ('payStatus.closed', 'pay', '已关闭'),
  ('payStatus.created', 'pay', '创建中'),
  ('payStatus.failed', 'pay', '支付失败'),
  ('payStatus.paid', 'pay', '已支付'),
  ('payStatus.paying', 'pay', '待支付'),
  ('reconcile.btn', 'pay', '对账补开'),
  ('reconcile.doing', 'pay', '对账中…'),
  ('reconcile.empty1', 'pay', '你还没有任何线上支付单。'),
  ('reconcile.empty2', 'pay', '从开通页选择档位并确认订单后，支付单会出现在这里。'),
  ('reconcile.empty3', 'pay', '已完成支付但会员未开通时，回到本页点「对账补开」即可自助补开。'),
  ('reconcile.emptyCta', 'pay', '去开通会员 ›'),
  ('reconcile.emptyTitle', 'pay', '暂无支付单'),
  ('reconcile.fail', 'pay', '对账失败，请稍后再试'),
  ('reconcile.hint', 'pay', '已完成支付但会员未开通时，在下方找到对应支付单点「对账补开」，系统自动核对通道结果并补开。'),
  ('reconcile.listTitle', 'pay', '我的支付单'),
  ('reconcile.loadFail', 'pay', '支付单列表加载失败'),
  ('reconcile.pushLabel', 'pay', '自助对账 · RECONCILE'),
  ('reconcile.success', 'pay', '已补开成功'),
  ('reconcile.title', 'pay', '付了没开？'),
  ('state.amountLabel', 'pay', '应付金额'),
  ('state.closedHint', 'pay', '超时未支付订单自动关闭，未产生扣款；可重新下单。'),
  ('state.closedTitle', 'pay', '订单已超时关闭'),
  ('state.createdBody', 'pay', '正在向支付通道下单，请稍候片刻；本页每 2 秒自动刷新。'),
  ('state.createdTitle', 'pay', '支付单创建中'),
  ('state.failedTitle', 'pay', '支付未完成'),
  ('state.failHint', 'pay', '本次支付未成功，未产生扣款；可重新发起支付。'),
  ('state.loadFail', 'pay', '支付状态加载失败'),
  ('state.mockDemoLabel', 'pay', '内测演示控制'),
  ('state.mockDrop', 'pay', '模拟掉单'),
  ('state.mockFail', 'pay', '模拟失败'),
  ('state.mockFailToast', 'pay', '演示指令发送失败，请重试'),
  ('state.mockSuccess', 'pay', '模拟支付成功'),
  ('state.mockTimeout', 'pay', '模拟超时'),
  ('state.mockWorking', 'pay', '演示指令执行中…'),
  ('state.orderNo', 'pay', '支付单号 {payNo}'),
  ('state.paidBody', 'pay', '{planLabel} · 有效期 {days} 天，权益即时生效。'),
  ('state.paidCta', 'pay', '看看会员页 ›'),
  ('state.paidTitle', 'pay', '会员已开通'),
  ('state.payingBody', 'pay', '请在下方内测演示控制区完成演示支付；本页每 2 秒自动刷新支付状态。'),
  ('state.payingTitle', 'pay', '等待支付结果'),
  ('state.planLine', 'pay', '{planLabel} · 覆盖 {n} 只'),
  ('state.pushLabel', 'pay', '收银台 · PAY'),
  ('state.reconcileEntry', 'pay', '付了没开？点这里自助对账 ›'),
  ('state.reorder', 'pay', '重新下单 ›'),
  ('state.retry', 'pay', '重新支付'),
  ('state.retrying', 'pay', '正在重新下单…'),
  ('pets.addCta', 'pets', '新增宠物'),
  ('pets.emptyBody', 'pets', '建立档案后，预约洗护与寄养更省心'),
  ('pets.emptyCta', 'pets', '建立档案'),
  ('pets.emptyTitle', 'pets', '还没有宠物档案'),
  ('pets.historyCount', 'pets', '共 {count} 次'),
  ('pets.historyTitle', 'pets', '洗护史'),
  ('pets.loadFail', 'pets', '宠物档案加载失败'),
  ('pets.rebook', 'pets', '同款再约 ›'),
  ('pets.title', 'pets', '宠物档案'),
  ('pets.vaccineExpired', 'pets', '疫苗已过期 · 寄养前需补种'),
  ('pets.vaccineNone', 'pets', '未登记疫苗'),
  ('pets.vaccineOk', 'pets', '疫苗有效至 {date}'),
  ('pets.vaccineSoon', 'pets', '疫苗 {days} 天后到期 · 寄养需有效期内'),
  ('refund.amountLabel', 'refund', '申请金额'),
  ('refund.appointmentNoBill', 'refund', '该服务单尚未结账，暂不可线上申请退款，如需退款请到店办理'),
  ('refund.backToOrigin', 'refund', '返回原单详情'),
  ('refund.backToRefunds', 'refund', '返回退款列表'),
  ('refund.cancelConfirm', 'refund', '确定撤回这次退款申请？'),
  ('refund.cancelCta', 'refund', '撤回申请'),
  ('refund.cancelDone', 'refund', '退款申请已撤回'),
  ('refund.descPlaceholder', 'refund', '补充说明（选填）'),
  ('refund.detailTitle', 'refund', '退款详情'),
  ('refund.emptyBody', 'refund', '对已完成的服务或商品单，可在详情页申请退款/售后'),
  ('refund.emptyCta', 'refund', '去看看订单 ›'),
  ('refund.emptyTitle', 'refund', '没有退款申请'),
  ('refund.entryCta', 'refund', '退款/售后 ›'),
  ('refund.entryHint', 'refund', '对已结账的服务单可申请退款'),
  ('refund.formTitle', 'refund', '申请退款'),
  ('refund.freeRegretNotice', 'refund', '服务完成 {hours} 小时内申请，全额原路退'),
  ('refund.inflightNotice', 'refund', '本单已有在途的退款申请'),
  ('refund.listTitle', 'refund', '退款/售后'),
  ('refund.loadFail', 'refund', '退款信息加载失败，请检查网络后重试'),
  ('refund.maintainNotice', 'refund', '退款申请通道维护中，请到店办理'),
  ('refund.notFound', 'refund', '申请单不存在或无权查看'),
  ('refund.orderNotRefundable', 'refund', '当前订单状态不可申请退款'),
  ('refund.originNotFound', 'refund', '原单不存在或无权查看'),
  ('refund.originTitle', 'refund', '原单信息'),
  ('refund.originTotalLine', 'refund', '原单'),
  ('refund.partialNotice', 'refund', '支持按行部分退款，按行明细见下'),
  ('refund.photoCta', 'refund', '添加照片'),
  ('refund.progressCta', 'refund', '退款进度 ›'),
  ('refund.reasonLabel', 'refund', '退款原因'),
  ('refund.reasonPlaceholder', 'refund', '请选择退款原因'),
  ('refund.refundableLine', 'refund', '本次可退'),
  ('refund.refundedSoFarLine', 'refund', '已退'),
  ('refund.refundNoLabel', 'refund', '退款单号'),
  ('refund.rejectedLabel', 'refund', '驳回原因'),
  ('refund.requestNoLabel', 'refund', '申请单号'),
  ('refund.slaNotice', 'refund', '门店 {hours} 小时内必复'),
  ('refund.status.cancelled', 'refund', '已撤回'),
  ('refund.status.processing', 'refund', '处理中'),
  ('refund.status.refunding', 'refund', '退款中'),
  ('refund.status.rejected', 'refund', '已驳回'),
  ('refund.status.settled', 'refund', '已到账'),
  ('refund.status.submitted', 'refund', '审核中'),
  ('refund.submitCta', 'refund', '提交申请'),
  ('refund.submitDone', 'refund', '退款申请已提交'),
  ('refund.submitHintNoReason', 'refund', '请先选择退款原因'),
  ('refund.timelineTitle', 'refund', '进度'),
  ('refund.timingBody', 'refund', '原路退回：微信/支付宝 T+{d1}~{d2} 个工作日到账；现金到店退回。'),
  ('refund.timingTitle', 'refund', '退款时效与路径'),
  ('refund.typeRefundOnly', 'refund', '仅退款'),
  ('refund.typeReturnRefund', 'refund', '退货退款'),
  ('refund.viewProgressCta', 'refund', '查看进度 ›'),
  ('refund.voucherHint', 'refund', '有争议请附凭证照片，门店审核更快'),
  ('album.emptyBody', 'serviceloop', '完成洗护服务后，前后对比照会自动收进这里'),
  ('album.emptyCta', 'serviceloop', '去预约洗护'),
  ('album.emptyTitle', 'serviceloop', '相册还是空的'),
  ('album.inProgressNote', 'serviceloop', '进行中 · 已确认 {n} 步'),
  ('album.loadFail', 'serviceloop', '相册加载失败'),
  ('album.meEntrySub', 'serviceloop', '美好瞬间'),
  ('album.meEntryTitle', 'serviceloop', '服务相册'),
  ('album.petFallback', 'serviceloop', '毛孩子'),
  ('album.petsEntry', 'serviceloop', '服务相册 ›'),
  ('album.photoAlt', 'serviceloop', '{pet}服务后照片'),
  ('album.serviceFallback', 'serviceloop', '洗护服务'),
  ('album.shareCopied', 'serviceloop', '链接已复制'),
  ('album.shareCta', 'serviceloop', '分享这份美好'),
  ('album.shareText', 'serviceloop', '{date} 在菲丽亚完成了{service}，看看前后对比！'),
  ('album.shareTitle', 'serviceloop', '{pet}的变美记录'),
  ('album.title', 'serviceloop', '服务相册'),
  ('cert.backList', 'serviceloop', '返回证书列表'),
  ('cert.brandMark', 'serviceloop', 'PHILIA'),
  ('cert.cardTitle', 'serviceloop', '安心证书'),
  ('cert.detailEntry', 'serviceloop', '安心证书 ›'),
  ('cert.emptyBody', 'serviceloop', '完成洗护后，门店会为宝贝生成专属安心证书'),
  ('cert.emptyCta', 'serviceloop', '去看看服务相册'),
  ('cert.emptyTitle', 'serviceloop', '还没有安心证书'),
  ('cert.entryTitle', 'serviceloop', '安心证书'),
  ('cert.listTitle', 'serviceloop', '安心证书'),
  ('cert.loadFail', 'serviceloop', '证书加载失败，请稍后重试'),
  ('cert.stepPhotos', 'serviceloop', '{count} 张'),
  ('cert.traceLine', 'serviceloop', '生成于 {generatedAt} · 送达 {deliveredAt}'),
  ('inv.amountLabel', 'serviceloop', '开票金额'),
  ('inv.amountLine', 'serviceloop', '开票金额=订单实付 {amount}'),
  ('inv.appliedAt', 'serviceloop', '申请于 {time}'),
  ('inv.applyEntry', 'serviceloop', '申请发票 ›'),
  ('inv.applyTitle', 'serviceloop', '申请发票'),
  ('inv.backList', 'serviceloop', '返回发票列表'),
  ('inv.billNo', 'serviceloop', '单号'),
  ('inv.billNotFound', 'serviceloop', '未找到该单据，无法申请开票'),
  ('inv.billSummaryTitle', 'serviceloop', '开票单据'),
  ('inv.cashierUnsupported', 'serviceloop', '收银单开票请到店办理，或联系小棉花协助'),
  ('inv.deliveryEmail', 'serviceloop', '邮箱接收'),
  ('inv.deliveryLabel', 'serviceloop', '送达方式'),
  ('inv.deliveryPickup', 'serviceloop', '到店自取'),
  ('inv.detailTitle', 'serviceloop', '发票详情'),
  ('inv.emailInvalid', 'serviceloop', '邮箱格式不正确'),
  ('inv.emailLabel', 'serviceloop', '接收邮箱'),
  ('inv.emailPlaceholder', 'serviceloop', 'name@example.com'),
  ('inv.emptyBody', 'serviceloop', '已支付的订单都可以申请开发票'),
  ('inv.emptyCta', 'serviceloop', '查看我的预约'),
  ('inv.emptyTitle', 'serviceloop', '还没有发票申请'),
  ('inv.honestLine', 'serviceloop', '提交后门店为您开具'),
  ('inv.issuedAtLine', 'serviceloop', '开具于 {time}'),
  ('inv.issuedNoLabel', 'serviceloop', '发票号'),
  ('inv.kindAppointment', 'serviceloop', '洗护预约'),
  ('inv.kindCashier', 'serviceloop', '门店收银'),
  ('inv.kindOrder', 'serviceloop', '商城订单'),
  ('inv.listTitle', 'serviceloop', '我的发票'),
  ('inv.loadFail', 'serviceloop', '加载失败，请稍后重试'),
  ('inv.progressEntry', 'serviceloop', '发票进度 ›')
)
INSERT INTO `copy_overrides` (`id`,`version`,`rule_key`,`label`,`value_json`,`effective_from`,`active`,`created_by`,`created_at`,`updated_at`)
SELECT 'seedcopy_' || lower(hex(randomblob(8))), 1, s.rule_key, s.label, json_object('text', s.text), unixepoch(), 1, 'system', unixepoch(), unixepoch()
FROM s
WHERE NOT EXISTS (SELECT 1 FROM `copy_overrides` WHERE `rule_key` = s.rule_key AND `active` = 1);
--> statement-breakpoint
WITH s(rule_key, label, text) AS (VALUES
  ('inv.statusIssued', 'serviceloop', '已开具'),
  ('inv.statusSubmitted', 'serviceloop', '申请中'),
  ('inv.store', 'serviceloop', '门店'),
  ('inv.submit', 'serviceloop', '提交申请'),
  ('inv.submitFail', 'serviceloop', '提交失败，请稍后重试'),
  ('inv.submitting', 'serviceloop', '提交中…'),
  ('inv.taxNoLabel', 'serviceloop', '税号'),
  ('inv.taxNoPlaceholder', 'serviceloop', '统一社会信用代码'),
  ('inv.taxNoRequired', 'serviceloop', '企业抬头按税务规定须填税号'),
  ('inv.titleBusiness', 'serviceloop', '企业'),
  ('inv.titleLabel', 'serviceloop', '发票抬头'),
  ('inv.titlePersonal', 'serviceloop', '个人'),
  ('inv.titlePlaceholderBusiness', 'serviceloop', '企业全称'),
  ('inv.titlePlaceholderPersonal', 'serviceloop', '姓名或个人抬头'),
  ('inv.titleRequired', 'serviceloop', '请填写发票抬头'),
  ('inv.titleTypeLabel', 'serviceloop', '抬头类型'),
  ('report.abnormalTitle', 'serviceloop', '异常提示'),
  ('report.detailEntry', 'serviceloop', '美容报告 ›'),
  ('report.loadFail', 'serviceloop', '报告加载失败，请稍后重试'),
  ('report.nextAdviceTitle', 'serviceloop', '下次护理建议'),
  ('report.notRecorded', 'serviceloop', '本次未记录'),
  ('report.promiseLine', 'serviceloop', '美容报告 30 分钟内送达'),
  ('report.statusAbnormal', 'serviceloop', '异常'),
  ('report.statusAttention', 'serviceloop', '注意'),
  ('report.statusNormal', 'serviceloop', '正常'),
  ('report.statusUnrecorded', 'serviceloop', '未记录'),
  ('report.title', 'serviceloop', '美容报告'),
  ('report.traceLine', 'serviceloop', '生成于 {generatedAt} · 送达 {deliveredAt}'),
  ('report.vitalCoat', 'serviceloop', '被毛'),
  ('report.vitalEar', 'serviceloop', '耳朵'),
  ('report.vitalNail', 'serviceloop', '指甲'),
  ('report.vitalSkin', 'serviceloop', '皮肤'),
  ('report.vitalsTitle', 'serviceloop', '本次体征'),
  ('report.vitalWeight', 'serviceloop', '体重'),
  ('ticket.backList', 'serviceloop', '返回工单列表'),
  ('ticket.contactLabel', 'serviceloop', '联系方式'),
  ('ticket.contactPlaceholder', 'serviceloop', '手机号，方便门店回电'),
  ('ticket.descLabel', 'serviceloop', '问题描述'),
  ('ticket.descPlaceholder', 'serviceloop', '发生了什么？说得越细，小棉花越好帮'),
  ('ticket.descRequired', 'serviceloop', '请填写问题描述'),
  ('ticket.detailTitle', 'serviceloop', '工单详情'),
  ('ticket.emptyBody', 'serviceloop', '建议、吐槽或表扬，都可以告诉小棉花'),
  ('ticket.emptyCta', 'serviceloop', '写一封给小棉花'),
  ('ticket.emptyTitle', 'serviceloop', '还没有工单'),
  ('ticket.hoursLine', 'serviceloop', '人工服务时间 {hours}'),
  ('ticket.hoursTitle', 'serviceloop', '客服服务时间'),
  ('ticket.listTitle', 'serviceloop', '小棉花客服'),
  ('ticket.loadFail', 'serviceloop', '工单加载失败，请稍后重试'),
  ('ticket.meEntrySub', 'serviceloop', '建议与吐槽'),
  ('ticket.meEntryTitle', 'serviceloop', '小棉花'),
  ('ticket.newTitle', 'serviceloop', '联系小棉花'),
  ('ticket.photoAdd', 'serviceloop', '上传照片'),
  ('ticket.photoRemove', 'serviceloop', '移除'),
  ('ticket.photosLabel', 'serviceloop', '附图（选传，最多 3 张）'),
  ('ticket.replyTitle', 'serviceloop', '门店回复'),
  ('ticket.statusClosed', 'serviceloop', '已关闭'),
  ('ticket.statusReplied', 'serviceloop', '已回复'),
  ('ticket.statusSubmitted', 'serviceloop', '已提交'),
  ('ticket.storeLabel', 'serviceloop', '相关门店'),
  ('ticket.storeRequired', 'serviceloop', '请选择相关门店'),
  ('ticket.submit', 'serviceloop', '提交给小棉花'),
  ('ticket.submitFail', 'serviceloop', '提交失败，请稍后重试'),
  ('ticket.submitting', 'serviceloop', '提交中…'),
  ('ticket.timelineClosed', 'serviceloop', '工单已关闭'),
  ('ticket.timelineReplied', 'serviceloop', '门店已回复'),
  ('ticket.timelineSubmitted', 'serviceloop', '工单已提交'),
  ('ticket.timelineTitle', 'serviceloop', '处理进度'),
  ('ticket.typeComplaint', 'serviceloop', '要吐槽'),
  ('ticket.typeLabel', 'serviceloop', '类型'),
  ('ticket.typeOther', 'serviceloop', '其他'),
  ('ticket.typePraise', 'serviceloop', '表扬'),
  ('ticket.typeSuggest', 'serviceloop', '提建议'),
  ('ticket.uploadFail', 'serviceloop', '照片上传失败，请重试'),
  ('attendance.fence.noCoord', 'staff:attendance', '门店未配置坐标，本次打卡不校验距离'),
  ('attendance.fence.range', 'staff:attendance', '打卡范围：门店 300 米内'),
  ('attendance.geo.denied', 'staff:attendance', '定位权限被拒绝：请在浏览器设置中允许定位后重试'),
  ('attendance.geo.failed', 'staff:attendance', '定位失败，请检查定位开关后重试'),
  ('attendance.geo.timeout', 'staff:attendance', '定位超时，请到开阔处重试'),
  ('attendance.geo.unsupported', 'staff:attendance', '当前设备不支持定位，请更换设备或联系店长'),
  ('attendance.records.empty', 'staff:attendance', '本月还没有考勤记录——到店后点上方按钮打卡'),
  ('boarding.cancelled.desc', 'staff:boarding', '如有疑问请到商家端查看处理。'),
  ('boarding.cancelled.title', 'staff:boarding', '该预约已取消'),
  ('boarding.cancelRequested.title', 'staff:boarding', '该预约正在取消审核中'),
  ('boarding.checkout.confirmDesc', 'staff:boarding', '退房后预约转入「已完成」；到店付订单请提醒商家在财务页确认收款。'),
  ('boarding.checkout.confirmTitle', 'staff:boarding', '确认办理退房？'),
  ('boarding.completed.banner', 'staff:boarding', '本单已完成退房结算'),
  ('boarding.error.fallbackDesc', 'staff:boarding', '预约不存在或无权查看'),
  ('boarding.error.notBoarding', 'staff:boarding', '该预约不是寄养单'),
  ('boarding.error.title', 'staff:boarding', '无法查看该寄养单'),
  ('boarding.overdue.dueLead', 'staff:boarding', '应于'),
  ('boarding.overdue.dueTail', 'staff:boarding', '退房'),
  ('boarding.overdue.title', 'staff:boarding', '已超期，请提醒商家安排退房'),
  ('boarding.preCheckin.action', 'staff:boarding', '去任务台核销'),
  ('boarding.preCheckin.desc', 'staff:boarding', '请先在任务台扫码或手动核销该预约，核销后才能办理入住登记。'),
  ('boarding.preCheckin.title', 'staff:boarding', '客户还未到店核销'),
  ('exec.report.advice.label', 'staff:execute', '下次建议（选填）'),
  ('exec.report.advice.placeholder', 'staff:execute', '如：两周后建议复查耳道'),
  ('exec.report.delivery', 'staff:execute', '完成后，报告将在 30 分钟内送达家长'),
  ('exec.report.note.placeholder', 'staff:execute', '补充一句情况说明（选填）'),
  ('exec.report.status.abnormal', 'staff:execute', '异常'),
  ('exec.report.status.attention', 'staff:execute', '注意'),
  ('exec.report.status.normal', 'staff:execute', '正常'),
  ('exec.report.title', 'staff:execute', '美容报告（随完成同步家长）'),
  ('exec.report.vital.coat', 'staff:execute', '被毛'),
  ('exec.report.vital.ear', 'staff:execute', '耳朵'),
  ('exec.report.vital.nail', 'staff:execute', '指甲'),
  ('exec.report.vital.skin', 'staff:execute', '皮肤'),
  ('exec.report.vital.weight', 'staff:execute', '体重'),
  ('exec.report.weight.empty', 'staff:execute', '档案未登记'),
  ('execute.guide.boarding.action', 'staff:execute', '前往入住登记'),
  ('execute.guide.boarding.desc', 'staff:execute', '寄养服务请走入住登记流程'),
  ('execute.guide.boarding.title', 'staff:execute', '这是寄养预约'),
  ('execute.guide.cancelled.desc', 'staff:execute', '如有疑问请联系商家'),
  ('execute.guide.cancelled.title', 'staff:execute', '预约已取消'),
  ('execute.guide.cancelRequested.title', 'staff:execute', '取消审核中'),
  ('execute.guide.completed.desc', 'staff:execute', '该预约的六步服务已全部完成'),
  ('execute.guide.completed.title', 'staff:execute', '服务已完成'),
  ('execute.guide.forbidden.desc', 'staff:execute', '该预约未指派给你，或不属于本店（非本人单）'),
  ('execute.guide.forbidden.title', 'staff:execute', '无法执行该预约'),
  ('execute.guide.loadFailed.title', 'staff:execute', '加载失败'),
  ('execute.guide.noCurrent.action', 'staff:execute', '回到任务台'),
  ('execute.guide.noCurrent.desc', 'staff:execute', '到任务台核销客户预约码后，即可开始服务执行'),
  ('execute.guide.noCurrent.title', 'staff:execute', '当前没有进行中的服务'),
  ('execute.guide.notCheckedIn.desc', 'staff:execute', '请先在任务台核销到店，再开始服务'),
  ('execute.guide.notCheckedIn.title', 'staff:execute', '该预约尚未核销'),
  ('execute.guide.notFound.desc', 'staff:execute', '可能已被取消或删除'),
  ('execute.guide.notFound.title', 'staff:execute', '预约不存在'),
  ('execute.guide.notInitialized.desc', 'staff:execute', '请重新核销或联系商家处理'),
  ('execute.guide.notInitialized.title', 'staff:execute', '六步服务流未初始化'),
  ('history.empty', 'staff:history', '还没有历史单——第一单完成后会出现在这里'),
  ('inventory.count.blindNote', 'staff:inventory', '本单为盲盘，不展示账面数。'),
  ('inventory.count.counted.desc', 'staff:inventory', '确认前库存不变；如被退回会出现在待办里可重盘。'),
  ('inventory.count.counted.title', 'staff:inventory', '已提交，待店长确认后才入账'),
  ('inventory.count.guide', 'staff:inventory', '逐项填写实盘数量后提交；提交后待店长确认才入账，确认前库存不变。'),
  ('inventory.count.missing', 'staff:inventory', '该盘点单不在你的待办中——可能已确认入账或已处理'),
  ('inventory.count.noItems', 'staff:inventory', '这张单没有盘点行项，请联系店长确认派单范围'),
  ('inventory.count.rejected.desc', 'staff:inventory', '店长退回了这张盘点单，请核对后修改实盘数重新提交。'),
  ('inventory.count.rejected.title', 'staff:inventory', '已退回重盘'),
  ('inventory.expiry.empty', 'staff:inventory', '30 天内没有临期安心包，继续保持'),
  ('inventory.expiry.note', 'staff:inventory', '临期/过期安心包请走回收登记流程处置，本页仅作提醒（只读）。'),
  ('inventory.tasks.empty', 'staff:inventory', '暂无待办盘点单——店长派单后会出现在这里'),
  ('login.accounts.title', 'staff:login', '选择员工账号'),
  ('login.agreement', 'staff:login', '登录即同意《员工内测协议》与《服务影像记录规范》'),
  ('login.gate.hint', 'staff:login', '输入口令后加载可登录账号；无口令或口令错误将无法登录。'),
  ('login.gate.required', 'staff:login', '需先输入内测口令'),
  ('login.gate.title', 'staff:login', '内测口令'),
  ('login.manifesto.line1', 'staff:login', '照顾好每一个'),
  ('login.manifesto.line2', 'staff:login', '被托付的小生命'),
  ('login.seed.empty', 'staff:login', '未拉到员工种子用户，请重跑 server 的 db:seed，或手动输入 userId'),
  ('login.seed.loadFailed', 'staff:login', '种子用户拉取失败（{error}），请确认 server 已启动，或手动输入 userId'),
  ('login.seed.tip', 'staff:login', '提示：dev-login 仅允许种子用户（kimi_id 以 seed_ 前缀），会话 cookie 有效期 7 天。
非员工账号登录后会被引导回本页切换。'),
  ('login.storeLine', 'staff:login', '菲丽亚宠物·示例店 · 员工内测通道'),
  ('login.wordmark', 'staff:login', 'PHILIA · 员工端'),
  ('manager.attendance.empty', 'staff:manager', '暂无待审批与防代打标记'),
  ('manager.cancel.empty', 'staff:manager', '暂无待审核的取消申请'),
  ('manager.guide.desc', 'staff:manager', '当前账号暂无店长权限。考勤/取消/盘点审批与日结确认请改用商家端，或联系店主开通店长角色。'),
  ('manager.guide.title', 'staff:manager', '店长视图仅店长与老板可用'),
  ('manager.inventory.countedEmpty', 'staff:manager', '暂无待确认盘点单'),
  ('manager.inventory.countedNote', 'staff:manager', '待确认（店员已录入实盘）'),
  ('manager.inventory.postedEmpty', 'staff:manager', '暂无已入账盘点单'),
  ('manager.movements.empty', 'staff:manager', '暂无库存流水'),
  ('manager.refund.draftNote', 'staff:manager', '超阈值/涉储值申请须店主审批（驳回权仅店主）'),
  ('manager.refund.empty', 'staff:manager', '暂无退款单'),
  ('manager.refund.listNote', 'staff:manager', '本店退款单（最近 20 条）· 发起入口在商家端收银台'),
  ('manager.refund.pendingNote', 'staff:manager', '实退待办（执行超 24 小时未登记）'),
  ('manager.reviews.empty', 'staff:manager', '暂无 ≤2 星差评'),
  ('me.help.flowBody', 'staff:me', '客户到店出示预约码 → 前台扫码（无摄像头走手动 6 位码）→ 核销成功自动开单；寄养单核销后办理入住登记。'),
  ('me.help.flowTitle', 'staff:me', '核销流程'),
  ('me.help.specBody', 'staff:me', '消毒 1–3 张 · 预检 2–6 张 · 洗护 3–9 张 · 精修 2–6 张 · 前后对比各 1 张；过程照实时同步家长，张数达标才能确认翻步。'),
  ('me.help.specTitle', 'staff:me', '六步影像规范'),
  ('me.myReviews', 'staff:me', '我的评价'),
  ('me.myReviewsSub', 'staff:me', '本人收到的客户评价'),
  ('me.reviewSummary', 'staff:me', '评价总览'),
  ('me.reviewSummaryAvg', 'staff:me', '均分'),
  ('me.reviewSummaryLead', 'staff:me', '近 30 天口径看历史页 · 本月已评'),
  ('me.reviewSummaryUnit', 'staff:me', '条'),
  ('me.settings.sync', 'staff:me', '实时同步：派单/改期/取消即时推送（SSE 长连接，断线自动重连 + 60s 轮询兜底）。'),
  ('pay.deductions.empty', 'staff:pay', '本月无扣减'),
  ('pay.deductions.note', 'staff:pay', '扣减只扣绩效，不扣提成'),
  ('pay.empty.default', 'staff:pay', '本月暂无此类计提单'),
  ('pay.empty.product', 'staff:pay', '本月暂无商品计提单'),
  ('pay.empty.service', 'staff:pay', '本月暂无服务计提单'),
  ('pay.footer.lead', 'staff:pay', '仅本人可见 · 规则版本'),
  ('pay.history.empty', 'staff:pay', '暂无历史快照——每月结算后自动生成'),
  ('pay.history.note', 'staff:pay', '已快照月份按冻结口径展示，冲减差额进当月调整项'),
  ('pay.perf.estimateLead', 'staff:pay', '预估绩效（基数 ×'),
  ('pay.perf.estimateTail', 'staff:pay', '× 系数，季度发放）'),
  ('pay.perf.noGrade', 'staff:pay', '本季尚未评级，评级后核算应付绩效'),
  ('pay.pool.frontdesk', 'staff:pay', '前台绩效池（本人接待归属洗美营收·门市价）'),
  ('pay.pool.groomer', 'staff:pay', '美容师绩效池（本人操作洗美营收·门市价）'),
  ('pay.probation.note', 'staff:pay', '试用期：商品/售卡类提成 ×50%'),
  ('reviews.empty', 'staff:reviews', '还没有收到客户评价——服务完成后客户可在预约详情留言，好评会同时长 XP'),
  ('reviews.footer', 'staff:reviews', '仅本人可见 · 好评 +XP，≤2 星 −8（扣分不扣款）'),
  ('reviews.summary.lead', 'staff:reviews', '已加载'),
  ('reviews.summary.tail', 'staff:reviews', '条评价的平均分'),
  ('today.frontdesk.empty', 'staff:today', '今天全店无预约——等自动接单，或把预约页分享给老客'),
  ('today.frontdesk.scanHint', 'staff:today', '无摄像头环境走「手动输入 6 位核销码」'),
  ('today.groomer.empty', 'staff:today', '今天没有派给你的单——休息，或去前台看看有没有要帮忙的'),
  ('today.noRole.bodyGuide', 'staff:today', '请联系店主在商家端「员工管理」邀请入职并分配角色（前台 / 美容师）后再使用。'),
  ('today.noRole.bodyLead', 'staff:today', '当前账号「{name}」还没有绑定门店员工身份。'),
  ('today.noRole.title', 'staff:today', '还未分配员工角色'),
  ('xp.board.note', 'staff:xp', '榜单只显示前三与你相邻的名次'),
  ('xp.events.empty', 'staff:xp', '还没有经验记录——打卡、完成服务、收获好评都会长经验'),
  ('xp.footer', 'staff:xp', '每月 1 日段位结算 · 经验累计不清零'),
  ('xp.level.gapLead', 'staff:xp', '距'),
  ('xp.level.gapMid', 'staff:xp', '还差'),
  ('xp.level.gapTail', 'staff:xp', '经验'),
  ('xp.level.max', 'staff:xp', '已达最高段位'),
  ('xp.retention.lead', 'staff:xp', '保级线：月增量'),
  ('xp.retention.mid', 'staff:xp', '· 本月已增'),
  ('xp.retention.none', 'staff:xp', '当前段位无保级要求，经验累计不清零'),
  ('xp.today.capLead', 'staff:xp', '日上限'),
  ('xp.today.capTail', 'staff:xp', '，超出部分不计分'),
  ('xp.today.fullBadge', 'staff:xp', '今日经验已满'),
  ('xp.today.fullHint', 'staff:xp', '今日经验已满，明日 0 点重置')
)
INSERT INTO `copy_overrides` (`id`,`version`,`rule_key`,`label`,`value_json`,`effective_from`,`active`,`created_by`,`created_at`,`updated_at`)
SELECT 'seedcopy_' || lower(hex(randomblob(8))), 1, s.rule_key, s.label, json_object('text', s.text), unixepoch(), 1, 'system', unixepoch(), unixepoch()
FROM s
WHERE NOT EXISTS (SELECT 1 FROM `copy_overrides` WHERE `rule_key` = s.rule_key AND `active` = 1);
