-- 员工端骨架整建批片 2：copy_overrides 增量种子（排班/考勤新增 133 键随批注册；片 B 纪律=新键随批注册进端口表）
-- 幂等：rule_key active 行 NOT EXISTS 守卫（存量库只补差、重放零副作用）；created_by='system'
-- （迁移执行器 PRAGMA foreign_keys=OFF，惯例见 migrate.ts 头注）。
-- 生成件=scripts/gen-copy-overrides-seed.mts 重跑产物（server/src/db/copySeedRows.ts 同帧；总量 1827 键/41 域）。
-- 撞键裁决：merchant/staff 两端 6 键同名异文 → staff 侧改键 sched.myweek.* / sched.swap.openPool（端口键全局唯一纪律）。
WITH s(rule_key, label, text) AS (VALUES
  ('sched.block.draft', 'merchant:schedule', '未发布'),
  ('sched.block.dragHint', 'merchant:schedule', '拖动班次块到其他格子即可调班'),
  ('sched.block.manual', 'merchant:schedule', '手动'),
  ('sched.block.published', 'merchant:schedule', '已发布'),
  ('sched.block.template', 'merchant:schedule', '模板'),
  ('sched.common.loadFail', 'merchant:schedule', '数据加载失败，请检查网络后重试'),
  ('sched.common.retry', 'merchant:schedule', '重新加载'),
  ('sched.drop.done', 'merchant:schedule', '已调整并留痕'),
  ('sched.drop.note', 'merchant:schedule', '拖拽调整留痕'),
  ('sched.gen.done', 'merchant:schedule', '生成完成：新增 {created} 班、跳过 {skipped} 班'),
  ('sched.gen.generateCta', 'merchant:schedule', '按模板生成本周'),
  ('sched.gen.generating', 'merchant:schedule', '生成中…'),
  ('sched.gen.publishCta', 'merchant:schedule', '发布本周班表'),
  ('sched.gen.published', 'merchant:schedule', '发布完成：新发布 {n} 班（幂等，已发布不重发）'),
  ('sched.gen.publishing', 'merchant:schedule', '发布中…'),
  ('sched.gen.publishNote', 'merchant:schedule', '发布后员工端可见并收到推送；重复发布幂等'),
  ('sched.guideHint', 'merchant:schedule', '排班、发布与换班审批属管理层动作；店员账号的工作面是收银台。'),
  ('sched.guideTitle', 'merchant:schedule', '排班管理由店长或店主处理'),
  ('sched.import.aside', 'merchant:schedule', '列名=员工/日期/开始/结束；先预览对账再落库'),
  ('sched.import.colDate', 'merchant:schedule', '日期'),
  ('sched.import.colLine', 'merchant:schedule', '行'),
  ('sched.import.colRange', 'merchant:schedule', '时段'),
  ('sched.import.colResult', 'merchant:schedule', '结果'),
  ('sched.import.colStaff', 'merchant:schedule', '员工'),
  ('sched.import.empty', 'merchant:schedule', '请先粘贴 CSV 文本'),
  ('sched.import.executeCta', 'merchant:schedule', '确认导入'),
  ('sched.import.executed', 'merchant:schedule', '导入完成：落库 {inserted} 行、跳过 {skipped} 行'),
  ('sched.import.placeholder', 'merchant:schedule', '粘贴 CSV 文本，如：
员工,日期,开始,结束
小王,2026-10-05,10:00,19:00'),
  ('sched.import.previewCta', 'merchant:schedule', '预览对账'),
  ('sched.import.rowOk', 'merchant:schedule', '可导入'),
  ('sched.import.summary', 'merchant:schedule', '可导入 {ok} 行 · 失败 {fail} 行'),
  ('sched.import.title', 'merchant:schedule', 'CSV 批量导入'),
  ('sched.pageSub', 'merchant:schedule', '周视图拖拽排班 · 模板生成 · 发布推送 · 换班审批 · 批量导入'),
  ('sched.pageTitle', 'merchant:schedule', '排班管理'),
  ('sched.skill.aside', 'merchant:schedule', '点选切换即保存；标签集由配置端口供给'),
  ('sched.skill.empty', 'merchant:schedule', '暂无在职员工'),
  ('sched.skill.noTags', 'merchant:schedule', '标签集为空（配置端口 staff_skill_tags 未供给）'),
  ('sched.skill.saved', 'merchant:schedule', '技能标签已更新'),
  ('sched.skill.title', 'merchant:schedule', '技能标签'),
  ('sched.swap.approve', 'merchant:schedule', '批准'),
  ('sched.swap.aside', 'merchant:schedule', '批准后班次换挂接手人；未认领前责任归原人'),
  ('sched.swap.empty', 'merchant:schedule', '暂无待审批的换班申请'),
  ('sched.swap.noQueue', 'merchant:schedule', '换班队列读口（swapQueue）server 端未透出，审批区待接上；员工发起换班后可在此批准/驳回。'),
  ('sched.swap.notePh', 'merchant:schedule', '审批备注（驳回必填）'),
  ('sched.swap.noteRequired', 'merchant:schedule', '驳回换班须填写备注'),
  ('sched.swap.openTarget', 'merchant:schedule', '开放认领'),
  ('sched.swap.reject', 'merchant:schedule', '驳回'),
  ('sched.swap.resolved', 'merchant:schedule', '已处理该换班申请'),
  ('sched.swap.title', 'merchant:schedule', '换班审批'),
  ('sched.tpl.aside', 'merchant:schedule', '模板按周生成排班；停用后不再参与生成'),
  ('sched.tpl.days', 'merchant:schedule', '适用周日'),
  ('sched.tpl.deactivate', 'merchant:schedule', '停用'),
  ('sched.tpl.deactivated', 'merchant:schedule', '模板已停用'),
  ('sched.tpl.empty', 'merchant:schedule', '暂无模板；新增后可一键生成整周排班'),
  ('sched.tpl.invalid', 'merchant:schedule', '请填齐班次名与起止时间，且至少选一天'),
  ('sched.tpl.namePh', 'merchant:schedule', '班次名（如 早班）'),
  ('sched.tpl.saveCta', 'merchant:schedule', '保存模板'),
  ('sched.tpl.saved', 'merchant:schedule', '模板已保存'),
  ('sched.tpl.title', 'merchant:schedule', '班次模板'),
  ('sched.week.draft', 'merchant:schedule', '本周未发布'),
  ('sched.week.empty', 'merchant:schedule', '本店暂无在职员工'),
  ('sched.week.next', 'merchant:schedule', '下一周 ›'),
  ('sched.week.prev', 'merchant:schedule', '‹ 上一周'),
  ('sched.week.published', 'merchant:schedule', '本周已发布'),
  ('sched.week.staffCol', 'merchant:schedule', '员工 \ 日期'),
  ('sched.week.this', 'merchant:schedule', '本周'),
  ('sched.wifi.pending', 'merchant:schedule', 'BSSID 白名单由考勤批提供端口页（attendance_wifi_bssids），本区暂为只读注记，端点落地后接上。'),
  ('sched.wifi.title', 'merchant:schedule', 'WiFi 打卡白名单'),
  ('attendance.appeal.cta', 'staff:attendance', '申诉'),
  ('attendance.appeal.placeholder', 'staff:attendance', '请填写申诉原因（必填）'),
  ('attendance.appeal.submit', 'staff:attendance', '提交申诉'),
  ('attendance.appeal.title', 'staff:attendance', '考勤申诉'),
  ('attendance.appeal.toast', 'staff:attendance', '申诉已提交，待店长处理'),
  ('attendance.confirm.cta', 'staff:attendance', '确认今日考勤'),
  ('attendance.confirm.done', 'staff:attendance', '今日考勤已确认'),
  ('attendance.confirm.toast', 'staff:attendance', '已确认今日考勤'),
  ('attendance.confirmed.chip', 'staff:attendance', '已确认'),
  ('attendance.field.ready', 'staff:attendance', '照片已上传，点上方打卡按钮完成外勤打卡'),
  ('attendance.field.tip', 'staff:attendance', '当前在打卡范围外：外勤打卡需上传现场照片，提交后待店长确认'),
  ('attendance.field.upload', 'staff:attendance', '上传现场照片'),
  ('attendance.field.uploading', 'staff:attendance', '照片上传中…'),
  ('attendance.offline.banner', 'staff:attendance', '断网暂存 {count} 条打卡，恢复网络后自动补传'),
  ('attendance.offline.saved', 'staff:attendance', '网络异常，本次打卡已暂存，恢复网络后自动补传'),
  ('attendance.source.field', 'staff:attendance', '外勤'),
  ('attendance.source.offline', 'staff:attendance', '补传'),
  ('attendance.today.detail', 'staff:attendance', '今日打卡明细'),
  ('attendance.wifi.manual', 'staff:attendance', '网页版无法自动读取 WiFi，请手动选择当前连接的门店 WiFi（选中所连 WiFi 后到岗打卡免定位围栏）'),
  ('attendance.wifi.none', 'staff:attendance', '不使用 WiFi 打卡'),
  ('attendance.wifi.title', 'staff:attendance', '门店 WiFi'),
  ('sched.avail.aside', 'staff:schedule', '填每周可上班时段，店长排班会参考'),
  ('sched.avail.empty', 'staff:schedule', '还没有填过可用时间'),
  ('sched.avail.invalid', 'staff:schedule', '请选择周日并填对起止时间'),
  ('sched.avail.notePh', 'staff:schedule', '备注（可空，如 只能晚班）'),
  ('sched.avail.saveCta', 'staff:schedule', '保存可用时间'),
  ('sched.avail.saved', 'staff:schedule', '可用时间已保存'),
  ('sched.avail.title', 'staff:schedule', '我的可用时间'),
  ('sched.comp.empty', 'staff:schedule', '暂无变动记录'),
  ('sched.comp.entries', 'staff:schedule', '变动流水'),
  ('sched.comp.hours', 'staff:schedule', '{h} 小时'),
  ('sched.comp.title', 'staff:schedule', '调休余额'),
  ('sched.leave.approved', 'staff:schedule', '已通过'),
  ('sched.leave.empty', 'staff:schedule', '还没有申请记录'),
  ('sched.leave.end', 'staff:schedule', '结束日期'),
  ('sched.leave.invalid', 'staff:schedule', '请填齐起止日期与原因'),
  ('sched.leave.kindCompOff', 'staff:schedule', '调休'),
  ('sched.leave.kindLeave', 'staff:schedule', '请假'),
  ('sched.leave.myList', 'staff:schedule', '我的申请'),
  ('sched.leave.pending', 'staff:schedule', '待审批'),
  ('sched.leave.reasonPh', 'staff:schedule', '请写明原因（必填）'),
  ('sched.leave.rejected', 'staff:schedule', '已驳回'),
  ('sched.leave.start', 'staff:schedule', '开始日期'),
  ('sched.leave.submitCta', 'staff:schedule', '提交申请'),
  ('sched.leave.submitted', 'staff:schedule', '已提交，待店长审批'),
  ('sched.leave.submitting', 'staff:schedule', '提交中…'),
  ('sched.leave.title', 'staff:schedule', '请假 / 调休申请'),
  ('sched.meFullLink', 'staff:schedule', '完整排班与换班 ›'),
  ('sched.myweek.draft', 'staff:schedule', '待发布'),
  ('sched.myweek.empty', 'staff:schedule', '本周还没有排班'),
  ('sched.myweek.next', 'staff:schedule', '下周 ›'),
  ('sched.myweek.prev', 'staff:schedule', '‹ 上周'),
  ('sched.myweek.published', 'staff:schedule', '已发布'),
  ('sched.no', 'staff:schedule', 'MY SCHEDULE'),
  ('sched.swap.cancel', 'staff:schedule', '收起'),
  ('sched.swap.cta', 'staff:schedule', '发起换班'),
  ('sched.swap.invalid', 'staff:schedule', '请填写换班理由'),
  ('sched.swap.openPool', 'staff:schedule', '开放认领（不指定）'),
  ('sched.swap.pickTarget', 'staff:schedule', '选择接手同事'),
  ('sched.swap.reasonPh', 'staff:schedule', '换班理由（必填）'),
  ('sched.swap.submitCta', 'staff:schedule', '提交换班申请'),
  ('sched.swap.submitted', 'staff:schedule', '换班申请已提交，待店长审批'),
  ('sched.title', 'staff:schedule', '我的排班'),
  ('sched.week.mine', 'staff:schedule', '我'),
  ('sched.week.rest', 'staff:schedule', '休息')
)
INSERT INTO `copy_overrides` (`id`,`version`,`rule_key`,`label`,`value_json`,`effective_from`,`active`,`created_by`,`created_at`,`updated_at`)
SELECT 'seedcopy_' || lower(hex(randomblob(8))), 1, s.rule_key, s.label, json_object('text', s.text), unixepoch(), 1, 'system', unixepoch(), unixepoch()
FROM s
WHERE NOT EXISTS (SELECT 1 FROM `copy_overrides` WHERE `rule_key` = s.rule_key AND `active` = 1);
