-- 员工端骨架整建批片 3：copy_overrides 增量种子（任务执行/通讯/权限新增 291 键随批注册；片 B 纪律=新键随批注册进端口表）
-- 幂等：rule_key active 行 NOT EXISTS 守卫（存量库只补差、重放零副作用）；created_by='system'
-- （迁移执行器 PRAGMA foreign_keys=OFF，惯例见 migrate.ts 头注）。
-- 生成件=scripts/gen-copy-overrides-seed.mts 重跑产物（server/src/db/copySeedRows.ts 同帧；总量 2118 键/50 域）。
-- 撞键裁决：staff 通知族 ntf.* 与 customer 既有族同键异文 4 条 → staff 侧改前缀 snt.*（端口键全局唯一纪律）。
WITH s(rule_key, label, text) AS (VALUES
  ('ann.common.loadFail', 'merchant:announcements', '数据加载失败，请检查网络后重试'),
  ('ann.common.retry', 'merchant:announcements', '重新加载'),
  ('ann.guideHint', 'merchant:announcements', '发布与回执对账属管理层动作；店员账号的工作面是收银台。'),
  ('ann.guideTitle', 'merchant:announcements', '公告发布由店长或店主处理'),
  ('ann.list.archiveCta', 'merchant:announcements', '撤下'),
  ('ann.list.archived', 'merchant:announcements', '公告已撤下（留痕，员工端不再展示）'),
  ('ann.list.archivedBadge', 'merchant:announcements', '已撤下'),
  ('ann.list.aside', 'merchant:announcements', '新→旧 · 置顶在前 · 撤下为灰态留痕'),
  ('ann.list.empty', 'merchant:announcements', '暂无公告——上方表单发布第一条'),
  ('ann.list.pinnedBadge', 'merchant:announcements', '置顶'),
  ('ann.list.readCount', 'merchant:announcements', '已读 {x}/{y}'),
  ('ann.list.readCountNoTotal', 'merchant:announcements', '已读 {x} 人'),
  ('ann.list.receiptsCta', 'merchant:announcements', '回执 ›'),
  ('ann.list.title', 'merchant:announcements', '公告列表'),
  ('ann.pageSub', 'merchant:announcements', '定向发布 · 已读回执对账 · 撤下留痕'),
  ('ann.pageTitle', 'merchant:announcements', '公告'),
  ('ann.pub.aside', 'merchant:announcements', '发布即推送员工端 · 置顶在前'),
  ('ann.pub.bodyLabel', 'merchant:announcements', '正文'),
  ('ann.pub.bodyPh', 'merchant:announcements', '正文（全员可见口径按定向角色投递）'),
  ('ann.pub.invalid', 'merchant:announcements', '请填齐标题与正文'),
  ('ann.pub.pinnedLabel', 'merchant:announcements', '置顶'),
  ('ann.pub.published', 'merchant:announcements', '公告已发布'),
  ('ann.pub.publishing', 'merchant:announcements', '发布中…'),
  ('ann.pub.submitCta', 'merchant:announcements', '发布'),
  ('ann.pub.targetAll', 'merchant:announcements', '全员'),
  ('ann.pub.targetFrontdesk', 'merchant:announcements', '前台'),
  ('ann.pub.targetGroomer', 'merchant:announcements', '美容师'),
  ('ann.pub.targetLabel', 'merchant:announcements', '定向角色'),
  ('ann.pub.title', 'merchant:announcements', '发布公告'),
  ('ann.pub.titleLabel', 'merchant:announcements', '标题'),
  ('ann.pub.titlePh', 'merchant:announcements', '标题（如：本周六店休盘点）'),
  ('ann.reads.close', 'merchant:announcements', '关闭'),
  ('ann.reads.empty', 'merchant:announcements', '暂无回执数据'),
  ('ann.reads.readCol', 'merchant:announcements', '已读（{n}）'),
  ('ann.reads.title', 'merchant:announcements', '已读回执对账'),
  ('ann.reads.unreadCol', 'merchant:announcements', '未读（{n}）'),
  ('cashier.handoverCashLabel', 'merchant:cashier', '现金'),
  ('cashier.handoverCashPh', 'merchant:cashier', '现金注记（选填，如：备用金 500 已点）'),
  ('cashier.handoverComplaintsLabel', 'merchant:cashier', '客诉'),
  ('cashier.handoverComplaintsPh', 'merchant:cashier', '客诉注记（选填，如：无 / 1 起待跟进）'),
  ('cashier.handoverKeysLabel', 'merchant:cashier', '钥匙'),
  ('cashier.handoverKeysPh', 'merchant:cashier', '钥匙交接注记（选填，如：前门钥匙 2 把已交班）'),
  ('cashier.handoverLogEmpty', 'merchant:cashier', '该班次无交接班留痕'),
  ('cashier.handoverLogFromTo', 'merchant:cashier', '交 {from} → 接 {to}'),
  ('cashier.handoverLogLoadFail', 'merchant:cashier', '交接班日志加载失败'),
  ('cashier.handoverLogNoTo', 'merchant:cashier', '未指定接棒人'),
  ('cashier.handoverLogTitle', 'merchant:cashier', '交接班日志'),
  ('cashier.handoverTitle', 'merchant:cashier', '交接班四节'),
  ('cashier.handoverToLabel', 'merchant:cashier', '接棒人（选填）'),
  ('cashier.handoverToPh', 'merchant:cashier', '不指定接棒人'),
  ('cashier.handoverWashingLabel', 'merchant:cashier', '在洗清单'),
  ('cashier.handoverWashingNote', 'merchant:cashier', '提交闭班时由系统自动快照当前在洗清单，无需手填'),
  ('ops.common.cancel', 'merchant:ops', '取消'),
  ('ops.common.confirm', 'merchant:ops', '确认提交'),
  ('ops.common.loadFail', 'merchant:ops', '数据加载失败，请检查网络后重试'),
  ('ops.common.retry', 'merchant:ops', '重新加载'),
  ('ops.common.submitting', 'merchant:ops', '提交中…'),
  ('ops.guideHint', 'merchant:ops', '问题复检与自检审核属管理层动作；店员账号的工作面是收银台。'),
  ('ops.guideTitle', 'merchant:ops', '运营闭环由店长或店主处理'),
  ('ops.pageSub', 'merchant:ops', '问题闭环 PDCA · 每日自检审核 · 巡检汇总（单店口径）'),
  ('ops.pageTitle', 'merchant:ops', '运营'),
  ('ops.pdca.aside', 'merchant:ops', '提出→整改→复检，复检不通过回到待整改'),
  ('ops.pdca.collapseCta', 'merchant:ops', '收起 ›'),
  ('ops.pdca.empty', 'merchant:ops', '当前筛选无问题单'),
  ('ops.pdca.expandCta', 'merchant:ops', '详情 ›'),
  ('ops.pdca.filterAll', 'merchant:ops', '全部'),
  ('ops.pdca.fixNoteLabel', 'merchant:ops', '整改说明'),
  ('ops.pdca.notePh', 'merchant:ops', '复检备注（必填，留痕）'),
  ('ops.pdca.noteRequired', 'merchant:ops', '复检备注不能为空'),
  ('ops.pdca.recheckDone', 'merchant:ops', '复检结论已登记'),
  ('ops.pdca.recheckFail', 'merchant:ops', '复检不通过'),
  ('ops.pdca.recheckNoteLabel', 'merchant:ops', '复检结论'),
  ('ops.pdca.recheckPass', 'merchant:ops', '复检通过'),
  ('ops.pdca.statusClosed', 'merchant:ops', '已闭环'),
  ('ops.pdca.statusFixing', 'merchant:ops', '整改中'),
  ('ops.pdca.statusOpen', 'merchant:ops', '待整改'),
  ('ops.pdca.statusRecheck', 'merchant:ops', '待复检'),
  ('ops.pdca.timelineTitle', 'merchant:ops', '留痕时间线'),
  ('ops.pdca.title', 'merchant:ops', '问题闭环（PDCA）'),
  ('ops.self.aside', 'merchant:ops', '员工每日自检提交后在此审核；审核意见必填并留痕'),
  ('ops.self.collapseCta', 'merchant:ops', '收起 ›'),
  ('ops.self.empty', 'merchant:ops', '暂无待审核的自检表'),
  ('ops.self.expandCta', 'merchant:ops', '展开自检快照 ›'),
  ('ops.self.filledBy', 'merchant:ops', '填报人 {name}'),
  ('ops.self.itemFailed', 'merchant:ops', '未达标'),
  ('ops.self.itemPassed', 'merchant:ops', '已打点'),
  ('ops.self.notePh', 'merchant:ops', '审核意见（必填，随单留痕）'),
  ('ops.self.noteRequired', 'merchant:ops', '审核意见不能为空'),
  ('ops.self.reviewCta', 'merchant:ops', '审核（写意见）'),
  ('ops.self.reviewDone', 'merchant:ops', '审核意见已登记'),
  ('ops.self.scoreLabel', 'merchant:ops', '得分 {n}'),
  ('ops.self.title', 'merchant:ops', '自检审核'),
  ('ops.sum.aside', 'merchant:ops', '单店口径'),
  ('ops.sum.byCategory', 'merchant:ops', '类目排行（Top）'),
  ('ops.sum.byStatus', 'merchant:ops', '按状态计数'),
  ('ops.sum.closed30d', 'merchant:ops', '近 30 天闭环'),
  ('ops.sum.emptyCategory', 'merchant:ops', '暂无类目数据'),
  ('ops.sum.loadFail', 'merchant:ops', '汇总加载失败，请检查网络后重试'),
  ('ops.sum.storeScopeNote', 'merchant:ops', '本卡为单店口径；跨店排行属开口项，待连锁合批（5 候）后透出。'),
  ('ops.sum.title', 'merchant:ops', '巡检汇总'),
  ('set.entriesAside', 'merchant:settings', '排班 / 公告 / 循环任务模板直达'),
  ('set.entryAnnouncements', 'merchant:settings', '公告'),
  ('set.entryAnnouncementsHint', 'merchant:settings', '定向发布 · 已读回执对账'),
  ('set.entryGo', 'merchant:settings', '进入 ›'),
  ('set.entrySchedules', 'merchant:settings', '排班管理'),
  ('set.entrySchedulesHint', 'merchant:settings', '周视图拖拽排班 · 模板生成 · 换班审批'),
  ('set.entryTasks', 'merchant:settings', '任务模板'),
  ('set.entryTasksHint', 'merchant:settings', '循环任务自管 · 近 7 天落实例'),
  ('set.panelEntries', 'merchant:settings', '管理入口'),
  ('staff.exitCta', 'merchant:staff', '离职交接 ›'),
  ('staff.exitDialogTitle', 'merchant:staff', '离职交接 · {name}'),
  ('staff.exitHandoffKindAppointment', 'merchant:staff', '预约改挂'),
  ('staff.exitHandoffPrevNext', 'merchant:staff', '{prev} → {next}'),
  ('staff.exitHandoffsEmpty', 'merchant:staff', '暂无交接留痕'),
  ('staff.exitHandoffsTitle', 'merchant:staff', '交接留痕'),
  ('staff.exitMemberNote', 'merchant:staff', '会员档案无员工负责人列，不在改挂范围（口径明面）。'),
  ('staff.exitNoCandidates', 'merchant:staff', '暂无其他在职员工可接手'),
  ('staff.exitNoTarget', 'merchant:staff', '请先选择接手员工'),
  ('staff.exitNotePh', 'merchant:staff', '备注（选填，随改挂留痕）'),
  ('staff.exitReassigned', 'merchant:staff', '改挂完成：共改挂 {n} 单'),
  ('staff.exitReassignHint', 'merchant:staff', '将该员工名下未完结预约改挂给接手人；改挂留痕前后值快照'),
  ('staff.exitReassigning', 'merchant:staff', '改挂中…'),
  ('staff.exitReassignSubmit', 'merchant:staff', '确认改挂'),
  ('staff.exitReassignTitle', 'merchant:staff', '改挂未完结单'),
  ('staff.exitToStaffPh', 'merchant:staff', '选择接手员工'),
  ('tasktpl.common.loadFail', 'merchant:tasks', '数据加载失败，请检查网络后重试'),
  ('tasktpl.common.retry', 'merchant:tasks', '重新加载'),
  ('tasktpl.form.aside', 'merchant:tasks', '频率=每日 或 每周（每周须选周日）'),
  ('tasktpl.form.cancelEdit', 'merchant:tasks', '取消编辑'),
  ('tasktpl.form.detailLabel', 'merchant:tasks', '说明'),
  ('tasktpl.form.detailPh', 'merchant:tasks', '说明（选填，员工端任务卡透出）'),
  ('tasktpl.form.dueLabel', 'merchant:tasks', '截止时刻'),
  ('tasktpl.form.freqDaily', 'merchant:tasks', '每日'),
  ('tasktpl.form.freqLabel', 'merchant:tasks', '频率'),
  ('tasktpl.form.freqWeekly', 'merchant:tasks', '每周'),
  ('tasktpl.form.invalid', 'merchant:tasks', '请填齐标题与截止时刻；按员工指派须选人；每周频率须至少选一天'),
  ('tasktpl.form.remindLabel', 'merchant:tasks', '提前提醒（分钟，选填）'),
  ('tasktpl.form.remindPh', 'merchant:tasks', '如 30'),
  ('tasktpl.form.roleFrontdesk', 'merchant:tasks', '前台'),
  ('tasktpl.form.roleGroomer', 'merchant:tasks', '美容师'),
  ('tasktpl.form.saveCta', 'merchant:tasks', '保存模板'),
  ('tasktpl.form.saved', 'merchant:tasks', '模板已保存'),
  ('tasktpl.form.saving', 'merchant:tasks', '保存中…'),
  ('tasktpl.form.scopeLabel', 'merchant:tasks', '指派范围'),
  ('tasktpl.form.scopeRole', 'merchant:tasks', '按角色'),
  ('tasktpl.form.scopeStaff', 'merchant:tasks', '按员工'),
  ('tasktpl.form.staffPh', 'merchant:tasks', '选择员工'),
  ('tasktpl.form.titleEdit', 'merchant:tasks', '编辑模板'),
  ('tasktpl.form.titleLabel', 'merchant:tasks', '任务标题'),
  ('tasktpl.form.titleNew', 'merchant:tasks', '新建模板'),
  ('tasktpl.form.titlePh', 'merchant:tasks', '任务标题（如：打烊前消毒备台）'),
  ('tasktpl.guideHint', 'merchant:tasks', '循环任务模板的新建与停用属管理层动作；店员账号的工作面是收银台。'),
  ('tasktpl.guideTitle', 'merchant:tasks', '任务模板由店长或店主处理'),
  ('tasktpl.list.aside', 'merchant:tasks', '停用=不再生成新例（active=false 留痕不删行）'),
  ('tasktpl.list.deactivateCta', 'merchant:tasks', '停用'),
  ('tasktpl.list.deactivated', 'merchant:tasks', '模板已停用'),
  ('tasktpl.list.dueLine', 'merchant:tasks', '截止 {hm}'),
  ('tasktpl.list.editCta', 'merchant:tasks', '编辑 ›'),
  ('tasktpl.list.empty', 'merchant:tasks', '暂无模板——上方表单新建第一条'),
  ('tasktpl.list.freqDailyLine', 'merchant:tasks', '每日'),
  ('tasktpl.list.freqWeeklyLine', 'merchant:tasks', '每周 {days}'),
  ('tasktpl.list.inactiveBadge', 'merchant:tasks', '已停用'),
  ('tasktpl.list.remindLine', 'merchant:tasks', '提前 {n} 分钟提醒'),
  ('tasktpl.list.scopeRoleLine', 'merchant:tasks', '角色·{role}'),
  ('tasktpl.list.scopeStaffLine', 'merchant:tasks', '指定员工'),
  ('tasktpl.list.title', 'merchant:tasks', '模板列表'),
  ('tasktpl.pageSub', 'merchant:tasks', '循环任务自管 · 每日/每周按模板生成落实例 · 停用不删行'),
  ('tasktpl.pageTitle', 'merchant:tasks', '任务模板'),
  ('tasktpl.runs.aside', 'merchant:tasks', '模板按日生成实例；完成人=员工端打点人'),
  ('tasktpl.runs.colDate', 'merchant:tasks', '日期'),
  ('tasktpl.runs.colDoneBy', 'merchant:tasks', '完成人'),
  ('tasktpl.runs.colStatus', 'merchant:tasks', '状态'),
  ('tasktpl.runs.colTemplate', 'merchant:tasks', '模板'),
  ('tasktpl.runs.empty', 'merchant:tasks', '近 7 天暂无落实例'),
  ('tasktpl.runs.statusDone', 'merchant:tasks', '已完成'),
  ('tasktpl.runs.statusMissed', 'merchant:tasks', '已过截止'),
  ('tasktpl.runs.statusPending', 'merchant:tasks', '待完成'),
  ('tasktpl.runs.title', 'merchant:tasks', '近 7 天落实例'),
  ('exec.draft.banner', 'staff:execute', '检测到上次未提交的填写（{time} 暂存）'),
  ('exec.draft.discard', 'staff:execute', '丢弃'),
  ('exec.draft.localNote', 'staff:execute', '暂存仅保存在本机，换设备或清缓存不保留'),
  ('exec.draft.restore', 'staff:execute', '继续上次填写'),
  ('exec.photo.onsiteNote', 'staff:execute', '照片须现场拍摄（服务端校验拍摄时刻），相册旧图将被拒收或标记'),
  ('me.groupCollab', 'staff:me', '通知 / 公告 / 心声 / 自检 / 问题上报'),
  ('me.row.notices', 'staff:me', '门店公告'),
  ('me.row.noticesSub', 'staff:me', '置顶在前 · 已读回执'),
  ('me.row.notifications', 'staff:me', '消息通知'),
  ('me.row.notificationsSub', 'staff:me', '派单 · 系统消息 · 未读高亮'),
  ('me.row.pdca', 'staff:me', '问题上报'),
  ('me.row.pdcaSub', 'staff:me', 'PDCA 整改闭环'),
  ('me.row.selfCheck', 'staff:me', '每日自检'),
  ('me.row.selfCheckSub', 'staff:me', '逐项打点 · 照片留证'),
  ('me.row.voice', 'staff:me', '员工心声'),
  ('me.row.voiceSub', 'staff:me', '建议吐槽 · 限时响应'),
  ('ntc.badgeRead', 'staff:notices', '已读'),
  ('ntc.badgeUnread', 'staff:notices', '未读'),
  ('ntc.empty', 'staff:notices', '暂无公告'),
  ('ntc.emptyBody', 'staff:notices', '店长发布公告后会出现在这里'),
  ('ntc.loadFail', 'staff:notices', '公告加载失败，请检查网络后重试'),
  ('ntc.no', 'staff:notices', 'NOTICES'),
  ('ntc.pinned', 'staff:notices', '置顶'),
  ('ntc.retry', 'staff:notices', '重新加载'),
  ('ntc.title', 'staff:notices', '门店公告'),
  ('ntc.unreadLead', 'staff:notices', '未读 {n} 条'),
  ('snt.empty', 'staff:notifications', '没有通知'),
  ('snt.emptyBody', 'staff:notifications', '派单、改期与系统消息会出现在这里'),
  ('snt.loadFail', 'staff:notifications', '通知加载失败，请检查网络后重试'),
  ('snt.markAll', 'staff:notifications', '全部已读'),
  ('snt.markAllDone', 'staff:notifications', '已全部标记为已读'),
  ('snt.no', 'staff:notifications', 'NOTIFICATIONS'),
  ('snt.retry', 'staff:notifications', '重新加载'),
  ('snt.title', 'staff:notifications', '通知'),
  ('snt.unreadLead', 'staff:notifications', '未读 {n} 条'),
  ('pdc.categoryPh', 'staff:pdca', '选择类目'),
  ('pdc.detailPh', 'staff:pdca', '补充说明（选填）'),
  ('pdc.empty', 'staff:pdca', '该状态下暂无问题单'),
  ('pdc.fixNotePh', 'staff:pdca', '整改说明（怎么处理的）…'),
  ('pdc.fixNoteRequired', 'staff:pdca', '请填写整改说明'),
  ('pdc.fixStarted', 'staff:pdca', '已认领整改'),
  ('pdc.fixSubmitted', 'staff:pdca', '整改已提交，待复检'),
  ('pdc.listTitle', 'staff:pdca', '问题单'),
  ('pdc.loadFail', 'staff:pdca', '加载失败，请检查网络后重试'),
  ('pdc.mine', 'staff:pdca', '我负责'),
  ('pdc.no', 'staff:pdca', 'PDCA'),
  ('pdc.photoCta', 'staff:pdca', '＋拍照留证（选传，最多 {max} 张）'),
  ('pdc.photoFull', 'staff:pdca', '最多传 {max} 张图'),
  ('pdc.raiseTitle', 'staff:pdca', '上报问题'),
  ('pdc.retry', 'staff:pdca', '重新加载'),
  ('pdc.startFix', 'staff:pdca', '开始整改'),
  ('pdc.submit', 'staff:pdca', '提交'),
  ('pdc.submitFix', 'staff:pdca', '提交整改'),
  ('pdc.submitted', 'staff:pdca', '已上报，店长会分派整改'),
  ('pdc.submitting', 'staff:pdca', '提交中…'),
  ('pdc.tabAll', 'staff:pdca', '全部'),
  ('pdc.tabClosed', 'staff:pdca', '已关闭'),
  ('pdc.tabFixing', 'staff:pdca', '整改中'),
  ('pdc.tabOpen', 'staff:pdca', '待整改'),
  ('pdc.tabRecheck', 'staff:pdca', '待复检'),
  ('pdc.title', 'staff:pdca', '问题上报'),
  ('pdc.titlePh', 'staff:pdca', '一句话说清问题'),
  ('pdc.titleRequired', 'staff:pdca', '请先填写问题标题'),
  ('sck.aside', 'staff:selfcheck', '逐项打点后提交；照片选传，用于留证'),
  ('sck.auditApproved', 'staff:selfcheck', '复核通过'),
  ('sck.auditPending', 'staff:selfcheck', '待店长复核'),
  ('sck.auditRejected', 'staff:selfcheck', '复核驳回'),
  ('sck.doneTitle', 'staff:selfcheck', '今日已提交'),
  ('sck.empty', 'staff:selfcheck', '今日没有自检表项'),
  ('sck.emptyBody', 'staff:selfcheck', '表项由店长在配置端口维护'),
  ('sck.fail', 'staff:selfcheck', '未完成'),
  ('sck.loadFail', 'staff:selfcheck', '加载失败，请检查网络后重试'),
  ('sck.no', 'staff:selfcheck', 'SELF-CHECK'),
  ('sck.notePh', 'staff:selfcheck', '备注（选填）'),
  ('sck.pass', 'staff:selfcheck', '完成'),
  ('sck.photoCta', 'staff:selfcheck', '＋拍照留证（选传）'),
  ('sck.photoOn', 'staff:selfcheck', '已附图 ✓'),
  ('sck.retry', 'staff:selfcheck', '重新加载'),
  ('sck.score', 'staff:selfcheck', '得分 {score}'),
  ('sck.submit', 'staff:selfcheck', '提交今日自检'),
  ('sck.submitted', 'staff:selfcheck', '今日自检已提交'),
  ('sck.submitting', 'staff:selfcheck', '提交中…'),
  ('sck.title', 'staff:selfcheck', '每日自检'),
  ('sck.unmarked', 'staff:selfcheck', '还有 {n} 项未打点'),
  ('ttd.doing', 'staff:taskToday', '打点中…'),
  ('ttd.doneAt', 'staff:taskToday', '{hm} 已完成'),
  ('ttd.doneCta', 'staff:taskToday', '完成'),
  ('ttd.doneOk', 'staff:taskToday', '已完成'),
  ('ttd.due', 'staff:taskToday', '截止 {hm}'),
  ('ttd.loadFail', 'staff:taskToday', '任务加载失败'),
  ('ttd.statusDone', 'staff:taskToday', '已完成'),
  ('ttd.title', 'staff:taskToday', '今日任务'),
  ('vce.descPh', 'staff:voice', '想对店里说的话…'),
  ('vce.descRequired', 'staff:voice', '请先填写心声内容'),
  ('vce.empty', 'staff:voice', '还没有提交过心声'),
  ('vce.formAside', 'staff:voice', '建议、吐槽、求助都可以写；店长会在工作时段处理'),
  ('vce.formTitle', 'staff:voice', '提交心声'),
  ('vce.loadFail', 'staff:voice', '加载失败，请检查网络后重试'),
  ('vce.myList', 'staff:voice', '我的心声'),
  ('vce.no', 'staff:voice', 'VOICE'),
  ('vce.phonePh', 'staff:voice', '联系方式（选填，便于回复）'),
  ('vce.photoCta', 'staff:voice', '＋附图（选传，最多 {max} 张）'),
  ('vce.photoFull', 'staff:voice', '最多传 {max} 张图'),
  ('vce.replyLead', 'staff:voice', '门店回复'),
  ('vce.retry', 'staff:voice', '重新加载'),
  ('vce.slaNote', 'staff:voice', '门店承诺 {h} 小时内响应（时限口径来自配置端口）'),
  ('vce.statusClosed', 'staff:voice', '已关闭'),
  ('vce.statusReplied', 'staff:voice', '已回复'),
  ('vce.statusSubmitted', 'staff:voice', '已提交'),
  ('vce.submit', 'staff:voice', '提交'),
  ('vce.submitted', 'staff:voice', '已提交，感谢你的声音'),
  ('vce.submitting', 'staff:voice', '提交中…'),
  ('vce.title', 'staff:voice', '员工心声')
)
INSERT INTO `copy_overrides` (`id`,`version`,`rule_key`,`label`,`value_json`,`effective_from`,`active`,`created_by`,`created_at`,`updated_at`)
SELECT 'seedcopy_' || lower(hex(randomblob(8))), 1, s.rule_key, s.label, json_object('text', s.text), unixepoch(), 1, 'system', unixepoch(), unixepoch()
FROM s
WHERE NOT EXISTS (SELECT 1 FROM `copy_overrides` WHERE `rule_key` = s.rule_key AND `active` = 1);
