-- 员工端骨架整建批片 4：copy_overrides 增量种子（薪资/XP 新增 212 键随批注册；片 B 纪律=新键随批注册进端口表）
-- 幂等：rule_key active 行 NOT EXISTS 守卫（存量库只补差、重放零副作用）；created_by='system'
-- （迁移执行器 PRAGMA foreign_keys=OFF，惯例见 migrate.ts 头注）。
-- 生成件=scripts/gen-copy-overrides-seed.mts 重跑产物（server/src/db/copySeedRows.ts 同帧；总量 2330 键/53 域）。
WITH s(rule_key, label, text) AS (VALUES
  ('payroll.appeal.approveCta', 'merchant:payroll', '批准'),
  ('payroll.appeal.approved', 'merchant:payroll', '申诉已批准'),
  ('payroll.appeal.approveNotePh', 'merchant:payroll', '审批意见（选填，随单留痕）'),
  ('payroll.appeal.approveTitle', 'merchant:payroll', '批准申诉 · {name}'),
  ('payroll.appeal.aside', 'merchant:payroll', '员工对罚单/工资条行/调整项的异议在此审批，审批意见留痕'),
  ('payroll.appeal.collapseCta', 'merchant:payroll', '收起 ›'),
  ('payroll.appeal.empty', 'merchant:payroll', '当前筛选无申诉单'),
  ('payroll.appeal.evidenceLabel', 'merchant:payroll', '附图'),
  ('payroll.appeal.expandCta', 'merchant:payroll', '展开 ›'),
  ('payroll.appeal.filterAll', 'merchant:payroll', '全部'),
  ('payroll.appeal.kindAdjustment', 'merchant:payroll', '调整项'),
  ('payroll.appeal.kindDeduction', 'merchant:payroll', '罚单申诉'),
  ('payroll.appeal.kindSlipLine', 'merchant:payroll', '工资条行'),
  ('payroll.appeal.monthLine', 'merchant:payroll', '涉月 {month}'),
  ('payroll.appeal.notePh', 'merchant:payroll', '审批意见（必填，随单留痕）'),
  ('payroll.appeal.noteRequired', 'merchant:payroll', '审批意见不能为空'),
  ('payroll.appeal.reasonLabel', 'merchant:payroll', '申诉理由'),
  ('payroll.appeal.refundInvalid', 'merchant:payroll', '返还金额须为不小于 0 的两位小数'),
  ('payroll.appeal.refundLabel', 'merchant:payroll', '返还金额（元，默认原额可改）'),
  ('payroll.appeal.refundLine', 'merchant:payroll', '返还 {amount}'),
  ('payroll.appeal.refundPh', 'merchant:payroll', '如 120.00'),
  ('payroll.appeal.rejectCta', 'merchant:payroll', '驳回'),
  ('payroll.appeal.rejected', 'merchant:payroll', '申诉已驳回'),
  ('payroll.appeal.rejectTitle', 'merchant:payroll', '驳回申诉 · {name}'),
  ('payroll.appeal.reviewLine', 'merchant:payroll', '{result} · {note}'),
  ('payroll.appeal.statusApproved', 'merchant:payroll', '已批准'),
  ('payroll.appeal.statusPending', 'merchant:payroll', '待审批'),
  ('payroll.appeal.statusRejected', 'merchant:payroll', '已驳回'),
  ('payroll.appeal.targetAmountLine', 'merchant:payroll', '原额 {amount}'),
  ('payroll.appeal.title', 'merchant:payroll', '薪资申诉审批'),
  ('payroll.collab.addCta', 'merchant:payroll', '添加'),
  ('payroll.collab.aside', 'merchant:payroll', '多人协作单按万分比拆分提成；拆分比入端口'),
  ('payroll.collab.cancelEdit', 'merchant:payroll', '取消'),
  ('payroll.collab.editCta', 'merchant:payroll', '编辑拆分'),
  ('payroll.collab.empty', 'merchant:payroll', '未登记协作人，本单提成全归主操作人'),
  ('payroll.collab.mainNote', 'merchant:payroll', '主操作人吃余数：协作人合计 + 主操作人 = 100%'),
  ('payroll.collab.readonlyNote', 'merchant:payroll', '已完成单的拆分只读透出；服务中/已确认可编辑'),
  ('payroll.collab.removeCta', 'merchant:payroll', '移除'),
  ('payroll.collab.roleAssist', 'merchant:payroll', '助理'),
  ('payroll.collab.roleGroom', 'merchant:payroll', '美容'),
  ('payroll.collab.roleLabel', 'merchant:payroll', '协作角色'),
  ('payroll.collab.roleWash', 'merchant:payroll', '洗护'),
  ('payroll.collab.saveCta', 'merchant:payroll', '保存拆分'),
  ('payroll.collab.saved', 'merchant:payroll', '协作拆分已保存'),
  ('payroll.collab.saving', 'merchant:payroll', '保存中…'),
  ('payroll.collab.splitInvalid', 'merchant:payroll', '拆分比须为 0~100 的数，且合计不得超过 100%'),
  ('payroll.collab.splitLabel', 'merchant:payroll', '拆分比（%）'),
  ('payroll.collab.staffPh', 'merchant:payroll', '添加协作员工'),
  ('payroll.collab.sumLine', 'merchant:payroll', '协作合计 {sum}%（余 {rest}% 归主操作人）'),
  ('payroll.collab.title', 'merchant:payroll', '协作拆分'),
  ('payroll.common.cancel', 'merchant:payroll', '取消'),
  ('payroll.common.confirm', 'merchant:payroll', '确认提交'),
  ('payroll.common.loadFail', 'merchant:payroll', '数据加载失败，请检查网络后重试'),
  ('payroll.common.retry', 'merchant:payroll', '重新加载'),
  ('payroll.common.submitting', 'merchant:payroll', '提交中…'),
  ('payroll.ded.amountInvalid', 'merchant:payroll', '扣减金额须为大于 0 的两位小数'),
  ('payroll.ded.amountLabel', 'merchant:payroll', '扣减金额（元）'),
  ('payroll.ded.amountPh', 'merchant:payroll', '如 200.00'),
  ('payroll.ded.aside', 'merchant:payroll', '扣减只扣绩效不扣提成；当月累计达上限 server 硬拒（50% 红线）'),
  ('payroll.ded.created', 'merchant:payroll', '罚单已录入'),
  ('payroll.ded.empty', 'merchant:payroll', '暂无罚单记录'),
  ('payroll.ded.invalid', 'merchant:payroll', '请选员工并填写金额与原因'),
  ('payroll.ded.listTitle', 'merchant:payroll', '近 20 条罚单'),
  ('payroll.ded.monthLabel', 'merchant:payroll', '归属月份'),
  ('payroll.ded.reasonLabel', 'merchant:payroll', '原因'),
  ('payroll.ded.reasonPh', 'merchant:payroll', '必填，随单留痕'),
  ('payroll.ded.revertedBadge', 'merchant:payroll', '已返还'),
  ('payroll.ded.revertLine', 'merchant:payroll', '返还留痕 · {at}'),
  ('payroll.ded.staffLabel', 'merchant:payroll', '员工'),
  ('payroll.ded.staffPh', 'merchant:payroll', '选择员工'),
  ('payroll.ded.submitCta', 'merchant:payroll', '录入罚单'),
  ('payroll.ded.submitting', 'merchant:payroll', '录入中…'),
  ('payroll.ded.title', 'merchant:payroll', '罚单录入'),
  ('payroll.guideHint', 'merchant:payroll', '工资条生成、申诉审批与罚单录入属管理层动作；店员账号的工作面是收银台。'),
  ('payroll.guideTitle', 'merchant:payroll', '薪资管理由店长或店主处理'),
  ('payroll.pageSub', 'merchant:payroll', '工资条生成与确认 · 申诉审批 · 罚单录入（发放=标记留痕，不碰真钱）'),
  ('payroll.pageTitle', 'merchant:payroll', '薪资'),
  ('payroll.slip.aside', 'merchant:payroll', '月份生成 → 老板确认定稿 → 逐人标记发放（标记留痕不碰真钱）'),
  ('payroll.slip.colAction', 'merchant:payroll', '操作'),
  ('payroll.slip.colAdjustment', 'merchant:payroll', '调整项'),
  ('payroll.slip.colCommission', 'merchant:payroll', '提成'),
  ('payroll.slip.colDeduction', 'merchant:payroll', '扣减'),
  ('payroll.slip.colDisburse', 'merchant:payroll', '发放'),
  ('payroll.slip.colNet', 'merchant:payroll', '净额'),
  ('payroll.slip.colPerformance', 'merchant:payroll', '绩效'),
  ('payroll.slip.colStaff', 'merchant:payroll', '员工'),
  ('payroll.slip.confirmCta', 'merchant:payroll', '老板确认'),
  ('payroll.slip.confirmed', 'merchant:payroll', '工资条已定稿'),
  ('payroll.slip.confirming', 'merchant:payroll', '确认中…'),
  ('payroll.slip.disbursedNote', 'merchant:payroll', '发放=标记留痕不碰真钱；重复标记幂等，留痕可溯。'),
  ('payroll.slip.empty', 'merchant:payroll', '该月份尚未生成工资条'),
  ('payroll.slip.generateCta', 'merchant:payroll', '生成工资条'),
  ('payroll.slip.generated', 'merchant:payroll', '工资条已生成'),
  ('payroll.slip.generating', 'merchant:payroll', '生成中…'),
  ('payroll.slip.markCta', 'merchant:payroll', '标记发放'),
  ('payroll.slip.markDone', 'merchant:payroll', '发放标记已登记'),
  ('payroll.slip.markedBadge', 'merchant:payroll', '已发放'),
  ('payroll.slip.markedByLine', 'merchant:payroll', '标记人 {by} · {at}'),
  ('payroll.slip.markNote', 'merchant:payroll', '发放=标记留痕（记账动作），系统不碰真钱、不走支付通道。'),
  ('payroll.slip.markTitle', 'merchant:payroll', '标记发放 · {name}'),
  ('payroll.slip.methodNotePh', 'merchant:payroll', '发放方式备注（选填，如「现金」/「转账尾号」）'),
  ('payroll.slip.monthLabel', 'merchant:payroll', '工资月份'),
  ('payroll.slip.statusConfirmed', 'merchant:payroll', '已定稿'),
  ('payroll.slip.statusGenerated', 'merchant:payroll', '待确认'),
  ('payroll.slip.title', 'merchant:payroll', '工资条'),
  ('xpadmin.award.aside', 'merchant:xpAdmin', '员工申报的正向积分；批准才落正式 XP 事件'),
  ('xpadmin.award.empty', 'merchant:xpAdmin', '暂无待审批的积分申报'),
  ('xpadmin.award.pointsLine', 'merchant:xpAdmin', '申报 +{n} 分'),
  ('xpadmin.award.title', 'merchant:xpAdmin', '积分申报审批'),
  ('xpadmin.common.cancel', 'merchant:xpAdmin', '取消'),
  ('xpadmin.common.confirm', 'merchant:xpAdmin', '确认提交'),
  ('xpadmin.common.loadFail', 'merchant:xpAdmin', '数据加载失败，请检查网络后重试'),
  ('xpadmin.common.retry', 'merchant:xpAdmin', '重新加载'),
  ('xpadmin.common.submitting', 'merchant:xpAdmin', '提交中…'),
  ('xpadmin.guideHint', 'merchant:xpAdmin', '积分申报与扣分异议的审批属管理层动作；店员账号的工作面是收银台。'),
  ('xpadmin.guideTitle', 'merchant:xpAdmin', 'XP 审核由店长或店主处理'),
  ('xpadmin.history.aside', 'merchant:xpAdmin', '审核结论随单留痕；通过单含落行回链'),
  ('xpadmin.history.empty', 'merchant:xpAdmin', '暂无审批历史'),
  ('xpadmin.history.kindAward', 'merchant:xpAdmin', '积分申报'),
  ('xpadmin.history.kindRevoke', 'merchant:xpAdmin', '扣分异议'),
  ('xpadmin.history.reviewedAt', 'merchant:xpAdmin', '审批于 {at}'),
  ('xpadmin.history.reviewLine', 'merchant:xpAdmin', '{result} · {note}'),
  ('xpadmin.history.statusApproved', 'merchant:xpAdmin', '已批准'),
  ('xpadmin.history.statusRejected', 'merchant:xpAdmin', '已驳回'),
  ('xpadmin.history.title', 'merchant:xpAdmin', '审批历史'),
  ('xpadmin.pageSub', 'merchant:xpAdmin', '积分申报与扣分异议审批；审核通过才落正式流水，XP 事件只增不改'),
  ('xpadmin.pageTitle', 'merchant:xpAdmin', 'XP 审核'),
  ('xpadmin.review.appliedAt', 'merchant:xpAdmin', '提交于 {at}'),
  ('xpadmin.review.approveCta', 'merchant:xpAdmin', '批准'),
  ('xpadmin.review.approved', 'merchant:xpAdmin', '已批准，正式流水已落'),
  ('xpadmin.review.approveTitle', 'merchant:xpAdmin', '批准申请 · {name}'),
  ('xpadmin.review.notePh', 'merchant:xpAdmin', '审批意见（必填，随单留痕）'),
  ('xpadmin.review.noteRequired', 'merchant:xpAdmin', '审批意见不能为空'),
  ('xpadmin.review.reasonLabel', 'merchant:xpAdmin', '申请理由'),
  ('xpadmin.review.rejectCta', 'merchant:xpAdmin', '驳回'),
  ('xpadmin.review.rejected', 'merchant:xpAdmin', '已驳回'),
  ('xpadmin.review.rejectTitle', 'merchant:xpAdmin', '驳回申请 · {name}'),
  ('xpadmin.revoke.aside', 'merchant:xpAdmin', '批准=对冲：原负分保留不删，另写一条正向对冲行（明面对冲注记）'),
  ('xpadmin.revoke.empty', 'merchant:xpAdmin', '暂无待审批的扣分异议'),
  ('xpadmin.revoke.hedgeNote', 'merchant:xpAdmin', '批准口径：原负分保留，按请求分值写对冲行，事件流水只增不改。'),
  ('xpadmin.revoke.originalLine', 'merchant:xpAdmin', '原扣分事件 {n} 分'),
  ('xpadmin.revoke.pointsLine', 'merchant:xpAdmin', '请求对冲 +{n} 分'),
  ('xpadmin.revoke.title', 'merchant:xpAdmin', '扣分异议审批'),
  ('prl.adjust.note', 'staff:payroll', '负数=跨月回冲 · 正数=补调'),
  ('prl.adjust.sourceLead', 'staff:payroll', '原属'),
  ('prl.appeal.cancel', 'staff:payroll', '取消'),
  ('prl.appeal.photoCta', 'staff:payroll', '＋附图（选传，最多 {max} 张）'),
  ('prl.appeal.photoFull', 'staff:payroll', '最多传 {max} 张图'),
  ('prl.appeal.reasonPh', 'staff:payroll', '申诉理由（必填，说明情况）'),
  ('prl.appeal.reasonRequired', 'staff:payroll', '请先填写申诉理由'),
  ('prl.appeal.submit', 'staff:payroll', '提交申诉'),
  ('prl.appeal.submitted', 'staff:payroll', '申诉已提交，等待复核'),
  ('prl.appeal.submitting', 'staff:payroll', '提交中…'),
  ('prl.appeal.title', 'staff:payroll', '提交申诉'),
  ('prl.appeals.empty', 'staff:payroll', '暂无申诉记录'),
  ('prl.appeals.loadFail', 'staff:payroll', '申诉记录加载失败，请稍后重试'),
  ('prl.appeals.refundLead', 'staff:payroll', '返还'),
  ('prl.appeals.reviewLead', 'staff:payroll', '复核注'),
  ('prl.appeals.slaNote', 'staff:payroll', '申诉将在 {h} 小时内复核（时限口径来自配置端口）'),
  ('prl.appeals.statusApproved', 'staff:payroll', '复核通过'),
  ('prl.appeals.statusPending', 'staff:payroll', '待复核'),
  ('prl.appeals.statusRejected', 'staff:payroll', '复核驳回'),
  ('prl.appeals.target.adjustment', 'staff:payroll', '调整项'),
  ('prl.appeals.target.deduction', 'staff:payroll', '扣减'),
  ('prl.appeals.target.slipLine', 'staff:payroll', '工资条'),
  ('prl.deduction.appeal', 'staff:payroll', '申诉'),
  ('prl.deduction.reverted', 'staff:payroll', '已返还'),
  ('prl.line.splitLead', 'staff:payroll', '协作拆得'),
  ('prl.refund.row', 'staff:payroll', '跨月退款回冲'),
  ('prl.retry', 'staff:payroll', '重新加载'),
  ('prl.sec.myAppeals', 'staff:payroll', '我的申诉'),
  ('prl.sec.refund', 'staff:payroll', '回冲与调整'),
  ('prl.sec.slip', 'staff:payroll', '工资条'),
  ('prl.slip.adjustment', 'staff:payroll', '调整'),
  ('prl.slip.appeal', 'staff:payroll', '对工资条申诉'),
  ('prl.slip.commission', 'staff:payroll', '提成'),
  ('prl.slip.deduction', 'staff:payroll', '扣减'),
  ('prl.slip.empty', 'staff:payroll', '工资条生成中'),
  ('prl.slip.emptyBody', 'staff:payroll', '每月结算核对后生成，请稍后再看'),
  ('prl.slip.marked', 'staff:payroll', '已发放'),
  ('prl.slip.markNote', 'staff:payroll', '发放为标记留痕，不代表银行到账'),
  ('prl.slip.netLabel', 'staff:payroll', '本月实发'),
  ('prl.slip.performance', 'staff:payroll', '绩效'),
  ('prl.slip.unmarked', 'staff:payroll', '尚未标记发放'),
  ('prl.track.labor', 'staff:payroll', '劳动业绩'),
  ('prl.track.note', 'staff:payroll', '劳动=服务操作营收门市价 · 销售=商品实收'),
  ('prl.track.sales', 'staff:payroll', '销售业绩'),
  ('xp.app.appealCta', 'staff:xp', '异议'),
  ('xp.app.appealReasonPh', 'staff:xp', '异议理由（必填，说明不该扣的依据）'),
  ('xp.app.appealTitle', 'staff:xp', '扣分异议'),
  ('xp.app.cancel', 'staff:xp', '取消'),
  ('xp.app.cta', 'staff:xp', '申报积分'),
  ('xp.app.empty', 'staff:xp', '暂无申请记录'),
  ('xp.app.kindAppeal', 'staff:xp', '扣分异议'),
  ('xp.app.kindAward', 'staff:xp', '积分申报'),
  ('xp.app.loadFail', 'staff:xp', '申请记录加载失败，请稍后重试'),
  ('xp.app.note', 'staff:xp', '申报与异议由店长/老板在管理端审核，员工不可自审'),
  ('xp.app.pointsInvalid', 'staff:xp', '请填写有效分值（正整数）'),
  ('xp.app.pointsLead', 'staff:xp', '申报'),
  ('xp.app.pointsPh', 'staff:xp', '申报分值（正整数）'),
  ('xp.app.reasonPh', 'staff:xp', '申报理由（必填，说明依据）'),
  ('xp.app.reasonRequired', 'staff:xp', '请先填写理由'),
  ('xp.app.resolvedNote', 'staff:xp', '已落分，见近期事件'),
  ('xp.app.reviewLead', 'staff:xp', '审核注'),
  ('xp.app.sec.list', 'staff:xp', '我的申请'),
  ('xp.app.statusApproved', 'staff:xp', '已通过'),
  ('xp.app.statusPending', 'staff:xp', '待审核'),
  ('xp.app.statusRejected', 'staff:xp', '已驳回'),
  ('xp.app.submit', 'staff:xp', '提交申报'),
  ('xp.app.submitted', 'staff:xp', '已提交，等待审核'),
  ('xp.app.submitting', 'staff:xp', '提交中…'),
  ('xp.app.title', 'staff:xp', '积分申报')
)
INSERT INTO `copy_overrides` (`id`,`version`,`rule_key`,`label`,`value_json`,`effective_from`,`active`,`created_by`,`created_at`,`updated_at`)
SELECT 'seedcopy_' || lower(hex(randomblob(8))), 1, s.rule_key, s.label, json_object('text', s.text), unixepoch(), 1, 'system', unixepoch(), unixepoch()
FROM s
WHERE NOT EXISTS (SELECT 1 FROM `copy_overrides` WHERE `rule_key` = s.rule_key AND `active` = 1);
