-- 员工端骨架整建批片 5：copy_overrides 增量种子（控制台 17 屏重建新增 241 键随批注册；片 B 纪律=新键随批注册进端口表）
-- 幂等：rule_key active 行 NOT EXISTS 守卫（存量库只补差、重放零副作用）；created_by='system'
-- （迁移执行器 PRAGMA foreign_keys=OFF，惯例见 migrate.ts 头注）。
-- 生成件=scripts/gen-copy-overrides-seed.mts 重跑产物（server/src/db/copySeedRows.ts 同帧）。
WITH s(rule_key, label, text) AS (VALUES
  ('appt.dualOwnerNote', 'merchant:appointments', '单据双归属：客户指定的洗护师会写在预约备注里传达门店，派单以门店安排为准'),
  ('appt.flowBoarding', 'merchant:appointments', '寄养中'),
  ('appt.flowCancelled', 'merchant:appointments', '已取消'),
  ('appt.flowCheckin', 'merchant:appointments', '核销'),
  ('appt.flowConfirm', 'merchant:appointments', '确认'),
  ('appt.flowDone', 'merchant:appointments', '完成'),
  ('appt.flowPaid', 'merchant:appointments', '收款'),
  ('appt.flowPending', 'merchant:appointments', '待确认'),
  ('appt.flowServing', 'merchant:appointments', '服务中'),
  ('appt.flowTitle', 'merchant:appointments', '状态流'),
  ('appt.flowWaitCheckin', 'merchant:appointments', '待到店核销'),
  ('appt.flowWaitPay', 'merchant:appointments', '待收款'),
  ('appt.folioAmount', 'merchant:appointments', '服务金额'),
  ('appt.folioDiscount', 'merchant:appointments', '会员折扣'),
  ('appt.folioDiscountNone', 'merchant:appointments', '无'),
  ('appt.folioDiscountPass', 'merchant:appointments', '次卡扣次'),
  ('appt.folioNet', 'merchant:appointments', '实收'),
  ('appt.folioNotYet', 'merchant:appointments', '未收'),
  ('appt.folioPaid', 'merchant:appointments', '已收'),
  ('appt.folioPayMode', 'merchant:appointments', '收款方式'),
  ('appt.folioPayState', 'merchant:appointments', '支付状态'),
  ('appt.folioTitle', 'merchant:appointments', '金额'),
  ('appt.folioUnpaid', 'merchant:appointments', '待收款'),
  ('appt.hintPay', 'merchant:appointments', '服务已完成，登记收款后本单闭环'),
  ('appt.hintPending', 'merchant:appointments', '确认预约后等待客户到店，核销码见左侧服务信息'),
  ('appt.hintReassign', 'merchant:appointments', '商家改派会覆盖自动派单结果并留痕，员工行来源签同步变更'),
  ('appt.hintReview', 'merchant:appointments', '客户申请取消本单，请在操作区审批'),
  ('appt.hintTitle', 'merchant:appointments', '提示'),
  ('appt.infoTitle', 'merchant:appointments', '服务信息'),
  ('appt.openDetail', 'merchant:appointments', '详情'),
  ('appt.opsTitle', 'merchant:appointments', '操作'),
  ('appt.thAction', 'merchant:appointments', '操作'),
  ('appt.thAmount', 'merchant:appointments', '金额'),
  ('appt.thCode', 'merchant:appointments', '核销码'),
  ('appt.thPetService', 'merchant:appointments', '宠物 / 服务'),
  ('appt.thStaff', 'merchant:appointments', '员工'),
  ('appt.thStatus', 'merchant:appointments', '状态'),
  ('appt.thTime', 'merchant:appointments', '时间'),
  ('board.capCalError', 'merchant:boarding', '容量日历加载失败'),
  ('board.capCalLoading', 'merchant:boarding', '容量日历加载中…'),
  ('board.capCalNote', 'merchant:boarding', '容量=在架房型间数合计，已住=逐晚预订槽位（boardingAvailability 预订口径，与上方在店口径不同源）'),
  ('board.m3Checkin', 'merchant:boarding', '今日入住'),
  ('board.m3Checkout', 'merchant:boarding', '今日退房'),
  ('board.m3InStore', 'merchant:boarding', '在店'),
  ('board.m3Overdue', 'merchant:boarding', '超期'),
  ('board.vaccineNote', 'merchant:boarding', '疫苗硬规则：员工端入住页透出疫苗有效期（过期赭红、30 天内到期提醒），过期不可入住的置灰拦截以员工端为准'),
  ('cashier.refundExecutedNote', 'merchant:cashier', '已执行落账 · 不可撤销'),
  ('cashier.refundPolicyReject', 'merchant:cashier', '草稿单（gold 审批位）可驳回——店长（本店）/店主（全域），原因必填留痕'),
  ('cashier.refundPolicyTitle', 'merchant:cashier', '驳回权口径'),
  ('cashier.refundsCreateHint', 'merchant:cashier', '退款从收银流水发起：已收单 → 详情 → 退款'),
  ('cashier.refundsCreateLink', 'merchant:cashier', '发起退款 ›'),
  ('cashier.tenderSplitAside', 'merchant:cashier', '现金/微信/支付宝计入已收 · 储值为参考列不计入（裁定①）'),
  ('cashier.tenderSplitRef', 'merchant:cashier', '次卡等值（参考·不计入）'),
  ('cashier.tenderSplitTitle', 'merchant:cashier', '今日账面四分列'),
  ('cadm.coexistNote', 'merchant:consoleAdmin', '共构不分叉：右栏直接复用规则配置/文案端口/槽位端口三页内核；旧路由 /settings/rules · /settings/copy · /settings/slots 保留可直达。'),
  ('cadm.dangerFrozen', 'merchant:consoleAdmin', '冻结项只读：作废/备用/预留规则行与结构字段（如会员档免费属性）不给改。'),
  ('cadm.dangerNoBackdate', 'merchant:consoleAdmin', '动规则不动账：规则改动只约束生效后的单，不回溯历史月份与已快照数据。'),
  ('cadm.dangerPin', 'merchant:consoleAdmin', '二次确认=L2-④ 二次 PIN：保存须键入「确认保存」口令（文案高危键逐键确认），沿用既有 highRisk 口令闸，非独立 PIN 件。'),
  ('cadm.groupA', 'merchant:consoleAdmin', 'A · 内容运营'),
  ('cadm.groupC', 'merchant:consoleAdmin', 'C · 会员机制'),
  ('cadm.groupD', 'merchant:consoleAdmin', 'D · 员工规则'),
  ('cadm.groupE', 'merchant:consoleAdmin', 'E · 门店·数据'),
  ('cadm.logAside', 'merchant:consoleAdmin', 'config.versions / 槽位版本计数现状透出'),
  ('cadm.logTitle', 'merchant:consoleAdmin', '留痕'),
  ('cadm.ownerOnlyBody', 'merchant:consoleAdmin', '端口配置与发布属店主专属（页内闸门 + server 硬闸门兜底）；请切换店主账号。'),
  ('cadm.ownerOnlyTitle', 'merchant:consoleAdmin', '开发者管理端仅店主可用'),
  ('cadm.pageSub', 'merchant:consoleAdmin', '端口配置与发布 · 店主专属 · 共构不分叉'),
  ('cadm.pageTitle', 'merchant:consoleAdmin', '开发者管理端'),
  ('cadm.portCommission', 'merchant:consoleAdmin', '提成'),
  ('cadm.portCopy', 'merchant:consoleAdmin', '文案端口'),
  ('cadm.portMember', 'merchant:consoleAdmin', '会员档'),
  ('cadm.portPendingNote', 'merchant:consoleAdmin', '置灰 · 端口待立'),
  ('cadm.portProfile', 'merchant:consoleAdmin', '门店档案'),
  ('cadm.portReportSpec', 'merchant:consoleAdmin', '报表口径'),
  ('cadm.portSlots', 'merchant:consoleAdmin', '槽位端口'),
  ('cadm.portStored', 'merchant:consoleAdmin', '储值'),
  ('cadm.portXp', 'merchant:consoleAdmin', 'XP'),
  ('cadm.profileEmptyBody', 'merchant:consoleAdmin', '门店档案维护在「门店档案·设置」页（W-15）；本口立项后收编，当前只读占位。'),
  ('cadm.profileEmptyTitle', 'merchant:consoleAdmin', '档案端口未收编'),
  ('cadm.pubNote', 'merchant:consoleAdmin', '发布流透出：草稿→预览→发布推三端；回滚=槽位卡「回退上一版」真链路（publish/revert 同管道，虚线注非新件）。'),
  ('cadm.reportSpecEmptyBody', 'merchant:consoleAdmin', 'D1–D9 报表口径/导出=开口项（18 号档 E4 🆕立项待供给）；本口只读占位。'),
  ('cadm.reportSpecEmptyTitle', 'merchant:consoleAdmin', '报表口径端口待立'),
  ('cadm.storedEmptyBody', 'merchant:consoleAdmin', '储值参数暂无独立配置域（储值提成规则已作废置灰，归提成域只读行）；立项前本口只读占位。'),
  ('cadm.storedEmptyTitle', 'merchant:consoleAdmin', '储值端口待立'),
  ('wnav.appts', 'merchant:console', '门店端·预约'),
  ('wnav.batchNote', 'merchant:console', '批次扩口 · 明面保留不删，转正后归并'),
  ('wnav.boarding', 'merchant:console', '寄养'),
  ('wnav.cashier', 'merchant:console', '收银台'),
  ('wnav.close', 'merchant:console', '日结'),
  ('wnav.dockCashier', 'merchant:console', '收银'),
  ('wnav.dockMe', 'merchant:console', '我的'),
  ('wnav.dockMeNote', 'merchant:console', '「我的」槽映射门店档案·设置'),
  ('wnav.dockOverview', 'merchant:console', '总览'),
  ('wnav.dockReport', 'merchant:console', '报表'),
  ('wnav.dockStore', 'merchant:console', '门店'),
  ('wnav.finance', 'merchant:console', '报表'),
  ('wnav.footConsole', 'merchant:console', '开发者管理端'),
  ('wnav.footRules', 'merchant:console', '规则配置'),
  ('wnav.groupAdmin', 'merchant:console', '管理'),
  ('wnav.groupBatch', 'merchant:console', '批次扩口'),
  ('wnav.groupMall', 'merchant:console', '商城'),
  ('wnav.groupOps', 'merchant:console', '经营'),
  ('wnav.matrix', 'merchant:console', '权限矩阵'),
  ('wnav.monitor', 'merchant:console', '监控 Hub'),
  ('wnav.ops', 'merchant:console', '审批中心'),
  ('wnav.opsBatch', 'merchant:console', '运营'),
  ('wnav.opsBatchNote', 'merchant:console', '与审批中心同屏'),
  ('wnav.orders', 'merchant:console', '商城订单'),
  ('wnav.overview', 'merchant:console', '总览·驾驶舱'),
  ('wnav.pass', 'merchant:console', '会员·次卡'),
  ('wnav.payroll', 'merchant:console', '薪资'),
  ('wnav.placeholderBody', 'merchant:console', '本屏锚点与导航结构段 0 先冻结，内容与交互段 3 落位。'),
  ('wnav.placeholderPending', 'merchant:console', '待段 3 落位'),
  ('wnav.products', 'merchant:console', '商品'),
  ('wnav.refunds', 'merchant:console', '退款'),
  ('wnav.schedules', 'merchant:console', '排班'),
  ('wnav.settings', 'merchant:console', '门店档案·设置'),
  ('wnav.staff', 'merchant:console', '员工'),
  ('wnav.xpAdmin', 'merchant:console', 'XP 审核'),
  ('wsk.alertEmpty', 'merchant:console', '当前没有异常'),
  ('wsk.alertGo', 'merchant:console', '去处理'),
  ('wsk.capCalFull', 'merchant:console', '满'),
  ('wsk.capCalLegend', 'merchant:console', '容量点=已住/容量'),
  ('wsk.dangerTitle', 'merchant:console', '危险区'),
  ('wsk.empty', 'merchant:console', '暂无内容'),
  ('wsk.folioTotal', 'merchant:console', '合计'),
  ('wsk.logEmpty', 'merchant:console', '还没有留痕'),
  ('wsk.matrixLocked', 'merchant:console', '锁死'),
  ('wsk.matrixNo', 'merchant:console', '—'),
  ('wsk.matrixOk', 'merchant:console', '✓'),
  ('wsk.matrixReadonly', 'merchant:console', '只读'),
  ('wsk.postcardEyebrow', 'merchant:console', 'MORNING POST'),
  ('wsk.postcardMore', 'merchant:console', '读完整晨报'),
  ('wsk.postcardTitle', 'merchant:console', '晨报。'),
  ('wsk.pubDraft', 'merchant:console', '草稿'),
  ('wsk.pubPreview', 'merchant:console', '预览'),
  ('wsk.pubPush', 'merchant:console', '发布推三端'),
  ('wsk.pubRollback', 'merchant:console', '回滚'),
  ('wsk.redline1', 'merchant:console', '无充值入口'),
  ('wsk.redline2', 'merchant:console', '年费≠储值'),
  ('wsk.redline3', 'merchant:console', '四分列对账'),
  ('wsk.redline4', 'merchant:console', '扣次非现金'),
  ('wsk.redlineTitle', 'merchant:console', '红线明面'),
  ('wsk.totalSpark', 'merchant:console', '近 14 日'),
  ('dash.approvalEmpty', 'merchant:dashboard', '当前没有待审批事项'),
  ('dash.approvalListTitle', 'merchant:dashboard', '审批'),
  ('dash.m3ChainNote', 'merchant:dashboard', '多店三栏=连锁预留开口项，当前按单店口径呈现'),
  ('dash.m3Title', 'merchant:dashboard', '单店口径'),
  ('dash.postcardFigCap', 'merchant:dashboard', '今日营业额 · 实时'),
  ('dash.postcardRowBoarding', 'merchant:dashboard', '在店寄养'),
  ('dash.postcardRowOverdue', 'merchant:dashboard', '超期寄养'),
  ('dash.postcardRowTodo', 'merchant:dashboard', '待办合计'),
  ('dash.sparkEmpty', 'merchant:dashboard', '近 14 日营收曲线读口待接入，槽位预留不造假'),
  ('dash.todayListTitle', 'merchant:dashboard', '今日预约'),
  ('dash.totalCap', 'merchant:dashboard', '今日营业额'),
  ('dash.totalPaidCell', 'merchant:dashboard', '已收笔数'),
  ('dash.totalUnpaidCell', 'merchant:dashboard', '待收笔数'),
  ('mtx.colCashier', 'merchant:matrix', '收银'),
  ('mtx.colClose', 'merchant:matrix', '日结'),
  ('mtx.colCopy', 'merchant:matrix', '文案端口'),
  ('mtx.colMatrix', 'merchant:matrix', '权限矩阵'),
  ('mtx.colMember', 'merchant:matrix', '会员'),
  ('mtx.colRefund', 'merchant:matrix', '退款'),
  ('mtx.colReport', 'merchant:matrix', '报表'),
  ('mtx.colReverse', 'merchant:matrix', '反结账'),
  ('mtx.colRules', 'merchant:matrix', '规则配置'),
  ('mtx.colSlots', 'merchant:matrix', '槽位'),
  ('mtx.colStaff', 'merchant:matrix', '员工'),
  ('mtx.colStock', 'merchant:matrix', '库存'),
  ('mtx.lockedPill', 'merchant:matrix', '锁死区 · 反结账/导出/储值导入仅店主'),
  ('mtx.noteLocked', 'merchant:matrix', '锁死区：反结账/导出/储值台账导入仅店主，任何端不可下放'),
  ('mtx.noteMatrix', 'merchant:matrix', '权限矩阵：本页只读；编辑归控制台（开发侧发布），任何端不可页内改'),
  ('mtx.noteMember', 'merchant:matrix', '会员：前台=仅收银识别时可见档位/余额/次卡，不可翻台账'),
  ('mtx.noteRefund', 'merchant:matrix', '退款：店长=本店≤阈值（默认 ¥500，配置端口店主可调）且非涉储值；超阈值/涉储值锁死仅店主（V1.2/V1.3 并轨）'),
  ('mtx.noteReport', 'merchant:matrix', '报表：店员不看营业额（总规则②）；导出仅店主（总规则③）'),
  ('mtx.noteSource', 'merchant:matrix', '数据真源：lib/roles.ts 头注冻结口径 + 20 号档 V1.2（退款行）+ 26 号档 V1.3（驳回权/运营）；改矩阵先改真源'),
  ('mtx.noteStock', 'merchant:matrix', '库存：店长=本店盘点派任务+确认差异；商品与服务定价仅店主'),
  ('mtx.pageSub', 'merchant:matrix', '角色×权限四态 · 本页只读'),
  ('mtx.pageTitle', 'merchant:matrix', '权限矩阵'),
  ('mtx.roleFront', 'merchant:matrix', '前台'),
  ('mtx.roleGroomer', 'merchant:matrix', '美容师'),
  ('mtx.roleManager', 'merchant:matrix', '店长'),
  ('mtx.roleOwner', 'merchant:matrix', '店主'),
  ('mon.alertOverdueLine', 'merchant:monitor', '{pet} · 寄养超期 {n} 天未退'),
  ('mon.alertStuckLine', 'merchant:monitor', '{pet} · {svc} · 本步 {n} 分钟未翻步'),
  ('mon.eta', 'merchant:monitor', '预计完成 {t}'),
  ('mon.stuck', 'merchant:monitor', '本步耗时已超 45 分钟'),
  ('order.rebateCol', 'merchant:orders', '回馈金'),
  ('order.rebatePendingNote', 'merchant:orders', '回馈金列读口待补——订单域未透出回馈金字段，待 server 开口；回馈金仅抵商品'),
  ('pass.cardNoCol', 'merchant:pass', '卡号'),
  ('pass.dualHomeNote', 'merchant:pass', '双归属：次卡=售卡店（本店）归属 · 会员档=办卡店归属 + 全店通用'),
  ('pass.statCards', 'merchant:pass', '持卡会员'),
  ('pass.statPass', 'merchant:pass', '次数包'),
  ('pass.statPassSub', 'merchant:pass', '剩余可扣 {n} 次'),
  ('pass.statPending', 'merchant:pass', '读口待补'),
  ('pass.statPendingNote', 'merchant:pass', '会员域暂无本店聚合读口（现仅按人查），待 server 开口——不造数'),
  ('pass.statRebate', 'merchant:pass', '回馈金负债'),
  ('pass.statSv', 'merchant:pass', '储值负债'),
  ('pass.threeBooksNote', 'merchant:pass', '三本账分离明面：次卡次数 / 储值 / 回馈金各自单列，永不混列；年费≠储值'),
  ('pass.tierNone', 'merchant:pass', '无档'),
  ('prod.csvCta', 'merchant:products', 'CSV 导入'),
  ('prod.csvPendingNote', 'merchant:products', '待供给——CSV 导入端口未开口，留位不画假件'),
  ('prod.dailyCountCol', 'merchant:products', '日盘档'),
  ('prod.dailyCountNote', 'merchant:products', '日盘档=单价 ≥¥100 商品每日盘点门槛（S-08 同口径）'),
  ('prod.dailyCountYes', 'merchant:products', '日盘'),
  ('rpt.dirD1', 'merchant:report', 'D1'),
  ('rpt.dirD2', 'merchant:report', 'D2'),
  ('rpt.dirD3', 'merchant:report', 'D3'),
  ('rpt.dirD4', 'merchant:report', 'D4'),
  ('rpt.dirD5', 'merchant:report', 'D5'),
  ('rpt.dirD6', 'merchant:report', 'D6'),
  ('rpt.dirD7', 'merchant:report', 'D7'),
  ('rpt.dirD8', 'merchant:report', 'D8'),
  ('rpt.dirD9', 'merchant:report', 'D9'),
  ('rpt.dirNote', 'merchant:report', 'D1–D9 报表口径/导出=开口项（18 号档 E4 🆕立项），全量置灰不画假件'),
  ('rpt.dirPending', 'merchant:report', '立项待供给'),
  ('rpt.dirTitle', 'merchant:report', '报表目录'),
  ('rpt.ledgerAside', 'merchant:report', '收款流水 · 按时间倒序'),
  ('rpt.ledgerTitle', 'merchant:report', '月度台账'),
  ('rpt.monthCloseNote', 'merchant:report', '月结快照：每月封箱留存，历史封箱不回填'),
  ('rpt.quadPending', 'merchant:report', '读口待补'),
  ('rpt.quadRebate', 'merchant:report', '回馈金负债'),
  ('rpt.quadRebateNote', 'merchant:report', '店级聚合读口待补（段 2 已核），置灰不造假'),
  ('rpt.quadRefund', 'merchant:report', '本月退款'),
  ('rpt.quadRefundCount', 'merchant:report', '共 {n} 笔（已执行+已实退）'),
  ('rpt.quadRevenue', 'merchant:report', '本月营收'),
  ('rpt.quadStored', 'merchant:report', '储值负债'),
  ('rpt.quadStoredNote', 'merchant:report', '店级聚合读口待补（段 2 已核），置灰不造假'),
  ('rpt.threeBooksNote', 'merchant:report', '三本账永不混列：营收 / 储值 / 回馈金各自单列'),
  ('set.entryCopy', 'merchant:settings', '文案端口'),
  ('set.entryCopyHint', 'merchant:settings', '控制台第七域 · 三端文案后台改'),
  ('set.entrySlots', 'merchant:settings', '槽位端口'),
  ('set.entrySlotsHint', 'merchant:settings', '控制台第八域 · 素材上传→待审→上线/回退'),
  ('set.panelPorts', 'merchant:settings', '端口入口'),
  ('set.portBornNote', 'merchant:settings', '带端口出生，后台可改不动代码'),
  ('set.portsAside', 'merchant:settings', 'owner 专属 · 带端口出生'),
  ('staff.attFlagged', 'merchant:staff', '打卡异常'),
  ('staff.attNote', 'merchant:staff', '考勤红字=当日打卡异常（防代打标记，attendance.exceptionQueue 真值）；「应班未打卡」店级读口待补，不画假件'),
  ('staff.permBody', 'merchant:staff', '提成与绩效明细全员仅本人可见（V1.3 员工端口径）；角色×权限四态（收银/退款/日结/反结账…）见权限矩阵。'),
  ('staff.permLink', 'merchant:staff', '查看权限矩阵 ›'),
  ('staff.permTitle', 'merchant:staff', '权限口径')
)
INSERT INTO `copy_overrides` (`id`,`version`,`rule_key`,`label`,`value_json`,`effective_from`,`active`,`created_by`,`created_at`,`updated_at`)
SELECT 'seedcopy_' || lower(hex(randomblob(8))), 1, s.rule_key, s.label, json_object('text', s.text), unixepoch(), 1, 'system', unixepoch(), unixepoch()
FROM s
WHERE NOT EXISTS (SELECT 1 FROM `copy_overrides` WHERE `rule_key` = s.rule_key AND `active` = 1);
