-- 客户端体验大批片 1：copy_overrides 增量种子（账户体系/支付售后新增 148 键随批注册；片 B 纪律=新键随批注册进端口表）
-- 幂等：rule_key active 行 NOT EXISTS 守卫（存量库只补差、重放零副作用）；created_by='system'
-- （迁移执行器 PRAGMA foreign_keys=OFF，惯例见 migrate.ts 头注）。
-- 生成件=scripts/gen-copy-overrides-seed.mts 重跑产物（server/src/db/copySeedRows.ts 同帧；总量 2716 键/63 域）。
WITH s(rule_key, label, text) AS (VALUES
  ('about.agreements', 'about', '协议中心'),
  ('about.agreementsSub', 'about', '用户协议 / 隐私政策 / 会员服务协议 / 寄养协议'),
  ('about.betaNote', 'about', '内测版本，功能与文案以门店公示为准。'),
  ('about.clearCache', 'about', '清除缓存'),
  ('about.clearCacheDesc', 'about', '清除本机缓存的图片与偏好，页面随后自动重新加载'),
  ('about.clearCancel', 'about', '再想想'),
  ('about.clearConfirmBody', 'about', '将清除本机缓存数据与本端偏好设置（含本机设备标识），账号数据不受影响；确认后页面自动重新加载。'),
  ('about.clearConfirmTitle', 'about', '清除缓存并重新加载？'),
  ('about.clearing', 'about', '正在清除…'),
  ('about.clearOk', 'about', '确认清除'),
  ('about.pushLabel', 'about', 'ABOUT'),
  ('about.title', 'about', '关于'),
  ('about.versionLabel', 'about', '版本号'),
  ('about.versionValue', 'about', '0.9.0 内测版'),
  ('device.newDeviceLink', 'account', '查看消息 ›'),
  ('device.newDeviceNote', 'account', '新设备登录提醒：账号在新设备登录时，消息中心会收到安全提醒'),
  ('privacy.accountDesc', 'account', '登录安全与账号变动'),
  ('privacy.accountLabel', 'account', '账户通知'),
  ('privacy.lockedNote', 'account', '不可关闭'),
  ('privacy.lockedWhy', 'account', '交易/服务/账户通知为保障服务履约不可关闭'),
  ('privacy.marketingDesc', 'account', '会员日、回馈金到账提醒、门店活动'),
  ('privacy.marketingLabel', 'account', '活动与优惠'),
  ('privacy.marketingOffHint', 'account', '关闭后，活动与优惠消息不再推送'),
  ('privacy.serviceDesc', 'account', '预约进度、证书与报告'),
  ('privacy.serviceLabel', 'account', '服务通知'),
  ('privacy.tradeDesc', 'account', '订单支付与退款结果'),
  ('privacy.tradeLabel', 'account', '交易通知'),
  ('settings.groupCommon', 'account', '通用'),
  ('addr.add', 'addresses', '新增地址'),
  ('addr.addTitle', 'addresses', '新增地址'),
  ('addr.defaultBadge', 'addresses', '默认'),
  ('addr.delCancel', 'addresses', '再想想'),
  ('addr.delConfirmBody', 'addresses', '删除后不可恢复。'),
  ('addr.delConfirmTitle', 'addresses', '删除该地址？'),
  ('addr.delDefaultNote', 'addresses', '这是默认地址，删除后最早添加的地址将自动升为默认。'),
  ('addr.delete', 'addresses', '删除'),
  ('addr.delFail', 'addresses', '删除失败，请稍后再试'),
  ('addr.delOk', 'addresses', '地址已删除'),
  ('addr.detailLabel', 'addresses', '详细地址'),
  ('addr.detailPlaceholder', 'addresses', '小区、楼栋、门牌号等'),
  ('addr.detailRequired', 'addresses', '请填写详细地址'),
  ('addr.edit', 'addresses', '编辑'),
  ('addr.editTitle', 'addresses', '编辑地址'),
  ('addr.emptyBody', 'addresses', '添加常用收货地址，商城下单结算时一键带出'),
  ('addr.emptyCta', 'addresses', '新增地址'),
  ('addr.emptyTitle', 'addresses', '还没有收货地址'),
  ('addr.loadFail', 'addresses', '地址加载失败，请检查网络后重试'),
  ('addr.phoneInvalid', 'addresses', '请输入 11 位手机号'),
  ('addr.phoneLabel', 'addresses', '手机号'),
  ('addr.phonePlaceholder', 'addresses', '输入 11 位手机号'),
  ('addr.pushLabel', 'addresses', 'ADDRESSES'),
  ('addr.receiverLabel', 'addresses', '收货人'),
  ('addr.receiverPlaceholder', 'addresses', '输入收货人姓名'),
  ('addr.receiverRequired', 'addresses', '请填写收货人'),
  ('addr.regionLabel', 'addresses', '所在地区'),
  ('addr.regionPlaceholder', 'addresses', '省 / 市 / 区'),
  ('addr.regionRequired', 'addresses', '请填写所在地区'),
  ('addr.save', 'addresses', '保存'),
  ('addr.saveFail', 'addresses', '保存失败，请稍后再试'),
  ('addr.saveOk', 'addresses', '地址已保存'),
  ('addr.saving', 'addresses', '保存中…'),
  ('addr.setDefault', 'addresses', '设为默认地址'),
  ('addr.title', 'addresses', '收货地址'),
  ('agr.betaMark', 'agreements', '内测期简版'),
  ('agr.betaNote', 'agreements', '本协议为内测期简版文本，正式条款以上线版本与门店公示为准。'),
  ('agr.boarding', 'agreements', '《寄养协议》'),
  ('agr.memberService', 'agreements', '《会员服务协议》'),
  ('agr.privacy', 'agreements', '《隐私政策》'),
  ('agr.pushLabel', 'agreements', 'AGREEMENTS'),
  ('agr.title', 'agreements', '协议中心'),
  ('agr.user', 'agreements', '《用户协议》'),
  ('agr.version', 'agreements', '版本 {version}'),
  ('devlogin.wechatNote', 'devlogin', '微信授权登录属小程序/资质批，PWA 端暂以手机号+种子账号入内测'),
  ('invt.add', 'invoiceTitles', '新增抬头'),
  ('invt.addTitle', 'invoiceTitles', '新增抬头'),
  ('invt.defaultBadge', 'invoiceTitles', '默认'),
  ('invt.delCancel', 'invoiceTitles', '再想想'),
  ('invt.delConfirmBody', 'invoiceTitles', '删除后不可恢复。'),
  ('invt.delConfirmTitle', 'invoiceTitles', '删除该抬头？'),
  ('invt.delete', 'invoiceTitles', '删除'),
  ('invt.delFail', 'invoiceTitles', '删除失败，请稍后再试'),
  ('invt.delOk', 'invoiceTitles', '抬头已删除'),
  ('invt.edit', 'invoiceTitles', '编辑'),
  ('invt.editTitle', 'invoiceTitles', '编辑抬头'),
  ('invt.emptyBody', 'invoiceTitles', '保存常用抬头，申请发票时一键回填'),
  ('invt.emptyCta', 'invoiceTitles', '新增抬头'),
  ('invt.emptyTitle', 'invoiceTitles', '还没有发票抬头'),
  ('invt.loadFail', 'invoiceTitles', '抬头加载失败，请检查网络后重试'),
  ('invt.pickCta', 'invoiceTitles', '选常用抬头 ›'),
  ('invt.pickTitle', 'invoiceTitles', '选择常用抬头'),
  ('invt.pushLabel', 'invoiceTitles', 'INVOICE TITLES'),
  ('invt.save', 'invoiceTitles', '保存'),
  ('invt.saveFail', 'invoiceTitles', '保存失败，请稍后再试'),
  ('invt.saveOk', 'invoiceTitles', '抬头已保存'),
  ('invt.saving', 'invoiceTitles', '保存中…'),
  ('invt.setDefault', 'invoiceTitles', '设为默认抬头'),
  ('invt.taxNoLabel', 'invoiceTitles', '税号（统一社会信用代码）'),
  ('invt.taxNoPlaceholder', 'invoiceTitles', '企业抬头必填'),
  ('invt.taxNoRequired', 'invoiceTitles', '企业抬头须填写税号'),
  ('invt.title', 'invoiceTitles', '发票抬头'),
  ('invt.titleLabel', 'invoiceTitles', '抬头名称'),
  ('invt.titlePlaceholderBusiness', 'invoiceTitles', '输入企业全称'),
  ('invt.titlePlaceholderPersonal', 'invoiceTitles', '输入姓名'),
  ('invt.titleRequired', 'invoiceTitles', '请填写抬头名称'),
  ('invt.typeBusiness', 'invoiceTitles', '企业'),
  ('invt.typeLabel', 'invoiceTitles', '抬头类型'),
  ('invt.typePersonal', 'invoiceTitles', '个人'),
  ('profile.avatarChange', 'profile', '更换头像'),
  ('profile.avatarLabel', 'profile', '头像'),
  ('profile.birthdayLabel', 'profile', '生日'),
  ('profile.genderFemale', 'profile', '女'),
  ('profile.genderLabel', 'profile', '性别'),
  ('profile.genderMale', 'profile', '男'),
  ('profile.genderSecret', 'profile', '保密'),
  ('profile.loadFail', 'profile', '资料加载失败，请检查网络后重试'),
  ('profile.meEntry', 'profile', '编辑资料'),
  ('profile.meEntrySub', 'profile', '头像 · 昵称 · 生日 · 性别'),
  ('profile.nicknameLabel', 'profile', '昵称'),
  ('profile.nicknamePlaceholder', 'profile', '输入昵称'),
  ('profile.nicknameRequired', 'profile', '昵称不能为空'),
  ('profile.pushLabel', 'profile', 'PROFILE'),
  ('profile.save', 'profile', '保存'),
  ('profile.saveFail', 'profile', '保存失败，请稍后再试'),
  ('profile.saveOk', 'profile', '资料已保存'),
  ('profile.saving', 'profile', '保存中…'),
  ('profile.title', 'profile', '编辑资料'),
  ('profile.uploadFail', 'profile', '头像上传失败，请重试'),
  ('profile.uploading', 'profile', '上传中…'),
  ('rec.depHeld', 'records', '在押'),
  ('rec.depHeldAt', 'records', '收取 {time}'),
  ('rec.depositEmpty', 'records', '暂无押金记录'),
  ('rec.depositNote', 'records', '押金收退=门店登记留痕，进度以此为准'),
  ('rec.depositTitle', 'records', '押金进度'),
  ('rec.depRefunded', 'records', '已退还'),
  ('rec.depRefundedAt', 'records', '退还完成 {time}'),
  ('rec.depRefunding', 'records', '退还在途'),
  ('rec.depRefundReqAt', 'records', '申请退还 {time}'),
  ('rec.emptyBody', 'records', '支付单、商城订单与发票记录会在这里汇总'),
  ('rec.emptyCta', 'records', '去商城逛逛 ›'),
  ('rec.emptyTitle', 'records', '还没有消费记录'),
  ('rec.kindInvoice', 'records', '发票'),
  ('rec.kindOrder', 'records', '订单'),
  ('rec.kindPay', 'records', '支付'),
  ('rec.loadFail', 'records', '记录加载失败，请检查网络后重试'),
  ('rec.meEntry', 'records', '消费记录'),
  ('rec.meEntrySub', 'records', '支付 · 订单 · 发票 · 押金'),
  ('rec.pushLabel', 'records', 'RECORDS'),
  ('rec.title', 'records', '消费记录')
)
INSERT INTO `copy_overrides` (`id`,`version`,`rule_key`,`label`,`value_json`,`effective_from`,`active`,`created_by`,`created_at`,`updated_at`)
SELECT 'seedcopy_' || lower(hex(randomblob(8))), 1, s.rule_key, s.label, json_object('text', s.text), unixepoch(), 1, 'system', unixepoch(), unixepoch()
FROM s
WHERE NOT EXISTS (SELECT 1 FROM `copy_overrides` WHERE `rule_key` = s.rule_key AND `active` = 1);
