-- 客户端体验大批片 3：copy_overrides 增量种子（会员体系+商城新增 ${delta.length} 键随批注册；片 B 纪律）
-- 幂等：rule_key active 行 NOT EXISTS 守卫；created_by='system'；迁移执行器 PRAGMA foreign_keys=OFF。
-- 生成件=scripts/gen-copy-overrides-seed.mts 重跑产物（copySeedRows.ts 同帧）。
WITH s(rule_key, label, text) AS (VALUES
  ('cpn.centerEmpty', 'coupons', '暂时没有可领的券'),
  ('cpn.centerTitle', 'coupons', '领用中心'),
  ('cpn.claimCta', 'coupons', '领取'),
  ('cpn.claimedAt', 'coupons', '领取 {time}'),
  ('cpn.claimedCta', 'coupons', '已领取'),
  ('cpn.claimFail', 'coupons', '领取失败，请稍后再试'),
  ('cpn.claimToast', 'coupons', '已领取，结算时出示登记抵扣'),
  ('cpn.loadFail', 'coupons', '券加载失败，请稍后重试'),
  ('cpn.mineEmpty', 'coupons', '还没有券，去领用中心看看'),
  ('cpn.mineTitle', 'coupons', '我的券'),
  ('cpn.pushLabel', 'coupons', 'COUPONS'),
  ('cpn.soldOutCta', 'coupons', '已领完'),
  ('cpn.stackTitle', 'coupons', '叠加规则公示'),
  ('cpn.statusClaimed', 'coupons', '待使用'),
  ('cpn.statusExpired', 'coupons', '已过期'),
  ('cpn.statusUsed', 'coupons', '已核销'),
  ('cpn.statusVoided', 'coupons', '已作废'),
  ('cpn.tabMine', 'coupons', '优惠券'),
  ('cpn.threshold', 'coupons', '满 {amt} 可用'),
  ('cpn.thresholdNone', 'coupons', '无门槛'),
  ('cpn.title', 'coupons', '优惠券'),
  ('cpn.usedAt', 'coupons', '核销 {time}'),
  ('cpn.useNote', 'coupons', '核销=登记抵扣，线下结算时出示'),
  ('cpn.validDays', 'coupons', '领取后 {days} 天有效'),
  ('fav.addToast', 'favorites', '已加入心愿单'),
  ('fav.emptyBody', 'favorites', '看中的好物点右上角小心心，会在这里等你'),
  ('fav.emptyCta', 'favorites', '去商城逛逛 ›'),
  ('fav.emptyTitle', 'favorites', '心愿单还空着呢'),
  ('fav.loadFail', 'favorites', '心愿单加载失败，请稍后重试'),
  ('fav.mallEntry', 'favorites', '心愿单'),
  ('fav.pdpAdd', 'favorites', '加入心愿单'),
  ('fav.pdpAdded', 'favorites', '已收藏'),
  ('fav.removeToast', 'favorites', '已移出心愿单'),
  ('fav.title', 'favorites', '心愿单'),
  ('fav.toggleFail', 'favorites', '操作失败，请稍后再试'),
  ('mall.addrOptionalNote', 'mall', '自提 / 同城可暂不填收货地址，到店报手机号即可'),
  ('mall.couponOff', 'mall', '减 {amt}'),
  ('mall.couponPick', 'mall', '选用'),
  ('mall.couponPicked', 'mall', '已选 · 登记抵扣'),
  ('mall.couponTitle', 'mall', '可用券'),
  ('mall.couponUseNote', 'mall', '核销=登记抵扣，线下结算时出示'),
  ('mall.deliveryExpress', 'mall', '快递'),
  ('mall.deliveryFreeNote', 'mall', '内测期免运费'),
  ('mall.deliveryMethod', 'mall', '配送方式'),
  ('mall.deliveryPickup', 'mall', '自提'),
  ('mall.deliverySameCity', 'mall', '同城'),
  ('mall.trackingNote', 'mall', '轨迹以快递公司为准'),
  ('perk.grantedAt', 'member', '发放 {time}'),
  ('perk.kindBirthdayOwner', 'member', '生日礼 · 主人'),
  ('perk.kindBirthdayPet', 'member', '生日礼 · 宠物'),
  ('perk.kindCarePack', 'member', '安心包'),
  ('perk.kindFallback', 'member', '权益'),
  ('perk.kindNewbie', 'member', '新人礼包'),
  ('perk.kindServiceDiscount', 'member', '服务折扣次数'),
  ('perk.kindUpgrade', 'member', '升级礼遇'),
  ('perk.ledgerNote', 'member', '权益台账=资格留痕，发放候资质批'),
  ('perk.passTimesLine', 'member', '次卡剩余 {n} 次'),
  ('perk.remainLine', 'member', '剩余 {remain} / 共 {total} 次'),
  ('perk.renewOff', 'member', '续费 {zhe} 折 · 折后 ¥{amount}'),
  ('perk.unusedEmpty', 'member', '暂无未用权益'),
  ('perk.unusedTitle', 'member', '未用权益'),
  ('perk.usedUp', 'member', '已用完'),
  ('q1.tokenFail', 'member', '会员码加载失败'),
  ('q1.tokenRetry', 'member', '重试'),
  ('q1.tokenTitle', 'member', '会员码'),
  ('q1.verifyNote', 'member', '核验走收银台 · 店员扫录或核对码文本'),
  ('rev.anonymous', 'productReviews', '匿名评价'),
  ('rev.anonymousName', 'productReviews', '匿名用户'),
  ('rev.empty', 'productReviews', '还没有评价，收货后来写第一条'),
  ('rev.loadFail', 'productReviews', '评价加载失败，请稍后重试'),
  ('rev.more', 'productReviews', '加载更多'),
  ('rev.needReceived', 'productReviews', '确认收货后即可评价本商品'),
  ('rev.orderEntry', 'productReviews', '写评价'),
  ('rev.photoAdd', 'productReviews', '晒图'),
  ('rev.photoLimit', 'productReviews', '最多 3 张'),
  ('rev.ratingLabel', 'productReviews', '评分'),
  ('rev.sheetTitle', 'productReviews', '写评价'),
  ('rev.submit', 'productReviews', '提交评价'),
  ('rev.submitFail', 'productReviews', '评价提交失败，请稍后再试'),
  ('rev.submitting', 'productReviews', '提交中…'),
  ('rev.summary', 'productReviews', '{avg} 分 · {count} 条评价'),
  ('rev.textPlaceholder', 'productReviews', '说说商品怎么样…（可不填）'),
  ('rev.title', 'productReviews', '商品评价'),
  ('rev.toastOk', 'productReviews', '评价已提交'),
  ('rev.writeCta', 'productReviews', '写评价')
)
INSERT INTO `copy_overrides` (`id`,`version`,`rule_key`,`label`,`value_json`,`effective_from`,`active`,`created_by`,`created_at`,`updated_at`)
SELECT 'seedcopy_' || lower(hex(randomblob(8))), 1, s.rule_key, s.label, json_object('text', s.text), unixepoch(), 1, 'system', unixepoch(), unixepoch()
FROM s
WHERE NOT EXISTS (SELECT 1 FROM `copy_overrides` WHERE `rule_key` = s.rule_key AND `active` = 1);
