-- 客户端体验大批 片 4：copy_overrides 增量种子（服务过程/软性体验/通知触达/触达配套/品牌 19 件新增 92 键随批注册；
-- 域分布=health（新域）/appointments/serviceloop/pets/home（PWA 引导条））
-- 幂等：rule_key active 行 NOT EXISTS 守卫（存量库只补差、重放零副作用）；created_by='system'
-- （迁移执行器 PRAGMA foreign_keys=OFF，惯例见 migrate.ts 头注）。
-- 生成件=scripts/gen-copy-overrides-seed.mts 重跑产物（server/src/db/copySeedRows.ts 同帧）。
WITH s(rule_key, label, text) AS (VALUES
  ('appointments.assuranceBelongings', 'appointments', '随身物品'),
  ('appointments.assuranceEmpty', 'appointments', '待入住登记'),
  ('appointments.assuranceEmptyBody', 'appointments', '店员办理入住后，房间、体重与物品清单会在这里更新'),
  ('appointments.assuranceLatestLog', 'appointments', '最新打卡'),
  ('appointments.assuranceLogDone', 'appointments', '当日照护已完成打卡'),
  ('appointments.assuranceNoLog', 'appointments', '暂无打卡记录'),
  ('appointments.assuranceRoom', 'appointments', '房间'),
  ('appointments.assuranceTitle', 'appointments', '寄养安心卡'),
  ('appointments.assuranceUnsealEmpty', 'appointments', '暂无拆封记录'),
  ('appointments.assuranceUnsealTitle', 'appointments', '拆封留痕'),
  ('appointments.assuranceWeight', 'appointments', '入住体重'),
  ('appointments.detailSheetTitle', 'appointments', '服务明细'),
  ('appointments.incidentHandledLine', 'appointments', '异常已处置：{note}'),
  ('appointments.incidentHandling', 'appointments', '门店处理中'),
  ('appointments.incidentOccurredAt', 'appointments', '发生于 {time}'),
  ('appointments.incidentTitle', 'appointments', '异常通报'),
  ('appointments.incidentToastHandled', 'appointments', '异常情况已处置，可下滑查看说明'),
  ('appointments.incidentToastReported', 'appointments', '{pet}有异常通报，门店正在处理'),
  ('appointments.incidentTypeInjury', 'appointments', '受伤'),
  ('appointments.incidentTypeStress', 'appointments', '应激'),
  ('appointments.incidentTypeVetVisit', 'appointments', '就医'),
  ('appointments.materialQty', 'appointments', '× {n}'),
  ('appointments.materialsEmpty', 'appointments', '本单无耗材扣减记录'),
  ('appointments.materialsTitle', 'appointments', '耗材使用'),
  ('appointments.roomPending', 'appointments', '待分配'),
  ('appointments.stepDoing', 'appointments', '进行中'),
  ('appointments.stepDone', 'appointments', '已完成'),
  ('appointments.stepDuration', 'appointments', '{min} 分钟'),
  ('appointments.stepPending', 'appointments', '待开始'),
  ('appointments.unsealToast', 'appointments', '{pet}的用品「{item}」已拆封使用'),
  ('health.dueExpired', 'health', '已过期 {date}'),
  ('health.dueOk', 'health', '下次到期 {date}'),
  ('health.dueSoon', 'health', '下次到期 {date} · {days} 天后'),
  ('health.loadFail', 'health', '健康档案加载失败'),
  ('health.recordAddTitle', 'health', '记一笔'),
  ('health.recordDateLabel', 'health', '发生日期'),
  ('health.recordDelete', 'health', '删除'),
  ('health.recordDeleteConfirm', 'health', '再点一次确认删除'),
  ('health.recordDeleted', 'health', '记录已删除'),
  ('health.recordNextDueLabel', 'health', '下次到期日（可选）'),
  ('health.recordNoteLabel', 'health', '备注（可选）'),
  ('health.recordNotePlaceholder', 'health', '如：宠物医院名称 / 剂量'),
  ('health.recordsTabEmpty', 'health', '暂无{type}记录'),
  ('health.recordsTitle', 'health', '健康记录'),
  ('health.recordSubmit', 'health', '保存记录'),
  ('health.recordTitleLabel', 'health', '标题'),
  ('health.recordTitlePlaceholder', 'health', '如：狂犬疫苗第三针'),
  ('health.recordTypeLabel', 'health', '类型'),
  ('health.saveFail', 'health', '保存失败，请稍后重试'),
  ('health.saving', 'health', '保存中…'),
  ('health.tabDeworm', 'health', '驱虫'),
  ('health.tabMedication', 'health', '用药'),
  ('health.tabVaccine', 'health', '疫苗'),
  ('health.tabVetVisit', 'health', '就医'),
  ('health.title', 'health', '健康档案'),
  ('health.weightAddTitle', 'health', '记体重'),
  ('health.weightDateLabel', 'health', '称重日期'),
  ('health.weightEmptyBody', 'health', '定期称重，掌握 TA 的健康变化'),
  ('health.weightEmptyTitle', 'health', '还没有体重记录'),
  ('health.weightKgLabel', 'health', '体重（kg）'),
  ('health.weightKgPlaceholder', 'health', '如：4.5'),
  ('health.weightNoteLabel', 'health', '备注（可选）'),
  ('health.weightSubmit', 'health', '保存体重'),
  ('health.weightTrend', 'health', '体重趋势'),
  ('health.weightUnit', 'health', 'kg'),
  ('home.pwaInstallAction', 'home', '安装'),
  ('home.pwaInstallDismiss', 'home', '暂不'),
  ('home.pwaInstallIosGuide', 'home', '用 Safari 分享 → 添加到主屏幕'),
  ('home.pwaInstallTitle', 'home', '把菲丽亚装到主屏'),
  ('pets.chipNoLabel', 'pets', '芯片号'),
  ('pets.chipNoPlaceholder', 'pets', '如：900123456789012'),
  ('pets.coatColorLabel', 'pets', '花色'),
  ('pets.coatColorPlaceholder', 'pets', '如：橘白 / 三花'),
  ('pets.healthEntry', 'pets', '健康档案 ›'),
  ('pets.switcherAll', 'pets', '全部宠物'),
  ('pets.switcherFail', 'pets', '切换失败，请稍后重试'),
  ('pets.switcherSingleNote', 'pets', '单宠档案已选定'),
  ('pets.switcherTitle', 'pets', '切换宠物'),
  ('ticket.escalateCancel', 'serviceloop', '再想想'),
  ('ticket.escalateCta', 'serviceloop', '申请店长介入'),
  ('ticket.escalatedAtLine', 'serviceloop', '升级于 {time}'),
  ('ticket.escalatedBadge', 'serviceloop', '已升级店长介入'),
  ('ticket.escalateDesc', 'serviceloop', '店长会亲自跟进处理你的工单'),
  ('ticket.escalateDone', 'serviceloop', '已升级，店长会亲自跟进'),
  ('ticket.escalateFail', 'serviceloop', '升级失败，请稍后重试'),
  ('ticket.escalateNoteLabel', 'serviceloop', '补充说明（选填）'),
  ('ticket.escalateNotePlaceholder', 'serviceloop', '告诉店长你还希望解决什么…'),
  ('ticket.escalateNoteTitle', 'serviceloop', '升级说明'),
  ('ticket.escalateSubmit', 'serviceloop', '确认升级'),
  ('ticket.escalateTitle', 'serviceloop', '申请店长介入'),
  ('ticket.statusEscalated', 'serviceloop', '已升级店长介入'),
  ('ticket.timelineEscalated', 'serviceloop', '申请店长介入')
)
INSERT INTO `copy_overrides` (`id`,`version`,`rule_key`,`label`,`value_json`,`effective_from`,`active`,`created_by`,`created_at`,`updated_at`)
SELECT 'seedcopy_' || lower(hex(randomblob(8))), 1, s.rule_key, s.label, json_object('text', s.text), unixepoch(), 1, 'system', unixepoch(), unixepoch()
FROM s
WHERE NOT EXISTS (SELECT 1 FROM `copy_overrides` WHERE `rule_key` = s.rule_key AND `active` = 1);
