-- 客户端体验大批 片 5：copy_overrides 增量种子（报表目录 17 张点亮+CSV 导入+申诉通道+尾牙四格，新增 201 键随批注册；
-- 域分布=report/orders/products（merchant）+reviews（staff）+ops（merchant））
-- 幂等：rule_key active 行 NOT EXISTS 守卫（存量库只补差、重放零副作用）；created_by='system'
-- （迁移执行器 PRAGMA foreign_keys=OFF，惯例见 migrate.ts 头注）。
-- 生成件=scripts/gen-copy-overrides-seed.mts 重跑产物（server/src/db/copySeedRows.ts 同帧）。
WITH s(rule_key, label, text) AS (VALUES
  ('ops.appeal.afterLabel', 'merchant:ops', '纠错后取值'),
  ('ops.appeal.afterPh', 'merchant:ops', '如：差评归属更正 / 更正后 79'),
  ('ops.appeal.approveCta', 'merchant:ops', '通过（纠错）'),
  ('ops.appeal.approveDone', 'merchant:ops', '申诉已通过，纠错留痕已登记'),
  ('ops.appeal.approveNotePh', 'merchant:ops', '复核意见（可选）'),
  ('ops.appeal.approveTitle', 'merchant:ops', '通过申诉 · 纠错留痕'),
  ('ops.appeal.aside', 'merchant:ops', '差评归属/报表指标异议；通过必留纠错前后值'),
  ('ops.appeal.beforeLabel', 'merchant:ops', '纠错前取值'),
  ('ops.appeal.beforePh', 'merchant:ops', '如：差评误挂到该员工 / 指标原值 82'),
  ('ops.appeal.correctionLabel', 'merchant:ops', '纠错留痕'),
  ('ops.appeal.correctionNotePh', 'merchant:ops', '纠错说明（可选）'),
  ('ops.appeal.correctionRequired', 'merchant:ops', '通过必须填写纠错前后值——兜底留痕铁规'),
  ('ops.appeal.empty', 'merchant:ops', '暂无待复核申诉'),
  ('ops.appeal.reasonLabel', 'merchant:ops', '申诉理由'),
  ('ops.appeal.rejectCta', 'merchant:ops', '驳回'),
  ('ops.appeal.rejectDone', 'merchant:ops', '申诉已驳回'),
  ('ops.appeal.rejectNotePh', 'merchant:ops', '复核意见（必填，随单留痕）'),
  ('ops.appeal.rejectNoteRequired', 'merchant:ops', '驳回必须填写复核意见'),
  ('ops.appeal.rejectTitle', 'merchant:ops', '驳回申诉'),
  ('ops.appeal.reviewedAtLabel', 'merchant:ops', '复核时间'),
  ('ops.appeal.reviewedTitle', 'merchant:ops', '已复核（近 50 条）'),
  ('ops.appeal.reviewNoteLabel', 'merchant:ops', '复核意见'),
  ('ops.appeal.statusApproved', 'merchant:ops', '已通过'),
  ('ops.appeal.statusRejected', 'merchant:ops', '已驳回'),
  ('ops.appeal.targetMetric', 'merchant:ops', '报表指标'),
  ('ops.appeal.targetReview', 'merchant:ops', '差评归属'),
  ('ops.appeal.title', 'merchant:ops', '指标申诉复核'),
  ('prod.csvAllOk', 'merchant:products', '全部合法，可确认导入'),
  ('prod.csvClose', 'merchant:products', '收起'),
  ('prod.csvDone', 'merchant:products', '导入成功 {n} 行'),
  ('prod.csvExecuteCta', 'merchant:products', '确认导入'),
  ('prod.csvFileCta', 'merchant:products', '选择 CSV 文件'),
  ('prod.csvImportTitle', 'merchant:products', 'CSV 批量导入'),
  ('prod.csvNoFile', 'merchant:products', '请先选择 CSV 文件'),
  ('prod.csvPreviewCta', 'merchant:products', '预览校验'),
  ('prod.csvSummary', 'merchant:products', '共 {t} 行 · 可导入 {ok} · 失败 {f}'),
  ('prod.csvTemplateCta', 'merchant:products', '下载模板'),
  ('rpt.d1.amortCard', 'merchant:report', '分摊口径 ②'),
  ('rpt.d1.amortSub', 'merchant:report', '服务+商品+年费按 12 月分摊（防收钱当月虚胖）'),
  ('rpt.d1.byDayTitle', 'merchant:report', '逐日营收'),
  ('rpt.d1.cashCard', 'merchant:report', '收现口径 ①'),
  ('rpt.d1.cashSub', 'merchant:report', '服务+商品+年费收现'),
  ('rpt.d1.guestLabel', 'merchant:report', '散客'),
  ('rpt.d1.memberLabel', 'merchant:report', '会员'),
  ('rpt.d1.memberShareTitle', 'merchant:report', '会员 vs 散客消费占比'),
  ('rpt.d1.momLabel', 'merchant:report', '环比'),
  ('rpt.d1.noBase', 'merchant:report', '无基数'),
  ('rpt.d1.nonCashNote', 'merchant:report', '非现金单列（不计已收）：次卡 {pass} · 储值 {sv} · 回馈金 {rb}'),
  ('rpt.d1.yoyLabel', 'merchant:report', '同比'),
  ('rpt.d2.attachCard', 'merchant:report', '附加项目搭售率'),
  ('rpt.d2.attachSub', 'merchant:report', '搭售 {n}/{t} 单 · 附加金额 {amt}'),
  ('rpt.d2.tableTitle', 'merchant:report', '按服务项构成'),
  ('rpt.d3.active90Card', 'merchant:report', '90 天活跃率'),
  ('rpt.d3.active90Sub', 'merchant:report', '{n}/{t} 人 90 天内有交易'),
  ('rpt.d3.activeCard', 'merchant:report', '存量活跃会员'),
  ('rpt.d3.byPlanTitle', 'merchant:report', '本月新增按档分布'),
  ('rpt.d3.newCard', 'merchant:report', '本月新增会员'),
  ('rpt.d4.deductedCard', 'merchant:report', '本月扣次'),
  ('rpt.d4.grantedCard', 'merchant:report', '本月售卡充次'),
  ('rpt.d4.remainCard', 'merchant:report', '剩余次数负债'),
  ('rpt.d4.stockSub', 'merchant:report', '在册 {n} 张 · 总 {t} 次'),
  ('rpt.d4.trendTitle', 'merchant:report', '近 6 月扣次趋势'),
  ('rpt.d5.consumeCard', 'merchant:report', '本月消耗'),
  ('rpt.d5.liabilityCard', 'merchant:report', '期末储值负债'),
  ('rpt.d5.prepaidRow', 'merchant:report', '预收负债总额（储值 ¥{sv} + 回馈金 ¥{rb}）'),
  ('rpt.d5.rechargeCard', 'merchant:report', '本月充值'),
  ('rpt.d6.amountCard', 'merchant:report', '退款金额'),
  ('rpt.d6.byTypeTitle', 'merchant:report', '类型分布'),
  ('rpt.d6.countCard', 'merchant:report', '退款笔数（已执行+已实退）'),
  ('rpt.d6.linkedBad', 'merchant:report', '退款关联差评 {n} 件'),
  ('rpt.d6.reasonTitle', 'merchant:report', '申请原因聚类'),
  ('rpt.d6.rejectCard', 'merchant:report', '申请驳回率'),
  ('rpt.d6.rejectSub', 'merchant:report', '{r}/{t} 件被驳回'),
  ('rpt.d6.spikeNa', 'merchant:report', '上月无退款基数，环比不出数'),
  ('rpt.d6.spikeOk', 'merchant:report', '退款金额环比 {pct}（预警阈值 {th}）'),
  ('rpt.d6.spikeWarn', 'merchant:report', '退款金额环比 +{pct}，超预警阈值（{th}）——请核查异常'),
  ('rpt.d7.tableTitle', 'merchant:report', '员工 × 绩效交叉'),
  ('rpt.d8.attachCard', 'merchant:report', '增值服务搭售率'),
  ('rpt.d8.nightsCard', 'merchant:report', '宠物夜数'),
  ('rpt.d8.occCard', 'merchant:report', '入住率'),
  ('rpt.d8.occSub', 'merchant:report', '{pets} 宠物夜 / 容量 {cap} 晚'),
  ('rpt.d8.overdueCard', 'merchant:report', '超期单数'),
  ('rpt.d8.perNightCard', 'merchant:report', '每宠物夜营收'),
  ('rpt.d9.byProductTitle', 'merchant:report', '按商品明细'),
  ('rpt.d9.ordersSub', 'merchant:report', '成交 {n} 单'),
  ('rpt.d9.salesCard', 'merchant:report', '销售额'),
  ('rpt.d9.sellThroughCard', 'merchant:report', '动销率'),
  ('rpt.d9.turnoverCard', 'merchant:report', '周转天数'),
  ('rpt.d9.unitsCard', 'merchant:report', '销量（件）'),
  ('rpt.dirAside', 'merchant:report', '17 张已点亮 · 导出 CSV 仅店主'),
  ('rpt.dirEmbedBadge', 'merchant:report', '埋点预埋中'),
  ('rpt.dirN1', 'merchant:report', 'N1 等级分布与升级'),
  ('rpt.dirN2', 'merchant:report', 'N2 续费与回本'),
  ('rpt.dirN3', 'merchant:report', 'N3 回馈金发行核销'),
  ('rpt.dirN4', 'merchant:report', 'N4 评价分布与差评'),
  ('rpt.dirN5', 'merchant:report', 'N5 交付合规与时效'),
  ('rpt.dirN6', 'merchant:report', 'N6 员工×服务质量'),
  ('rpt.dirN7', 'merchant:report', 'N7 内容曝光互动'),
  ('rpt.dirN8', 'merchant:report', 'N8 种草预约归因'),
  ('rpt.embed.ev1', 'merchant:report', 'case_impression 案例曝光'),
  ('rpt.embed.ev2', 'merchant:report', 'case_detail_view 案例详情浏览'),
  ('rpt.embed.ev3', 'merchant:report', 'case_dwell 案例停留时长'),
  ('rpt.embed.ev4', 'merchant:report', 'case_read_finish 案例读完'),
  ('rpt.embed.ev5', 'merchant:report', 'case_interact 案例互动'),
  ('rpt.embed.ev6', 'merchant:report', 'book_same_impression 预约同款曝光'),
  ('rpt.embed.ev7', 'merchant:report', 'book_same_click 预约同款点击'),
  ('rpt.embed.ev8', 'merchant:report', 'booking_attributed 预约归因'),
  ('rpt.embed.ev9', 'merchant:report', 'booking_verified 到店核销确认'),
  ('rpt.embed.eventsTitle', 'merchant:report', '九类预埋事件（名单写死）'),
  ('rpt.embed.intro', 'merchant:report', '本报表为埋点预埋项：埋点底座已落（content_events 九类事件写口+读数），出表排期=瀑布流批——本页先实证预埋有效性'),
  ('rpt.embed.outNote', 'merchant:report', '出表=瀑布流批（H 表 §方向三清单）；导出 CSV 不对预埋项开放（server 400 明文）'),
  ('rpt.embed.statsEmpty', 'merchant:report', '暂无事件落账——写口就绪，待客户端行为接入'),
  ('rpt.embed.statsTitle', 'merchant:report', '预埋有效性实证（本店事件计数）'),
  ('rpt.n1.cohortTitle', 'merchant:report', '入会月份 cohort（新增 → 至今仍活跃）'),
  ('rpt.n1.downgradeCard', 'merchant:report', '降级率'),
  ('rpt.n1.exitCard', 'merchant:report', '本月退出'),
  ('rpt.n1.newTitle', 'merchant:report', '本月新增按档'),
  ('rpt.n1.stockTitle', 'merchant:report', '四档存量（活跃会员）'),
  ('rpt.n1.upDownSub', 'merchant:report', '升级 {u} · 降级 {d}（分母=期初存量）'),
  ('rpt.n1.upgradeCard', 'merchant:report', '升级率'),
  ('rpt.n2.cohortTitle', 'merchant:report', '到期 cohort 续费率（近 6 月+本月）'),
  ('rpt.n2.paybackCard', 'merchant:report', '回本率（店级均值）'),
  ('rpt.n2.paybackDetailTitle', 'merchant:report', '逐员回本明细'),
  ('rpt.n2.paybackSub', 'merchant:report', '{n} 位活跃会员 · 年费 ¥{paid} · 实省 ¥{saved}'),
  ('rpt.n2.warnEmpty', 'merchant:report', '30 天内无到期会员'),
  ('rpt.n2.warnTitle', 'merchant:report', '到期预警名单（30 天内）'),
  ('rpt.n3.closingCard', 'merchant:report', '期末回馈金负债'),
  ('rpt.n3.redeemCard', 'merchant:report', '核销率'),
  ('rpt.n3.redeemSub', 'merchant:report', '基准 20-35% · 累计发行 ¥{g} · 核销 ¥{d}'),
  ('rpt.n3.rollNote', 'merchant:report', '滚动恒等式：期初 + 发行 − 核销 − 过期/破损 = 期末'),
  ('rpt.n3.rollTitle', 'merchant:report', '按期次滚动'),
  ('rpt.n4.avgCard', 'merchant:report', '平均评分'),
  ('rpt.n4.badRateCard', 'merchant:report', '差评率（纠错扣减后）'),
  ('rpt.n4.byServiceTitle', 'merchant:report', '按服务'),
  ('rpt.n4.byStaffTitle', 'merchant:report', '按员工'),
  ('rpt.n4.correctedRow', 'merchant:report', '含纠错 {n} 件——approved 申诉已从差评指标即时扣减（附录 B 兜底口径）'),
  ('rpt.n4.distTitle', 'merchant:report', '星级分布'),
  ('rpt.n4.minutesVal', 'merchant:report', '{n} 分钟'),
  ('rpt.n4.recentAside', 'merchant:report', '近十条 · 全时段口径（非同月过滤）'),
  ('rpt.n4.recentEmpty', 'merchant:report', '暂无差评'),
  ('rpt.n4.recentTitle', 'merchant:report', '差评明细与回复'),
  ('rpt.n4.repliedBadge', 'merchant:report', '已回复'),
  ('rpt.n4.replyCancel', 'merchant:report', '取消'),
  ('rpt.n4.replyCta', 'merchant:report', '回复 ›'),
  ('rpt.n4.replyDone', 'merchant:report', '已回复该差评'),
  ('rpt.n4.replyPlaceholder', 'merchant:report', '填写回复内容（500 字内）…'),
  ('rpt.n4.replyRateCard', 'merchant:report', '差评回复率'),
  ('rpt.n4.replySubmit', 'merchant:report', '提交回复'),
  ('rpt.n4.replyTagsLabel', 'merchant:report', '原因标签（可多选，最多 5 个）'),
  ('rpt.n4.replyTimeCard', 'merchant:report', '平均回复时效'),
  ('rpt.n4.tagTitle', 'merchant:report', '差评标签聚类'),
  ('rpt.n5.actualCard', 'merchant:report', '实际时长（均值）'),
  ('rpt.n5.bucket120', 'merchant:report', '30–120 分钟'),
  ('rpt.n5.bucket30', 'merchant:report', '5–30 分钟'),
  ('rpt.n5.bucket5', 'merchant:report', '≤5 分钟'),
  ('rpt.n5.bucketOver', 'merchant:report', '>120 分钟'),
  ('rpt.n5.bucketsTitle', 'merchant:report', '报告送达时效分布'),
  ('rpt.n5.bucketUnread', 'merchant:report', '未读'),
  ('rpt.n5.completedCard', 'merchant:report', '本月完成服务单'),
  ('rpt.n5.photoCard', 'merchant:report', '照片覆盖率'),
  ('rpt.n5.photoSub', 'merchant:report', '实传 {n} 张'),
  ('rpt.n5.sampleCard', 'merchant:report', '抽检率（打标重拍步占比）'),
  ('rpt.n5.stdCard', 'merchant:report', '标准时长（均值）'),
  ('rpt.n6.gateTitle', 'merchant:report', '海底捞铁规两件（附录 B）'),
  ('rpt.n6.queueEmpty', 'merchant:report', '暂无申诉记录'),
  ('rpt.n6.queueGo', 'merchant:report', '去审批中心 ›'),
  ('rpt.n6.queueTitle', 'merchant:report', '申诉队列（metric_appeals）'),
  ('rpt.n6.statusApproved', 'merchant:report', '已采纳'),
  ('rpt.n6.statusPending', 'merchant:report', '待复核'),
  ('rpt.n6.statusRejected', 'merchant:report', '已驳回'),
  ('rpt.n6.tableTitle', 'merchant:report', '员工 × 服务质量交叉'),
  ('rpt.page.actionFail', 'merchant:report', '操作失败，请重试'),
  ('rpt.page.backToDir', 'merchant:report', '‹ 返回报表目录'),
  ('rpt.page.empty', 'merchant:report', '该月暂无数据'),
  ('rpt.page.exportCta', 'merchant:report', '导出 CSV'),
  ('rpt.page.exportDone', 'merchant:report', '已导出 {name}（{n} 行）'),
  ('rpt.page.exportFail', 'merchant:report', '导出失败，请重试'),
  ('rpt.page.exporting', 'merchant:report', '导出中…'),
  ('rpt.page.exportOwnerOnly', 'merchant:report', '导出 CSV 仅店主（总规则③）'),
  ('rpt.page.loadError', 'merchant:report', '报表加载失败，请检查网络后重试'),
  ('rpt.page.monthLabel', 'merchant:report', '报表月份'),
  ('rpt.page.noteLead', 'merchant:report', '口径：'),
  ('rpt.page.retry', 'merchant:report', '重新加载'),
  ('rpt.page.unknown', 'merchant:report', '未知报表键'),
  ('rpt.quadRebateSub', 'merchant:report', '{n} 户会员回馈金余额'),
  ('rpt.quadStoredSub', 'merchant:report', '{n} 户 · 本金+赠送合计'),
  ('rpt.quadYesterday', 'merchant:report', '昨日营收'),
  ('rpt.quadYesterdayClose', 'merchant:report', '日结对账：{n} 箱 · 账面现金 ¥{amt}'),
  ('rpt.quadYesterdayNoClose', 'merchant:report', '昨日未封箱（日结行缺）'),
  ('rpt.quadYesterdaySub', 'merchant:report', '{date} · {n} 笔已收'),
  ('rpt.sparkNote', 'merchant:report', '今日格=截至当前已收 · financeStats 同源口径'),
  ('rpt.sparkTitle', 'merchant:report', '近 14 日营收走势'),
  ('reviews.appeal.cancel', 'staff:reviews', '取消'),
  ('reviews.appeal.cta', 'staff:reviews', '申诉'),
  ('reviews.appeal.duplicated', 'staff:reviews', '该评价已有申诉在途，请等待复核'),
  ('reviews.appeal.pending', 'staff:reviews', '已申诉待复核'),
  ('reviews.appeal.placeholder', 'staff:reviews', '请说明申诉理由（必填，500 字内，店长复核时可见）'),
  ('reviews.appeal.required', 'staff:reviews', '请填写申诉理由'),
  ('reviews.appeal.submit', 'staff:reviews', '提交申诉'),
  ('reviews.appeal.title', 'staff:reviews', '申诉该评价'),
  ('reviews.appeal.toast', 'staff:reviews', '申诉已提交，待店长复核')
)
INSERT INTO `copy_overrides` (`id`,`version`,`rule_key`,`label`,`value_json`,`effective_from`,`active`,`created_by`,`created_at`,`updated_at`)
SELECT 'seedcopy_' || lower(hex(randomblob(8))), 1, s.rule_key, s.label, json_object('text', s.text), unixepoch(), 1, 'system', unixepoch(), unixepoch()
FROM s
WHERE NOT EXISTS (SELECT 1 FROM `copy_overrides` WHERE `rule_key` = s.rule_key AND `active` = 1);
